### ISSUE TITLE
MSVC dynamic builds (DLL) lack complete exports.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-explorer#116]
This is the result of insufficient exports (for Windows builds) in the various libbitcoin libraries, all of which require augmentation:
- libbitcoin
- libbitcoin-blockchain
- libbitcoin-client
- libbitcoin-consensus
- libbitcoin-explorer
- libbitcoin-node
- libbitcoin-protocol
- libbitcoin-server

**Comment by evoskuil** [comment]
[![Synapsi bounty](https://synapsi.com/bb/c5/1c/e4/10/c124a10e0db5e4b97fc2af39.png)](https://synapsi.com/questions/how-to-implement-full-dll-export-support-201509051915)
Collect or contribute bitcoins for resolving this issue via Synapsi

**Comment by thewtex** [comment]
Some suggestions:

First, consider using [CMake](https://cmake.org) as a build system generator. This means multiple build configurations (autotools, and Visual Studio solution files for every version of Visual Studio that is supported) do not have to be maintained in duplicate. You can also use, for example, the fast command line [Ninja](https://ninja-build.org) build system on Windows (and Unix). It also makes nice, cross-platform tools for symbol export specification available.

Then, there are two approaches.

The quickfix is to let CMake automatically add the symbol export specification with [CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS](https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/).

The other approach is to add explicit export markup with preprocessor macros to the declarations desired. The macros can be created in a cross-platform way by using CMake's [GenerateExportHeader](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html) macro.

**Comment by evoskuil** [comment]
The problem isn't with the lack of export designation, it's that DLLs don't support the type of cross-library access that is implemented. We looked into this and it required a significant amount of code changes. Will revisit now that we have automated CMake project generation, and given that VS supports makefile compilation (MinGW).
