### ISSUE TITLE
Several commands are not implemented.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-explorer#13]
Several commands that were implemented in Python have been obsoleted and others have been re-implemented.

These are previously-existing commands that have been stubbed in pending implementation in C++.
- ~~address-embed~~ [implemented]
- ~~qrcode~~ [version3]

Previously-existing network commands that were dropped from original python implementation.
- fetch-public-key
- ~~fetch-utxo~~ [version3]
- watch-tx

Previously-existing Electrum commands that need to be rewritten to [BIP-39](https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki).
- ~~mnemonic-new~~ [implemented]
- ~~mnemonic-to-seed~~ [implemented]

New commands, based on [BIP-38](https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki).
- ~~ec-to-ek~~ [implemented]
- ~~ek-new~~ [implemented]
- ~~ek-public~~ [implemented]
- ~~ek-public-to-address~~ [implemented]
- ~~ek-public-to-ec~~ [implemented]
- ~~ek-to-address~~ [implemented]
- ~~ek-to-ec~~ [implemented]
- ~~token-new~~ [implemented]

New command, previously envisioned but not implemented.
- tx-sign

**Comment by skaht** [comment]
Will "qrcode" provide functionality similar to qrencode (http://fukuchi.org/works/qrencode/) that generates a QR png file from text, and zxing (latest zebra crossing fork https://github.com/glassechidna/zxing-cpp ) that converts a png file back into text?

**Comment by evoskuil** [comment]
That's the intent. The dependencies may be a bit problematic. I don't like conditional dependencies, but that may be the outcome.

**Comment by evoskuil** [comment]
The lower level functionality should be incorporated into libbitcoin (along with scan from a video feed).

**Comment by skaht** [comment]
I will have to experiment with zxing to see if it can handle rotated PNG images.

Assuming the most stressing use case,  people won't have the patience for properly aligning QR codes at checkout scanners, unlike Bitcoin wallets.

It might be quicker to look at the results of zxing to see if the scanned text follows BIP 20 BNF formula, versus performing an image rotation on all the pixels comprising an QR image. 

I'm not a QR technologist, but from my DSP background from 25+ years ago I'm guessing if zxing is applied it will need an interface for a video feed to convert a given frame into a PNG file.  If the BNF does not handle rotated QR codes and the trick above doesn't work, then an orientation discriminator may be needed to identify a 2D rotation angle to rotate a PNG image for zxing to consume.

If the QR image is not withing the proper depth-of-foucus (DOF), 2D image focusing software may also need to be applied.

**Comment by evoskuil** [comment]
Hey, not so fast... we have 4 more commands listed for @thecodefactory to implement!

**Comment by thecodefactory** [comment]
I think it's about time to close this issue in favor of a new one listing fetch-publc-key, watch-tx, and tx-sign (with descriptions) as an enhancement.  This issue can be referenced by the new one.  Thoughts?

**Comment by evoskuil** [comment]
Sure, but please add new before closing old.
