### ISSUE TITLE
Mnemonic is based on Electrum implementation.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-explorer#14]
This should be migrated to [BIP-39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki).

**Comment by thecodefactory** [comment]
Started getting BIP39 support for mnemonics going and am currently testing and working with evoskuil to get it into shape for inclusion.

**Comment by evoskuil** [comment]
Thanks to @thecodefactory for getting this done!
