### ISSUE TITLE
Add a command to simplify stealth.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-explorer#18]
Tto consolidate payment detection and pay/spend transaction generations.

**Comment by orweinberger** [comment]
The old sx had a `sx stealth-newkey`. What's the equivalent in bx? I could not find any documentation on how to create new stealth addresses.

**Comment by evoskuil** [comment]
Hi @orweinberger - If you enter SX command names at the BX command-line you should get some assistance, in this case:
```
$ bx stealth-newkey
This command is no longer supported. Use stealth-encode instead.
```
There is also extensive documentation on the [BX github wiki](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Stealth-Commands).

**Comment by orweinberger** [comment]
Thanks @evoskuil, is it possible for you to provide an elaborate example on how to generate a new stealth address and how one would spend coins sent to a stealth address?

**Comment by evoskuil** [comment]
I'm planning to do so as another tutorial in the wiki, but it will take some time before I get to it. Generating the address is pretty simple though, it only requires a public key.

https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-stealth-encode

**Comment by evoskuil** [comment]
stealth tx deprecated (no longer server-indexed).
