### ISSUE TITLE
script-to-address command doesn't load from STDIN

### ISSUE THREAD

**Issue by periodic1236** [libbitcoin/libbitcoin-explorer#216]
Here's one example. `bx script-to-address` doesn't accept serialized script (unlike `sx scripthash`). So following the [SX multisig example](http://sx.dyne.org/multisig.html), instead of `cat msig.script | sx scripthash`, I want to do:
```
$ cat msig.script | bx script-decode | bx script-to-address
37xnxAAtVbceQXeudE7edjmToaLPuh2bz3
```

Right now, this doesn't work when the base16 script in msig.script deserializes to more than one token (which is most of the time) because `script-to-address` tries to parse the input from stdin as a single token. Instead I have to use `xargs`:
```
$ cat msig.script | bx script-decode | xargs bx script-to-address
34CRZpt8j81rgh9QhzuBepqPi4cBQSjhjr
```

which is twice as long as the SX command.

I may add additional examples here as I play around with it more.

**Comment by evoskuil** [comment]
Try this:
```sh
$ cat msig.script | bx script-encode | bx script-to-address
```

**Comment by evoskuil** [comment]
I need to get around to porting the multisig and stealth examples to the BX wiki.

**Comment by evoskuil** [comment]
Oh, I see your msig.script file is base16 encoded. STDIN from that file *should* be a single base16 token. `script-decode` converts it to a set of tokens, which `script-to-address` accepts. I don't have a problem with this:
```sh
c:\>bx script-encode 2 [ 024745a36740327223a4dd3b9f42da6f03a5418d6ef18f1371e097f7dedc49b25f ] [ 024745a36740327223a4dd3b9f42da6f03a5418d6ef18f1371e097f7dedc49b25f ] [ 024745a36740327223a4dd3b9f42da6f03a5418d6ef18f1371e097f7dedc49b25f ] 3 checkmultisig > msig.script
5221024745a36740327223a4dd3b9f42da6f03a5418d6ef18f1371e097f7dedc49b25f21024745a36740327223a4dd3b9f42da6f03a5418d6ef18f1371e097f7dedc49b25f21024745a36740327223a4dd3b9f42da6f03a5418d6ef18f1371e097f7dedc49b25f53ae

c:\>type msig.script | bx script-decode
2 [ 024745a36740327223a4dd3b9f42da6f03a5418d6ef18f1371e097f7dedc49b25f ] [ 024745a36740327223a4dd3b9f42da6f03a5418d6ef18f1371e097f7dedc49b25f ] [ 024745a36740327223a4dd3b9f42da6f03a5418d6ef18f1371e097f7dedc49b25f ] 3 checkmultisig

c:\>type msig.script | bx script-decode | bx script-to-address
37xnxAAtVbceQXeudE7edjmToaLPuh2bz3
```

**Comment by evoskuil** [comment]
The example is actually quite a bit more straightforward in BX, since there is no reason whatsoever to encode the script as base16. BX preserves the option to encode and decode script for the case where the script is being extracted from a tx or some other encoded source. But when fabricating scripts base16 is just a nuisance.

Additionally, BX doesn't overload parameter types. SX, very inconsistently, would inspect the data in certain parameters to determine its type. This complicated implementation and documentation of the commands. BX strongly types each parameter so there are no ambiguities, and I haven't found that this hinders usability in any way.

**Comment by periodic1236** [comment]
I definitely prefer the design of BX and I'm glad you made the effort to standardize input/output processing.

As for your example on Windows, it actually illustrates the bug. Take another look at the two commands in my post. `37xnxAAtVbceQXeudE7edjmToaLPuh2bz3` is not the right address - it's the same thing that `bx script-to-address 0` returns. Sorry for not making that clear.

**Comment by evoskuil** [comment]
OK, I see it. Now that I have a repro I'll take care of it.

**Comment by evoskuil** [comment]
The `stdin=true` attribute was missing from the metadata declaration for `script-to-address` (added below):
```xml
  <command symbol="script-to-address" formerly="scripthash" category="TRANSACTION" description="Create a BIP16 pay-to-script-hash address from an encoded script.">
    <argument name="TOKEN" stdin="true" limit="-1" type="string" description="The script. If not specified the script is read from STDIN."/>
  </command>
```

**Comment by evoskuil** [comment]
Fixed by https://github.com/libbitcoin/libbitcoin-explorer/pull/217

**Comment by evoskuil** [comment]
@periodic1236 Thanks for writing this up!

**Comment by evoskuil** [comment]
The unit test suite is comprehensive inside of each command, but the coverage is quite light on the command line handing. This is mitigated in part by the fact that much of that code is generated, but if the metadata is incorrect ... :<.

**Comment by periodic1236** [comment]
Thanks! Nice to see it was a simple fix.
