### ISSUE TITLE
Windows BIP-39 mnemonic commands i8n break.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-explorer#229]
There is a known issue with boost::program_options when accepting command line arguments as unicode. Similarly there is a yet-to-be-determined issue with output of UTF-8 text to the console.

```bat
c:\>bx mnemonic-new baadf00dbaadf00dbaadf00dbaadf00d --language en
rival hurdle address inspire tenant almost turkey safe asset step lab boy

c:\>bx mnemonic-new baadf00dbaadf00dbaadf00dbaadf00d --language es
previo humilde actuar jarabe tabique ahorro tope pulpo anÃƒÂ­s seÃƒÂ±al lavar bahÃƒÂ­a

c:\>bx mnemonic-new baadf00dbaadf00dbaadf00dbaadf00d --language ja
ã­ã‚“ã‹ã‚“ ã™ãšã—ã„ ã‚ã²ã‚‹ ã›ãŸã‘ ã»ã¨ã‚“ã© ã‚ã‚“ã¾ã‚Š ã‚ã„ã‚ã‚“ ã®ã¹ã‚‹ ã„ãªã‹ ãµã¨ã‚‹ ãœã‚“ã‚Šã‚ƒã ãˆã„ã›ã„

c:\>bx mnemonic-new baadf00dbaadf00dbaadf00dbaadf00d --language zh
åš è‚‰ åœ° å± æƒœ å¤š é™ª è’ å›  æ‚£ ä¼Š åŸº
```

**Comment by evoskuil** [comment]
On osx and ubuntu the results are consistent, but appear incorrect for Spanish.
```sh
$ bx mnemonic-new baadf00dbaadf00dbaadf00dbaadf00d --language en
rival hurdle address inspire tenant almost turkey safe asset step lab boy

$ bx mnemonic-new baadf00dbaadf00dbaadf00dbaadf00d --language es
previo humilde actuar jarabe tabique ahorro tope pulpo anÃ­s seÃ±al lavar bahÃ­a

$ bx mnemonic-new baadf00dbaadf00dbaadf00dbaadf00d --language ja
ねんかん すずしい あひる せたけ ほとんど あんまり めいあん のべる いなか ふとる ぜんりゃく えいせい

$ bx mnemonic-new baadf00dbaadf00dbaadf00dbaadf00d --language zh
博 肉 地 危 惜 多 陪 荒 因 患 伊 基
```

**Comment by evoskuil** [comment]
The non-Windows behavior is correct, however the Spanish dictionary includes invalid words.

**Comment by evoskuil** [comment]
There was a trivial dictionary issue with Spanish in libbitcoin, which has been resolved in that repo. This issue is a general problem of mixing string interpretation (UTF8 vs. ANSI) in Windows and non-Windows APIs.

**Comment by skaht** [comment]
Think I may be running into a related "bip39" problem with a fresh build of bitcoin-explorer on OSX. (A fresh build of bitcoin-server completed successfully.)

configure: creating ./config.status
config.status: creating Makefile
config.status: creating libbitcoin-explorer.pc
config.status: executing depfiles commands
config.status: executing libtool commands
  CXX      src/src_libbitcoin_explorer_la-async_client.lo
  CXX      src/src_libbitcoin_explorer_la-callback_state.lo
  CXX      src/src_libbitcoin_explorer_la-config.lo
  CXX      src/src_libbitcoin_explorer_la-dispatch.lo
In file included from ../libbitcoin-explorer/src/dispatch.cpp:20:
In file included from ../libbitcoin-explorer/include/bitcoin/explorer/dispatch.hpp:26:
In file included from ../libbitcoin-explorer/include/bitcoin/explorer/command.hpp:52:
../libbitcoin-explorer/include/bitcoin/explorer/primitives/language.hpp:56:26: error: no member named 'bip39' in namespace 'libbitcoin'
    BCX_API language(bc::bip39::language language);
                     ~~~~^
../libbitcoin-explorer/include/bitcoin/explorer/primitives/language.hpp:68:26: error: no member named 'bip39' in namespace 'libbitcoin'
    BCX_API operator bc::bip39::language() const;
                     ~~~~^
../libbitcoin-explorer/include/bitcoin/explorer/primitives/language.hpp:93:9: error: no member named 'bip39' in namespace 'libbitcoin'
    bc::bip39::language value_;
    ~~~~^
../libbitcoin-explorer/include/bitcoin/explorer/primitives/language.hpp:93:16: error: qualified reference to 'language' is a constructor name rather
      than a type wherever a constructor can be declared
    bc::bip39::language value_;
               ^
In file included from ../libbitcoin-explorer/src/dispatch.cpp:32:
In file included from ../libbitcoin-explorer/include/bitcoin/explorer/generated.hpp:85:
../libbitcoin-explorer/include/bitcoin/explorer/commands/mnemonic-new.hpp:127:16: error: cannot initialize object parameter of type
      'libbitcoin::explorer::command' with an expression of type 'libbitcoin::explorer::commands::mnemonic_new'
        return get_argument_metadata()
               ^~~~~~~~~~~~~~~~~~~~~
../libbitcoin-explorer/include/bitcoin/explorer/commands/mnemonic-new.hpp:150:40: error: cannot initialize object parameter of type
      'libbitcoin::explorer::command' with an expression of type 'libbitcoin::explorer::commands::mnemonic_new'
        options_description& options = get_option_metadata();
                                       ^~~~~~~~~~~~~~~~~~~
6 errors generated.
make: *** [src/src_libbitcoin_explorer_la-dispatch.lo] Error 1

**Comment by evoskuil** [comment]
@skaht It looks like your sources are not current. The line:
```c
BCX_API language(bc::bip39::language language);
````
doesn't exist in current master or version2.

**Comment by skaht** [comment]
You are correct:-)  The build at this end did not have current bitcoin-explorer source code, my fault. Was checking out "version2" code, but from old March 31st cloned source code.

Performed "git clone --branch version2 --single-branch https://github.com/libbitcoin/libbitcoin-explorer" a few minutes ago, and I'm good to go... Thanks:-)

**Comment by evoskuil** [comment]
i8n support is now integrated across the stack. Windows builds now use utf8 internally and translate to/from to/from utf16 internally as necessary. command line arguments, environment variables, configuration settings and path translations are all handled. there are utf8 bugs in certain DOS utilities (such as `echo` and `type`) that can't be rectified, so piping non-ASCII between commands is problematic, but there is nothing that can be done about this.
