### ISSUE TITLE
documentation issue: how to use bx to sign multisig transaction

### ISSUE THREAD

**Issue by eriksank** [libbitcoin/libbitcoin-explorer#236]
There's an example in the documentation of how to do that with the sx tool, but I could not find the corresponding example in the bx tool. It would be really nice if someone transliterated the sx example to bx ...

**Comment by evoskuil** [comment]
The sx documentation gets you pretty close, and if you use the old command names bx will redirect you to the new ones. But I'll try and get the tutorial up soon after the pending release goes out.

**Comment by johtso** [comment]
Some documentation on this would be fantastic!

This is what I'm currently getting when trying to generate a 2-of-3 multisig script:
```
❯ ./bx-osx-x64-testnet script-encode "2 [ mo3dafuFJLPnxGCCJZrkqArCHTRGaEgE7K ] [ mkgD8skBDEucEvN48VJMnWzGLYkNH9TAai ] [ mfWyfRdsjA4Z5aAjfanB5oP2dvoGbsMWPQ ] 3 checkmultisig"
Unexpected error: the argument ('2 [ mo3dafuFJLPnxGCCJZrkqArCHTRGaEgE7K ] [ mkgD8skBDEucEvN48VJMnWzGLYkNH9TAai ] [ mfWyfRdsjA4Z5aAjfanB5oP2dvoGbsMWPQ ] 3 checkmultisig') for option is invalid
```

**Comment by evoskuil** [comment]
It looks like you are passing addresses as opposed to base16 encoded public keys.

**Comment by johtso** [comment]
Aha, thanks for the heads up!

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-explorer/wiki/How-to-Create-a-Multisig-Address
https://github.com/libbitcoin/libbitcoin-explorer/wiki/How-to-Spend-From-a-Multisig-Address
