### ISSUE TITLE
bx watch-address returns 'Bad stream'

### ISSUE THREAD

**Issue by brutesque** [libbitcoin/libbitcoin-explorer#248]
I cant' find any documentation on what this would mean. Can anyone help me find out how to fix this or figure out what is happening?

I'm running Version: 2.1.0 [mainnet] on Ubuntu 15.04

**Comment by brutesque** [comment]
I found documentation here: https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-watch-address.

**Comment by evoskuil** [comment]
The default configured server is currently an alias to an Obelisk server. This will be replaced by a libbitcoin server once the sync is complete. The default servers are maintained by Airbitz.

**Comment by brutesque** [comment]
Ah, might be a good time for me to test out the libbitcoin-server :)
Thanks
