### ISSUE TITLE
Generate and work wth testnet addresses

### ISSUE THREAD

**Issue by venzen** [libbitcoin/libbitcoin-explorer#251]
Is there a way to create and manipulate testnet addresses (starting with 'm' character) via BX ?

I compiled for testnet and have set the network option in the config file.

**Comment by evoskuil** [comment]
Yes, but unfortunately you must rebuild the stack. This can be done using the `install.sh` with the `--enable-testnet` switch.

**Comment by venzen** [comment]
Sure, I have done this. Just now, for my fun Friday I dist-upgraded a 12.04 t 14.04 and the boost-library won't build:

checking --enable-testnet option... yes
checking for boostlib >= 1.55.0... yes
configure: boost_CPPFLAGS : -I/usr/include
configure: boost_LDFLAGS : -L/usr/lib/x86_64-linux-gnu
checking whether the Boost::Chrono library is available... yes
configure: error: Could not find a version of the library!

No problem doing battle with Canonical's ever-more-crap Ubuntu, but it would help if you stated a reference known-good installation platform and dependencies.

For example, after redoing the oblivious to previous downloaded packages install.sh script for the 4th time, it errored out with a git problem "single-branch unknown option". So I add the git PPA and then ran into other issues related to 12.04.

No big deal, Linux is a guaranteed headache (as opposed to a direct Microsoft ass-fucking) - it would just be useful to know dependencies or a minimum Liinux OS.

**Comment by evoskuil** [comment]
The readme states:
```
Libbitcoin requires a C++11 compiler, currently minimum GCC 4.8.0 or Clang based on LLVM 3.5.
```
If you have this you have a sufficient version of Linux. The same document also states that you need to:
```
$ sudo apt-get install build-essential autoconf automake libtool pkg-config
```
And that you need to:
```
$ sudo apt-get install libboost-all-dev
```
I'm not sure hat you mean by, "the boost-library won't build". The error isn't a boost build error, it's a boost discovery error.

The above log indicates a problem with boost. Note that the boost m4 script misrepresents failures. There is typically a "yes" and then a failure on the next component, where the failure really applies to the previous component. But in any case, you need to verify your boost installation. Alternatively you can have the installer build boost (more below).

The install script is meant to provide a full working install, not to patch up the various parts of the build you may have already installed. The install script is the same that we use for pull and push testing in Travis. It's designed for predictability, not for speed. If you want incremental build and install of the various dependencies, then don't use the script.

It works best if you isolate it to a `--prefix=<directory>`, let it build boost using `--build-boost`, and use static linking via `--disable-shared`. This prevents libtool from reaching outside of the prefix directory to use dynamic versions of boost (and ICU as applicable). This will ensure a reliable build as it will have only trivial dependencies on platform shared libraries.

**Comment by venzen** [comment]
@evoskuil, thanks for the detailed explanation.

The compilation error I'm getting seems to be a result of dist-upgrade'ing Ubuntu 12.04 to 14.10:

checking for boostlib >= 1.55.0... yes
configure: boost_CPPFLAGS : -I/home/venzen/libbitcoin-server-build/libboost_local_lib/include
configure: boost_LDFLAGS : -L/home/venzen/libbitcoin-server-build/libboost_local_lib/lib
checking for bitcoin... yes
configure: bitcoin_CPPFLAGS : -DENABLE_TESTNET -I/home/venzen/libbitcoin-server-build/libboost_local_lib/include  
configure: bitcoin_LIBS : -L/home/venzen/libbitcoin-server-build/libboost_local_lib/lib -lbitcoin -lboost_chrono -lboost_date_time -lboost_filesystem -lboost_locale -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread -lrt -ldl -lsecp256k1  
checking for bitcoin_consensus... yes
configure: bitcoin_consensus_CPPFLAGS : -I/home/venzen/libbitcoin-server-build/libboost_local_lib/include  
configure: bitcoin_consensus_LIBS : -L/home/venzen/libbitcoin-server-build/libboost_local_lib/lib -lbitcoin-consensus -lcrypto  
checking whether C++ compiler accepts -std=c++11... yes
checking whether C++ compiler accepts -Wall... yes
checking whether C++ compiler accepts -Wextra... yes
checking whether C++ compiler accepts -Wpedantic... yes
checking whether C++ compiler accepts -Wno-missing-braces... yes
checking whether C++ compiler accepts -Wno-deprecated-declarations... yes
checking whether the linker accepts -fstack-protector... yes
checking whether the linker accepts -fstack-protector-all... yes
checking whether C++ compiler accepts -fvisibility-hidden... no
checking whether C++ compiler accepts -fvisibility-inlines-hidden... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libbitcoin-blockchain.pc
config.status: executing depfiles commands
config.status: executing libtool commands
configure: WARNING: unrecognized options: --enable-testnet
  CXX      src/src_libbitcoin_blockchain_la-blockchain.lo
  CXX      src/src_libbitcoin_blockchain_la-block_detail.lo
  CXX      src/src_libbitcoin_blockchain_la-checkpoints.lo
  CXX      src/src_libbitcoin_blockchain_la-db_interface.lo
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make: *** [src/src_libbitcoin_blockchain_la-checkpoints.lo] Error 1

**Comment by evoskuil** [comment]
Yeah, I'm not sure what to do with that. Not something we've seen.

**Comment by venzen** [comment]
It turns out the compiler error above is the result of not having enough memory on the server. 1GB RAM is not enough, 2GB eventually worked, so > 4GB seems to be a recommended minimum.

Also, because the install.sh script passes "--single-branch" to git, the minimum git version requirement is 1.7.10.

**Comment by evoskuil** [comment]
Great, thanks for the additional info.
