### ISSUE TITLE
Watching unconfirmed transactions and confirmed blocks coming in

### ISSUE THREAD

**Issue by eriksank** [libbitcoin/libbitcoin-explorer#253]
At the moment, I use bitcoind to get a stream of unconfirmed transactions (wallet notifications) and confirmed blocks (block notifications). This allows me to flag existing invoice records as paid. Is there a way to do that with bx or other tools in this toolkit?

**Comment by evoskuil** [comment]
BX is designed as a command line tool. It's not probably the best way to perform such integration. BX uses libbitcoin-client to perform requests against libbitcoin-server. You can subscribe to addresses but there is no block subscription, but that should not be necessary. Address history should be sufficient.

**Comment by eriksank** [comment]
One problem are multiple payments to one address. That is why I ended up dealing with wallet/block notifications. Apparently, libbitcoin-server should be able to do that:

https://github.com/libbitcoin/libbitcoin-server/wiki/Configuration-Settings

> # The block publishing service endpoint, defaults to 'tcp://*:9093'.

> block_publish = tcp://*:9093

> # The transaction publishing service endpoint, defaults to 'tcp://*:9094'.

> tx_publish = tcp://*:9094

Unfortunately, it is not documented how to use libbitcoin-server. All the pages that should do that, are empty. I suspect that it is not yet ready for prime time.

By the way, is it possible to listen to 500 addresses at the same time, or does that require starting 500 bx processes?

**Comment by evoskuil** [comment]
BX currently supports one subscription per watch-address command (process). This could easily be extended to support multiple per command. I wouldn't recomment a change to support dynamic changes to subscriptions however. That scenario is better left to client integration.

**Comment by evoskuil** [comment]
See tx and block subscrion methods here: https://github.com/libbitcoin/libbitcoin-server/blob/master/src/server_node.cpp
