### ISSUE TITLE
Testnet (TEST) key generation issues?

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-explorer#254]
In the bx.cfg file, made "network = testnet". Then executed "bx settings" with the BX_CONFIG pointing to the correct bx.cfg file.  Validated the configuration file took hold when the following was executed.

% bx fetch-height
428042          <- was the expected result for testnet

The issue is immediately after fetching the test-net height, the following generates a compressed private key, public key, and address for the main-net and not the test-net.

% echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | bx ec-new | bx ec-to-wif
Kz4q2e3oSAYkpUzxHBB7ewrQRJrUWd6hK2TbaDDaCGrcoyDzB9eV

Was expecting a private key starting with a "c".

% echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | bx ec-new | bx ec-to-public
0339f59bcac166bc0e7fb66b7d322e9d7e9d7be2b5ab489c2d8293d7c607cde2bd

% echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | bx ec-new | bx ec-to-public | bx ec-to-address
1GnF1oBb7VMAv3j3KoJrjF7rJVsmLsbTRh

Was expecting a public address starting with a "m" or "n".

Any suggestions synthesizing TEST keys and addresses?

**Comment by evoskuil** [comment]
You must compile for Trstnet (all libs), switching config is insufficient.

**Comment by skaht** [comment]
Thanks for the hint:-)  Had partial success for resolving the issue.

Found the CPPFLAGS "ENABLE_TESTNET" variable in C++ source code with some recursive greps. bx is dependent upon bitcoin-explorer, libbitcoin-client, and libbitcoin. Intuition indicates these should be the only libraries that may require cognizant of TEST coins.  For good measure, I performed a recursive grep for "ENABLE_TESTNET" in secp256k1. No hits were found as expected.

Added "-DENABLE_TESTNET" to the CPPFLAGS to the libbitcoin, libbitcoin-client, bitcoin-explorer, and libbitcoin config&build scripts at this end. Then I recompiled in this order.

The results from the following look good for generating a TEST WIF private key:)

echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | bx ec-new | bx ec-to-wif
cQRpVZ3esEF1yvUDfazF2GMU3Y9tB5CPP4c4gdg5hPWd4iGf3gCK

However, the behaviors/results from the other two sets of piped commands has not changed.

Any other suggestions?

**Comment by evoskuil** [comment]
Looks like you missed libbitcoin-explorer (the lib). Hard to say, and I'm on my phone. I recommend building with the bx install.sh, passing the --enable-testnet option.

**Comment by skaht** [comment]
I finally caved in and used the native bitcoin-explorer install.sh script to do the build for the first time. The results are identical. Hence, the issue still exists. 

Didn't want to wait for yet another boost download, so I pointed the build to use an existing boost root build, /Users/XXX/Projects/BX/boost/1.54.0.

Within my /Users/XXX/Projects/BX/bitcoin-explorer/libbitcoin-explorer that contained the install.sh file, I executed the following: 

% ./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test --build-dir=/Users/XXX/Projects/BX/bitcoin-explorer/build --with-boost=/Users/XXX/Projects/BX/boost/1.54.0 --enable-testnet

It took about 4 times as long to compile because only 2 of the 8 VM cores were running. Hence, I validated that changing line 77 of the install.sh file to the following worked:-) The Mac got much noisier & warmer, but got the job done quickly.

 70 SEQUENTIAL=1
 71 OS=`uname -s`
 72 if [[ $TRAVIS == true ]]; then
 73     PARALLEL=$SEQUENTIAL
 74 elif [[ $OS == Linux ]]; then
 75     PARALLEL=`nproc`
 76 elif [[ $OS == Darwin ]]; then
 77     PARALLEL=`sysctl -n hw.ncpu`  # was hard coded to 2
 78 else
 79     echo "Unsupported system: $OS"
 80     exit 1

I found the "bx" executable located in the /Users/Scott/Projects/BX/bitcoin-explorer/libbitcoin-explorer/data folder on my Mac with some msvc folders...

Finally, I did get the following warning from configuring outputs for libbitcoin-client and bitcoin-explorer, 
            configure: WARNING: you should use --build, --host, --target
            configure: WARNING: unrecognized options: --enable-testnet
while libbitcoin provided only the following warning
            configure: WARNING: you should use --build, --host, --target

**Comment by thecodefactory** [comment]
I'll test this out shortly.  I'm assuming you're using a checkout from master?

**Comment by skaht** [comment]
I did a "git pull" on everything today.  Crap... 
Noticed that I need to update the versions of libbitcoin_client and bitcoin_explorer_version.

set libbitcoin_version            = master
set libbitcoin_client_version  = version2
set bitcoin_explorer_version = version2

Let me fix the issue at my end, and get back to you.

**Comment by thecodefactory** [comment]
Ok, here's what I did (and got a working result, on debian).  Let me know if this helps!

``` # checkout fresh install from master ```
git clone https://github.com/libbitcoin/libbitcoin-explorer.git

``` # pre-emptively make sure we're picking up the right libs during the build by pointing PKG_CONFIG_PATH to the install destination dir (assumes a target installation dir of /usr/local/libbitcoin-explorer-testnet) ```
export PKG_CONFIG_PATH=/usr/local/libbitcoin-explorer-testnet/lib/pkgconfig

cd libbitcoin-explorer
./install.sh --prefix=/usr/local/libbitcoin-explorer-testnet

``` # run the provided test ```
cd /usr/local/libbitcoin-explorer-testnet/bin

echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | ./bx ec-new | ./bx ec-to-wif
cQRpVZ3esEF1yvUDfazF2GMU3Y9tB5CPP4c4gdg5hPWd4iGf3gCK

**Comment by thecodefactory** [comment]
@skaht Oh, I see what you're saying about the public address now -- something is off.

**Comment by skaht** [comment]
Okay, I'm finally got my home-grown build to compile and run with the correct "master" branch.

set libbitcoin_version            = master
set libbitcoin_client_version  = master
set bitcoin_explorer_version = master

The following looks good:

% echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | bx ec-new | bx ec-to-wif
cQRpVZ3esEF1yvUDfazF2GMU3Y9tB5CPP4c4gdg5hPWd4iGf3gCK

However, the following is still erroneous:

% echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | bx ec-new | bx ec-to-public
0339f59bcac166bc0e7fb66b7d322e9d7e9d7be2b5ab489c2d8293d7c607cde2bd

% echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | bx ec-new | bx ec-to-public | bx ec-to-address
1GnF1oBb7VMAv3j3KoJrjF7rJVsmLsbTRh

If I go to https://brainwallet.org/ and select "TEST" in the upper right hand corner, "Private Key", and "Compressed" and enter cQRpVZ3esEF1yvUDfazF2GMU3Y9tB5CPP4c4gdg5hPWd4iGf3gCK into the private key field the following address results: mwJCJrGZvWnRhACf3NHEZALBAVUUFYmSWo.

I'll use the install.sh script like I did above to see if the answer remains the same.

**Comment by thecodefactory** [comment]
A similar --enable-testnet needs to be in BITCOIN_EXPLORER_OPTIONS and BITCOIN_CLIENT_OPTIONS.  Building/testing now.

**Comment by skaht** [comment]
I made another bonehead mistake with the different "bx" executables.  I need to use ./bx like you did above to override my normal default paths for my custom build.  

Still getting the wrong answer for bx residing in the /Users/XXX/Projects/BX/bitcoin-explorer/build/libbitcoin-explorer/console directory at my end

% echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | ./bx ec-new | ./bx ec-to-public | ./bx ec-to-address
1GnF1oBb7VMAv3j3KoJrjF7rJVsmLsbTRh

**Comment by thecodefactory** [comment]
Still looking into!

**Comment by skaht** [comment]
Still working it at this end.

**Comment by skaht** [comment]
It's been over 17 years since I've done any C++ code development. 

I will start to look at the source code in the libbitcoin, libbitcoin-client, and libbitcoin-explorer packages containing CPPFLAGS for "ENABLE_TESTNET" for any potential adjacent flags that might need to be set.

% find libbitcoin -type f -exec grep ENABLE_TESTNET {} \; -print
# Implement --enable-testnet and define ENABLE_TESTNET and output ${testnet}.
    $as_echo "@%:@define ENABLE_TESTNET 1" >>confdefs.h
    testnet=-DENABLE_TESTNET
libbitcoin/autom4te.cache/output.0
# Implement --enable-testnet and define ENABLE_TESTNET and output ${testnet}.
    $as_echo "@%:@define ENABLE_TESTNET 1" >>confdefs.h
    testnet=-DENABLE_TESTNET
libbitcoin/autom4te.cache/output.1
# Implement --enable-testnet and define ENABLE_TESTNET and output ${testnet}.
    $as_echo "@%:@define ENABLE_TESTNET 1" >>confdefs.h
    testnet=-DENABLE_TESTNET
libbitcoin/autom4te.cache/output.2
m4trace:configure.ac:132: -2- m4_pattern_allow([^ENABLE_TESTNET$])
libbitcoin/autom4te.cache/traces.0
m4trace:configure.ac:132: -2- AC_DEFINE_TRACE_LITERAL([ENABLE_TESTNET])
m4trace:configure.ac:132: -2- m4_pattern_allow([^ENABLE_TESTNET$])
m4trace:configure.ac:133: -2- AC_SUBST([testnet], [-DENABLE_TESTNET])
libbitcoin/autom4te.cache/traces.1
m4trace:configure.ac:132: -2- m4_pattern_allow([^ENABLE_TESTNET$])
libbitcoin/autom4te.cache/traces.2
      <PreprocessorDefinitions Condition="'$(Option-testnet)' == 'true'">ENABLE_TESTNET;%(PreprocessorDefinitions)</PreprocessorDefinitions>
libbitcoin/builds/msvc/vs2013/libbitcoin/libbitcoin.props
      <PreprocessorDefinitions Condition="'$(Option-testnet)' == 'true'">ENABLE_TESTNET;%(PreprocessorDefinitions)</PreprocessorDefinitions>
libbitcoin/builds/msvc/vs2013/libbitcoin.import.props
# Implement --enable-testnet and define ENABLE_TESTNET and output ${testnet}.
    $as_echo "#define ENABLE_TESTNET 1" >>confdefs.h
    testnet=-DENABLE_TESTNET
libbitcoin/configure
# Implement --enable-testnet and define ENABLE_TESTNET and output ${testnet}.
AS_CASE([${enable_testnet}], [yes], AC_DEFINE([ENABLE_TESTNET]))
AS_CASE([${enable_testnet}], [yes], AC_SUBST([testnet], [-DENABLE_TESTNET]))
libbitcoin/configure.ac
#ifdef ENABLE_TESTNET
libbitcoin/include/bitcoin/bitcoin/constants.hpp
#ifdef ENABLE_TESTNET
libbitcoin/include/bitcoin/bitcoin/wallet/address.hpp
#ifdef ENABLE_TESTNET
libbitcoin/src/block.cpp
#ifdef ENABLE_TESTNET
libbitcoin/src/constants.cpp
#ifdef ENABLE_TESTNET
libbitcoin/src/network/protocol.cpp
    // This changes based on ENABLE_TESTNET, so the test condition must vary.
#ifdef ENABLE_TESTNET
libbitcoin/test/hash.cpp
#ifdef ENABLE_TESTNET
libbitcoin/test/key_formats.cpp
#ifdef ENABLE_TESTNET
libbitcoin/test/message.cpp
#ifdef ENABLE_TESTNET
libbitcoin/test/stealth_address.cpp


% find libbitcoin-client -type f -exec grep ENABLE_TESTNET {} \; -print
      <PreprocessorDefinitions Condition="'$(Option-testnet)' == 'true'">ENABLE_TESTNET;%(PreprocessorDefinitions)</PreprocessorDefinitions>
libbitcoin-client/builds/msvc/vs2013/libbitcoin.import.props


% find libbitcoin-explorer -type f -exec grep ENABLE_TESTNET {} \; -print
Binary file libbitcoin-explorer/.git/objects/pack/pack-99b7b875c2c6c899d464efd9e9c9c8f8b356d41f.pack matches
libbitcoin-explorer/.git/objects/pack/pack-99b7b875c2c6c899d464efd9e9c9c8f8b356d41f.pack
      <PreprocessorDefinitions Condition="'$(Option-testnet)' == 'true'">ENABLE_TESTNET;%(PreprocessorDefinitions)</PreprocessorDefinitions>
libbitcoin-explorer/builds/msvc/vs2013/libbitcoin.import.props
#ifdef ENABLE_TESTNET
libbitcoin-explorer/include/bitcoin/explorer/define.hpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/ec-to-wif.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/fetch-balance.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/fetch-tx.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/hd-to-address.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/hd-to-wif.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/message-sign.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/message-validate.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/script-to-address.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/tx-decode.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/tx-encode.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/wif-to-ec.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/commands/wif-to-public.cpp
#ifndef ENABLE_TESTNET
libbitcoin-explorer/test/primitives/address.cpp

**Comment by thecodefactory** [comment]
I'm running a test currently, will let you know what I find.

**Comment by skaht** [comment]
It's becoming very apparent that libbitcoin must be compiled for either mainnet or testnet.  There is no toggling back and forth from the config file like bitcoin-core.

**Comment by thecodefactory** [comment]
Oh no, definitely not.  It's a separate build for testnet for sure.

**Comment by skaht** [comment]
With the CPPFLAGS being used the way they are for ENABLE_TESTNET testnet and mainnet compilations are mutually exclusive for the libbitcoin package.  This becomes evident from examining the following list of files: 

libbitcoin/src/constants.cpp libbitcoin/src/network/protocol.cpp libbitcoin/test/hash.cpp libbitcoin/test/key_formats.cpp libbitcoin/test/message.cpp libbitcoin/test/stealth_address.cpp libbitcoin/test/key_formats.cpp libbitcoin/test/message.cpp libbitcoin/test/stealth_address.cpp

**Comment by skaht** [comment]
protocol.cpp is the clincher

 49 #ifdef ENABLE_TESTNET
 50 const hosts::authority_list protocol::default_seeds =
 51 {
 52     { "testnet-seed.alexykot.me", 18333 },
 53     { "testnet-seed.bitcoin.petertodd.org", 18333 },
 54     { "testnet-seed.bluematt.me", 18333 },
 55     { "testnet-seed.bitcoin.schildbach.de", 18333 }
 56 };
 57 #else
 58 const hosts::authority_list protocol::default_seeds =
 59 {
 60     { "seed.bitnodes.io", 8333 },
 61     { "seed.bitcoinstats.com", 8333 },
 62     { "seed.bitcoin.sipa.be", 8333 },
 63     { "dnsseed.bluematt.me", 8333 },
 64     { "seed.bitcoin.jonasschnelli.ch", 8333 },
 65     { "dnsseed.bitcoin.dashjr.org", 8333 }
 66 
 67     // Previously also included:
 68     // bitseed.xf2.org:8333
 69     // archivum.info:8333
 70     // progressbar.sk:8333
 71     // faucet.bitcoin.st:8333
 72     // bitcoin.securepayment.cc:8333
 73 };
 74 #endif

**Comment by thecodefactory** [comment]
I'm not sure I follow.  I do use testnet frequently though from the libbitcoin-server install.sh and protocol is certainly working there.  This is the first time I'm trying the client side (libbitcoin-explorer) with testnet, so it's taking me a second to trace it through.

**Comment by thecodefactory** [comment]
I think I'm on to it, but need some more time.  Definitely found an error anyway ;-)

**Comment by skaht** [comment]
Its a little disconcerting seeing an asymmetry of boost test cases for libbitcoin-explorer. Look at:
libbitcoin-explorer/test/commands/script-to-address.cpp, 
libbitcoin-explorer/test/commands/wif-to-public.cpp,
libbitcoin-explorer/test/primitives/address.cpp

**Comment by skaht** [comment]
Signing out.  Need to sleep. Thank:-)

**Comment by thecodefactory** [comment]
No problem, will update when I have results.  As for the test cases, I think that's just a matter of so few of us working on this.  I'll update the tests if/when this is fixed ;-)

**Comment by evoskuil** [comment]
All components should be built with --enable-testnet, anything else is not supported and could break at any time. Eventually this conditional compile will be removed. Using the installer without modification achieves this. 

The test cases are differentiated because the build is differentiated. This is necessary as long as the conditional compile exists. The tests cases cover the testnet address scenarios, so if the tests are passing it indicates the build is correct.

**Comment by evoskuil** [comment]
It appears that the command is producing the correct result. The `--version` is not specified, making it `0x00` (the default), which specifies a mainnet P2PKH address. Specifying a version byte of `0x6F`, or more specifically `--version=111` should give you the desired result.

This is a case where the conditional build is not used to change the default, since we intend to remove it and because there are other version bytes unrelated to testnet vs. mainnet. However it may (or may not) be the case that the conditional build is still required.  When working with testnet you should compile with `--enable-testnet`, but some features may not require it.

**Comment by thecodefactory** [comment]
This corrects the issue here.  I will see about adding appropriate tests for this.

> echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | ./bx ec-new | ./bx ec-to-public | ./bx ec-to-address --version=111
mwJCJrGZvWnRhACf3NHEZALBAVUUFYmSWo

**Comment by skaht** [comment]
You guys are great for resolving this issue so quickly! 

The detail for adding "--version=111" fixed the issue for my custom build as well. The adding of "-DENABLE_TESTNET" to the CPPFLAGS for building libbitcoin, libbitcoin-client, bitcoin-explorer, and libbitcoin was sufficient. Configuring with the install.sh most definitely required the "--enable-testnet" flag to be set to set -DENABLE_TESTNET down in the bowels of the configure.

For others that may read this concerning the "--version=111" flag passed by bx ec-to-address, visiting https://en.bitcoin.it/wiki/List_of_address_prefixes complements the examples at https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-ec-to-address.

Another rough corner I noticed was that when the bx-explorer code was configured and compiled using --enable-testnet, the ec-to-wif and sub-command was locked into generating wif keys for the testnet, independent of tweaking the bx.cfg file to use mainnet and committing the change with an appropriate bx settings command.

As a libbitcoin newbie, it would be very nice if the key generation behaviors of bx for mainet or testnet were controlled by its config file (e.g., bx.cfg) versus how it was compiled based upon --enable-testnet flags being passed. Is it reasonable to request to have the master branches of bx support a slightly enhanced semantic for the "network" variable within the config file to encompass controlling the key generation behavior for either mainnet or testnet keys and addreses?

For example, with the code compiled with --enable-testnet, and a ./bx settings returning
settings
{
    general
    {
        network mainnet
        retries 2
        wait 2000
    }
    logging
    {
        debug_file debug.log
        error_file error.log
    }
    mainnet
    {
        cert_file ""
        server_cert_key ""
        url tcp://bitcoin-crate.airbitz.co:9091
    }
    testnet
    {
        cert_file ""
        server_cert_key ""
        url tcp://obelisk-testnet.airbitz.co:9091
    }
}

it would be nice if:
 
% echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | ./bx ec-new | ./bx ec-to-wif
Kz4q2e3oSAYkpUzxHBB7ewrQRJrUWd6hK2TbaDDaCGrcoyDzB9eV

versus 

% echo "a76e98bda0269269a3a2bbc98108ac6cc614c54b94d48f502745b5e74eaff613" | ./bx ec-new | ./bx ec-to-wif
cQRpVZ3esEF1yvUDfazF2GMU3Y9tB5CPP4c4gdg5hPWd4iGf3gCK

**Comment by evoskuil** [comment]
Yes, elimination of the testnet conditional compilation would require testnet functionality to be based on configuration and/or parameterization, depending on the scenario.

**Comment by Abdullah114** [comment]
Hi, I recompiled all libraries with --enable-testnet option and now when I type bx i receive:
>> Usage: bx COMMAND [--help]
Version: 2.2.1 [testnet]
Info: The bx commands are:

Also in the bx.cfg I changed 
>> network = testnet

When I fetch height, it shows a correct blockchain height for the testnet.
>> bx fetch-height
554230

Nevertheless when I try to generate a testnet address using piped command, as far as I understand I receive a mainnet address.
>> bx seed | bx ec-new | bx ec-to-public | bx ec-to-address
1DDKoV67jHANi5aG6ax1KngBzvfkynUTmH

Can you please explain what I am doing wrong?
Thanks.

**Comment by skaht** [comment]
Almost there... 

Try `bx seed | bx ec-new | bx ec-to-public | bx ec-to-address -v 111`. 

70% of the way down https://github.com/libbitcoin/libbitcoin-explorer/pull/269#issuecomment-137988187 provides values for versions (-v) when keys and addresses for altcoins are to be synthesized.

**Comment by Abdullah114** [comment]
Thanks a lot skaht!
I appreciate your help.

**Comment by evoskuil** [comment]
Unfortunately we have not fully removed the conditional compilation requirement. In some cases (like address creation) compilation doesn't affect outcome - which is the objective for all operations. In other cases outcome is still affected by the compiler option.

**Comment by Abdullah114** [comment]
Thanks.

Suppose I created a private testnet bitcoin network using docker such as (https://geraldkaszuba.com/creating-your-own-experimental-bitcoin-network/), is there any way I could use bx on it?

**Comment by evoskuil** [comment]
Sure, you can configure bx to use it for both client-server and p2p (`send-tx-p2p` and `send-tx-node`) operations.  client-server is configured via the config file. `sent-tx-node` is via the command line. `send-tx-p2p` is a little more challenging if you intend to fully isolate bx to talking to your own nodes. I would recommend you just use `sent-tx-node` (until the 3.0 release when this will get a little easier).

**Comment by Abdullah114** [comment]
Thanks for prompt reply.
I'll try it and update you.

**Comment by evoskuil** [comment]
Server sync in v2 can be a challenge. I recommend setting a checkpoint that's near the top.
