### ISSUE TITLE
Issue with fully building bx the preferred libbitcoin way on a Mac

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-explorer#255]
I have Xcode, command line tools, and Homebrew installed on your Mac with the following significant packages installed using Homebrew: autoconf, automake, curl, libtool, pkgconfig, and wget.

Ensured `clang++ --version` >= clang-600.0.54, worth examining https://gist.github.com/yamaya/2924292

Been able to successfully bx compile if I compile boost v1.54.0 myself (or use a homebrew version on boost) and set the DYLD_LIBRARY_PATH to something like /Users/XXX/Projects/BX/boost/1.54.0/lib using:

% ./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test --build-dir=/Users/XXX/Projects/BX/bitcoin-explorer/build --with-boost=/Users/XXX/Projects/BX/boost/1.54.0

But can't get the following to work:

% cd /Users/XXX/Projects/BX/bitcoin-explorer
% git clone --branch master --single-branch https://github.com/libbitcoin/libbitcoin-explorer
% cd libbitcoin-explorer
% ./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test --build-dir=/Users/XXX/Projects/BX/bitcoin-explorer/build --build-boost

Almost got it the build to complete, but I get the following error on the home stretch, even with the "--disable-shared" tucked on to the end of the install.sh command above.
......
  CXX      test/commands/test_libbitcoin_explorer_test-wrap-encode.o
  CXXLD    test/libbitcoin_explorer_test
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
FAIL: libbitcoin_explorer_test_runner.sh
============================================================================
Testsuite summary for libbitcoin-explorer 2.1.1
============================================================================
\# TOTAL: 1
\# PASS:  0
\# SKIP:  0
\# XFAIL: 0
\# FAIL:  1
\# XPASS: 0
\# ERROR: 0
============================================================================
See ./test-suite.log
Please report to eric@voskuil.org
============================================================================
make[2]: *** [test-suite.log] Error 1
make[1]: *** [check-TESTS] Error 2
make: *** [check-am] Error 2
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
cat test-suite.log
------------------------------
=================================================
   libbitcoin-explorer 2.1.1: ./test-suite.log
=================================================

\# TOTAL: 1
\# PASS:  0
\# SKIP:  0
\# XFAIL: 0
\# FAIL:  1
\# XPASS: 0
\# ERROR: 0

.. contents:: :depth: 2

FAIL: libbitcoin_explorer_test_runner.sh
========================================

dyld: Library not loaded: libboost_unit_test_framework.dylib
  Referenced from: /Users/XXX/Projects/BX/bitcoin-explorer/build/libbitcoin-explorer/test/.libs/libbitcoin_explorer_test
  Reason: image not found
./libbitcoin_explorer_test_runner.sh: line 21: 40292 Trace/BPT trap: 5       ./test/libbitcoin_explorer_test ${BOOST_UNIT_TEST_OPTIONS}
FAIL libbitcoin_explorer_test_runner.sh (exit status: 133)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Any suggestions?

**Comment by evoskuil** [comment]
The libtool is linking dynamically and not finding `libboost_unit_test_framework.dylib`. There is no way that I know of to force libtool to use a dynamic library that you intend as opposed to a system level library (if it finds one). So it's apparently linking to a system level install which doesn't include boost test. Therefore if upgrading your system to boost 1.54 (including boost test) is not an option, then you need to build statically in a prefix directory. It looks like you have the static build option misspelled, it should be:  `--disable-shared`

**Comment by skaht** [comment]
I had a typo in submitting this issue.  Having "--disable-shared" set does not fix the issue.  Don't expend much bandwidth resolving this issue.  This is more of an FYSA...

**Comment by evoskuil** [comment]
OK, note that this configuration is regularly verified via the Travis build.
