### ISSUE TITLE
Is tx-encode lock_time functioning properly for testnet? 

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-explorer#256]
Here are three examples.  The first command behaves as expected. The second and third commands fail but use the same base command. The second command is suffixed with "-v 1 -l  428500" that assumes the lock_time can be supplied as decimal.  The third command is suffixed with -"v 1 -l 0x000689d4" that assumes the lock_time can be provided as a hex number.

% bx tx-encode -i 9fa2ef129884d1efd9bd860a4d83fe82ae05e3b7af1e43857e83c923e4fbd4ce:0 -i 58abf676e318d3114a3a27c13d3d4349b3a7a551d9149a9ce6c130f751d057a4:0 -o mtBuosVqynvVfMXLnuPLsBfNtn4DscQirW:100000000 -o mtAt5BpwY36j7nNhwAfBD35ZqtbiD6Z1W6:4900100000
0100000002ced4fbe423c9837e85431eafb7e305ae82fe834d0a86bdd9efd1849812efa29f0000000000ffffffffa457d051f730c1e69c9a14d951a5a7b349433d3dc1273a4a11d318e376f6ab580000000000ffffffff0200e1f505000000001976a9148affa823117f86b627c13006042e757bea1b202988aca0971124010000001976a9148acdcaaf8fea863f0d5a7b770c330cf6f899fdba88ac00000000

% bx tx-encode -i 9fa2ef129884d1efd9bd860a4d83fe82ae05e3b7af1e43857e83c923e4fbd4ce:0 -i 58abf676e318d3114a3a27c13d3d4349b3a7a551d9149a9ce6c130f751d057a4:0 -o mtBuosVqynvVfMXLnuPLsBfNtn4DscQirW:100000000 -o mtAt5BpwY36j7nNhwAfBD35ZqtbiD6Z1W6:4900100000 -v 1 -l  428500
The specified lock time is ineffective because all sequences are set to the maximum value.

% bx tx-encode -i 9fa2ef129884d1efd9bd860a4d83fe82ae05e3b7af1e43857e83c923e4fbd4ce:0 -i 58abf676e318d3114a3a27c13d3d4349b3a7a551d9149a9ce6c130f751d057a4:0 -o mtBuosVqynvVfMXLnuPLsBfNtn4DscQirW:100000000 -o mtAt5BpwY36j7nNhwAfBD35ZqtbiD6Z1W6:4900100000 -v 1 -l 0x000689d4
Error: the argument ('0x000689d4') for option '--lock_time' is invalid

Tells me that lock_time should not be a hex value.

Any suggestions?

**Comment by skaht** [comment]
I'm beginning to doubt that the lock_time error is at my end.

Locktime details from https://en.bitcoin.it/wiki/Protocol_documentation#tx
	0			Not Locked
	<500000000  	Block number at which this transaction is locked
	>= 500000000	UNIX timestamp at which this transaction is locked

When the lock_time is explicitly set, its results only appear to work properly only when explicitly set to zero.

% bx tx-encode -i 9fa2ef129884d1efd9bd860a4d83fe82ae05e3b7af1e43857e83c923e4fbd4ce:0 -i 58abf676e318d3114a3a27c13d3d4349b3a7a551d9149a9ce6c130f751d057a4:0 -o mtBuosVqynvVfMXLnuPLsBfNtn4DscQirW:100000000 -o mtAt5BpwY36j7nNhwAfBD35ZqtbiD6Z1W6:4900100000 -l 0
0100000002ced4fbe423c9837e85431eafb7e305ae82fe834d0a86bdd9efd1849812efa29f0000000000ffffffffa457d051f730c1e69c9a14d951a5a7b349433d3dc1273a4a11d318e376f6ab580000000000ffffffff0200e1f505000000001976a9148affa823117f86b627c13006042e757bea1b202988aca0971124010000001976a9148acdcaaf8fea863f0d5a7b770c330cf6f899fdba88ac00000000

The output of the second command in the window above matches the contents of the
libbitcoin-explorer/include/bitcoin/explorer/commands/tx-encode.hpp file that contains:
75 #define BX_TX_ENCODE_LOCKTIME_CONFLICT \
76     "The specified lock time is ineffective because all sequences are set to the maximum value."

The BX_TX_ENCODE_LOCKTIME_CONFLICT CPP variable is contained within 
libbitcoin-explorer/src/commands/tx-encode.cpp file that contains:
 37 console_result tx_encode::invoke(std::ostream& output, std::ostream& error)
 38 {
 39     // Bound parameters.
 40     const auto locktime = get_lock_time_option();
 41     const auto version = get_version_option();
 42     const auto& inputs = get_inputs_option();
 43     const auto& outputs = get_outputs_option();
 44 
 45     tx_type tx;
 46     tx.version = version;
 47     tx.locktime = locktime;
 48 
 49     for (const tx_input_type& input: inputs)
 50         tx.inputs.push_back(input);
 51 
 52     for (const std::vector<tx_output_type>& output_sets: outputs)
 53         for (const auto& output: output_sets)
 54             tx.outputs.push_back(output);
 55 
 56     if (is_locktime_conflict(tx))
 57     {
 58         error << BX_TX_ENCODE_LOCKTIME_CONFLICT << std::endl;
 59         return console_result::failure;
 60     }
 61 
 62     output << transaction(tx) << std::endl;
 63     return console_result::okay;
 64 }

Hence, the second command fails on line 56, which prints the error on line 58.

bitcoin-explorer/include/bitcoin/explorer/commands/tx-encode.hpp contains:
194     /**
195      * Get the value of the lock_time option.
196      */
197     BCX_API virtual uint32_t& get_lock_time_option()
198     {
199         return option_.lock_time;
200     }

**Comment by evoskuil** [comment]
locktime is related to sequence, as the error message implies. See: http://bitcoin.stackexchange.com/questions/2025/what-is-txins-sequence

**Comment by evoskuil** [comment]
If the sequence for all inputs is max the tx is final. Otherwise if locktime is zero the tx is final.

See: https://github.com/libbitcoin/libbitcoin/blob/master/src/transaction.cpp#L168

BX therefore returns an error when a locktime is non-zero and all input sequences are max, as the user's intent is ambiguous.

See: https://github.com/libbitcoin/libbitcoin/blob/master/src/transaction.cpp#L188

To specify an input sequence in BX see: https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-tx-encode

```
-i [--input]         The set of transaction input points encoded as      
                     TXHASH:INDEX:SEQUENCE. TXHASH is a Base16           
                     transaction hash. INDEX is the 32 bit input index in
                     the context of the transaction. SEQUENCE is the     
                     optional 32 bit input sequence and defaults to the  
                     maximum value.
```
