### ISSUE TITLE
mnemonic-to-seed indicating "The passphrase option requires an ICU build."

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-explorer#257]
Was trying to manually double check/learn from the test vectors from https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt.  In particular, the test vector being tried was:

`“00000000000000000000000000000000”,
"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
"c55257c360c07c72029aebc1b53c05ed0362ada38ead3e3e9efa3708e53495531f09a6987599d18264c1e1c92f2cf141630c7a3c4ab7c81b2f001698e7463b04"`

The first time around I got the following message was returned:

`% echo "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" | bx mnemonic-to-seed -p 00000000000000000000000000000000`
`The passphrase option requires an ICU build.`

So I recompiled bx with icu using the following command:

`./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test --build-dir=/Users/XXX/Projects/BX/bitcoin-explorer/build --with-boost=/Users/XXX/Projects/BX/boost/1.54.0 --build-icu`

Confirmed the path to bx was for the new executable, but the results for the text piped to bx mnemonic-to-seed remained the same.

Any suggestions?

**Comment by evoskuil** [comment]
Add --with-icu (see https://github.com/libbitcoin/libbitcoin/blob/master/README.md)

**Comment by skaht** [comment]
Build the code on a Mac Book Pro with the command:
`./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test --build-dir=/Users/XXX/Projects/BX/bitcoin-explorer/build --with-boost=/Users/XXX/Projects/BX/boost/1.54.0 --build-icu --with-icu`

Minus the Github markdown escapes, the following is the is the result when the compilation for the build finishes:

 build-aux/install-sh -c -d '/Users/XXX/Projects/BX/bitcoin-explorer/test/lib/pkgconfig'
 /usr/bin/install -c -m 644 libbitcoin-explorer.pc '/Users/XXX/Projects/BX/bitcoin-explorer/test/lib/pkgconfig'
 build-aux/install-sh -c -d '/Users/XXX/Projects/BX/bitcoin-explorer/test/etc/libbitcoin'
 /usr/bin/install -c -m 644 data/bx.cfg '/Users/XXX/Projects/BX/bitcoin-explorer/test/etc/libbitcoin'
/Applications/Xcode.app/Contents/Developer/usr/bin/make  test/libbitcoin_explorer_test
  CXX      test/commands/test_libbitcoin_explorer_test-address-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-address-embed.o
  CXX      test/commands/test_libbitcoin_explorer_test-address-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-address-validate.o
  CXX      test/commands/test_libbitcoin_explorer_test-base16-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-base16-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-base58-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-base58-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-base58check-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-base58check-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-base64-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-base64-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-bci-fetch-last-height.o
  CXX      test/commands/test_libbitcoin_explorer_test-bci-history.o
  CXX      test/commands/test_libbitcoin_explorer_test-bitcoin160.o
  CXX      test/commands/test_libbitcoin_explorer_test-bitcoin256.o
  CXX      test/commands/test_libbitcoin_explorer_test-blke-fetch-transaction.o
  CXX      test/commands/test_libbitcoin_explorer_test-btc-to-satoshi.o
  CXX      test/commands/test_libbitcoin_explorer_test-cert-new.o
  CXX      test/commands/test_libbitcoin_explorer_test-cert-public.o
  CXX      test/commands/test_libbitcoin_explorer_test-ec-add-secrets.o
  CXX      test/commands/test_libbitcoin_explorer_test-ec-add.o
  CXX      test/commands/test_libbitcoin_explorer_test-ec-lock.o
  CXX      test/commands/test_libbitcoin_explorer_test-ec-multiply-secrets.o
  CXX      test/commands/test_libbitcoin_explorer_test-ec-multiply.o
  CXX      test/commands/test_libbitcoin_explorer_test-ec-new.o
  CXX      test/commands/test_libbitcoin_explorer_test-ec-to-address.o
  CXX      test/commands/test_libbitcoin_explorer_test-ec-to-public.o
  CXX      test/commands/test_libbitcoin_explorer_test-ec-to-wif.o
  CXX      test/commands/test_libbitcoin_explorer_test-ec-unlock.o
  CXX      test/commands/test_libbitcoin_explorer_test-fetch-balance.o
  CXX      test/commands/test_libbitcoin_explorer_test-fetch-header.o
  CXX      test/commands/test_libbitcoin_explorer_test-fetch-height.o
  CXX      test/commands/test_libbitcoin_explorer_test-fetch-history.o
  CXX      test/commands/test_libbitcoin_explorer_test-fetch-public-key.o
  CXX      test/commands/test_libbitcoin_explorer_test-fetch-stealth.o
  CXX      test/commands/test_libbitcoin_explorer_test-fetch-tx-index.o
  CXX      test/commands/test_libbitcoin_explorer_test-fetch-tx.o
  CXX      test/commands/test_libbitcoin_explorer_test-fetch-utxo.o
  CXX      test/commands/test_libbitcoin_explorer_test-genaddr.o
  CXX      test/commands/test_libbitcoin_explorer_test-genpriv.o
  CXX      test/commands/test_libbitcoin_explorer_test-genpub.o
  CXX      test/commands/test_libbitcoin_explorer_test-hd-new.o
  CXX      test/commands/test_libbitcoin_explorer_test-hd-private.o
  CXX      test/commands/test_libbitcoin_explorer_test-hd-public.o
  CXX      test/commands/test_libbitcoin_explorer_test-hd-to-address.o
  CXX      test/commands/test_libbitcoin_explorer_test-hd-to-ec.o
  CXX      test/commands/test_libbitcoin_explorer_test-hd-to-public.o
  CXX      test/commands/test_libbitcoin_explorer_test-hd-to-wif.o
  CXX      test/commands/test_libbitcoin_explorer_test-help.o
  CXX      test/commands/test_libbitcoin_explorer_test-initchain.o
  CXX      test/commands/test_libbitcoin_explorer_test-input-set.o
  CXX      test/commands/test_libbitcoin_explorer_test-input-sign.o
  CXX      test/commands/test_libbitcoin_explorer_test-input-validate.o
  CXX      test/commands/test_libbitcoin_explorer_test-message-sign.o
  CXX      test/commands/test_libbitcoin_explorer_test-message-validate.o
  CXX      test/commands/test_libbitcoin_explorer_test-mnemonic-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-mnemonic-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-mnemonic-new.o
  CXX      test/commands/test_libbitcoin_explorer_test-mnemonic-to-seed.o
  CXX      test/commands/test_libbitcoin_explorer_test-mpk.o
  CXX      test/commands/test_libbitcoin_explorer_test-newseed.o
  CXX      test/commands/test_libbitcoin_explorer_test-qrcode.o
  CXX      test/commands/test_libbitcoin_explorer_test-ripemd160.o
  CXX      test/commands/test_libbitcoin_explorer_test-satoshi-to-btc.o
  CXX      test/commands/test_libbitcoin_explorer_test-script-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-script-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-script-to-address.o
  CXX      test/commands/test_libbitcoin_explorer_test-seed.o
  CXX      test/commands/test_libbitcoin_explorer_test-send-tx-node.o
  CXX      test/commands/test_libbitcoin_explorer_test-send-tx-p2p.o
  CXX      test/commands/test_libbitcoin_explorer_test-send-tx.o
  CXX      test/commands/test_libbitcoin_explorer_test-sendtx-bci.o
  CXX      test/commands/test_libbitcoin_explorer_test-settings.o
  CXX      test/commands/test_libbitcoin_explorer_test-sha160.o
  CXX      test/commands/test_libbitcoin_explorer_test-sha256.o
  CXX      test/commands/test_libbitcoin_explorer_test-sha512.o
  CXX      test/commands/test_libbitcoin_explorer_test-showblkhead.o
  CXX      test/commands/test_libbitcoin_explorer_test-stealth-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-stealth-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-stealth-initiate.o
  CXX      test/commands/test_libbitcoin_explorer_test-stealth-newkey.o
  CXX      test/commands/test_libbitcoin_explorer_test-stealth-public.o
  CXX      test/commands/test_libbitcoin_explorer_test-stealth-secret.o
  CXX      test/commands/test_libbitcoin_explorer_test-stealth-shared.o
  CXX      test/commands/test_libbitcoin_explorer_test-tx-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-tx-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-tx-sign.o
  CXX      test/commands/test_libbitcoin_explorer_test-uri-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-uri-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-validate-tx.o
  CXX      test/commands/test_libbitcoin_explorer_test-wallet.o
  CXX      test/commands/test_libbitcoin_explorer_test-watch-address.o
  CXX      test/commands/test_libbitcoin_explorer_test-watch-tx.o
  CXX      test/commands/test_libbitcoin_explorer_test-wif-to-ec.o
  CXX      test/commands/test_libbitcoin_explorer_test-wif-to-public.o
  CXX      test/commands/test_libbitcoin_explorer_test-wrap-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-wrap-encode.o
  CXX      test/primitives/test_libbitcoin_explorer_test-address.o
  CXX      test/primitives/test_libbitcoin_explorer_test-base58.o
  CXX      test/test_libbitcoin_explorer_test-generated__broadcast.o
  CXX      test/test_libbitcoin_explorer_test-generated__find.o
  CXX      test/test_libbitcoin_explorer_test-generated__formerly.o
  CXX      test/test_libbitcoin_explorer_test-generated__symbol.o
  CXX      test/test_libbitcoin_explorer_test-main.o
  CXXLD    test/libbitcoin_explorer_test
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
FAIL: libbitcoin_explorer_test_runner.sh
\============================================================================
Testsuite summary for libbitcoin-explorer 2.1.1
\============================================================================
\# TOTAL: 1
\# PASS:  0
\# SKIP:  0
\# XFAIL: 0
\# FAIL:  1
\# XPASS: 0
\# ERROR: 0
\============================================================================
See ./test-suite.log
Please report to eric@voskuil.org
\============================================================================
make[2]: *** [test-suite.log] Error 1
make[1]: *** [check-TESTS] Error 2
make: *** [check-am] Error 2
\<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
cat test-suite.log
\------------------------------
\=================================================
   libbitcoin-explorer 2.1.1: ./test-suite.log
\=================================================

\# TOTAL: 1
\# PASS:  0
\# SKIP:  0
\# XFAIL: 0
\# FAIL:  1
\# XPASS: 0
\# ERROR: 0

**Comment by skaht** [comment]
The results for applying the failed build are given below:

`echo "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" | bx mnemonic-to-seed -p 00000000000000000000000000000000`
`libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Unicode normalization test failed, a dependency may be missing.`

**Comment by evoskuil** [comment]
This is a test for a missing dependency that cannot reasonably be verified at build time. Boost ignores the missing dependency and at runtime fails to perform the normalization as specified. It means that the build of ICU that is being linked does not contain the necessary features for normalization.

**Comment by evoskuil** [comment]
You appear to be reusing an existing boost build that was not built with a reference to the ICU build. Boost needs to see ICU when it builds. Recommend building both with install.sh.

**Comment by skaht** [comment]
You are correct about the problem at my end concerning how boost was being built.  The reason for building boost on my own was when I build the libbitcoin preferred way

`./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test --build-dir=/Users/XXX/Projects/BX/bitcoin-explorer/build --build-icu --with-icu --build-boost`

The following are pertinent results:
boost_1_54_0.tar.bz2                               100%[=================================================================================================================>]  55.19M   143KB/s   in 9m 2s  s

2015-07-05 14:43:13 (104 KB/s) - 'boost_1_54_0.tar.bz2' saved [57873778/57873778]

hack: ICU detection modified, will always indicate found.
bootstrap: --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test --with-icu=/Users/XXX/Projects/BX/bitcoin-explorer/test
b2: install --reconfigure -j 8 --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test link=static,shared toolset=clang cxxflags=-stdlib=libc++ linkflags=-stdlib=libc++ threading=multi variant=release -d0 -q -sICU_PATH=/Users/XXX/Projects/BX/bitcoin-explorer/test -sICU_LINK=-L/Users/XXX/Projects/BX/bitcoin-explorer/test/lib -licui18n -licuuc -licudata  -ldl boost.locale.iconv=off boost.locale.posix=off --with-chrono --with-date_time --with-filesystem --with-locale --with-program_options --with-regex --with-system --with-thread --with-test

-n Building Boost.Build engine with toolset darwin... 
tools/build/v2/engine/bin.macosxx86_64/b2
-n Detecting Python version... 
2.7
-n Detecting Python root... 
/System/Library/Frameworks/Python.framework/Versions/2.7
-n Unicode/ICU support for Boost.Regex?... 
/Users/XXX/Projects/BX/bitcoin-explorer/test
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2
    
To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - Boost.Build documentation:
     http://www.boost.org/boost-build2/doc/html/index.html

Performing configuration checks

    - icu                      : yes
    - has_icu builds           : yes

Component configuration:

    - atomic                   : not building
    - chrono                   : building
    - context                  : not building
    - coroutine                : not building
    - date_time                : building
    - exception                : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - iostreams                : not building
    - locale                   : building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - program_options          : building
    - python                   : not building
    - random                   : not building
    - regex                    : building
    - serialization            : not building
    - signals                  : not building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : not building
    - wave                     : not building

Undefined symbols for architecture x86_64:
  "_UCNV_FROM_U_CALLBACK_SKIP_55", referenced from:
      boost::locale::impl_icu::icu_std_converter<char, 1>::uconv::uconv(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, boost::locale::impl_icu::cpcvt_type) in codepage.o
      boost::locale::impl_icu::icu_std_converter<char, 1>::uconv::uconv(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, boost::locale::impl_icu::cpcvt_type) in boundary.o

**Comment by skaht** [comment]
With a custom boost build, I can get over the "Undefined symbols for architecture x86_64" error. However, I'm not yet able to mimic the summary above, but I'm converging.

x tools/wave/trace_macro_expansion.hpp
~/Projects/BX/boost/boost_1.54.0 ~/Projects/BX/boost 
-n Building Boost.Build engine with toolset clang... 
tools/build/v2/engine/bin.macosxx86_64/b2
-n Unicode/ICU support for Boost.Regex?... 
not found.
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2
    
To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - Boost.Build documentation:
     http://www.boost.org/boost-build2/doc/html/index.html

Performing configuration checks

    - iconv (libc)             : no
    - iconv (separate)         : yes
    - icu                      : no
    - icu (lib64)              : no
    - has_icu builds           : no

Component configuration:

    - atomic                   : not building
    - chrono                   : building
    - context                  : not building
    - coroutine                : not building
    - date_time                : building
    - exception                : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - iostreams                : not building
    - locale                   : building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - program_options          : building
    - python                   : not building
    - random                   : not building
    - regex                    : building
    - serialization            : not building
    - signals                  : not building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : not building
    - wave                     : not building

~/Projects/BX/boost 


Finished building & installing: boost_1.54.0

The main elements of the custom boost build in a /bin/tcsh shell are provided below:

% curl -vL http://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.bz2/download -o boost_1_54_0.tar.bz2

% mkdir boost_1.54.0
% tar xvjf boost_1_54_0.tar.bz2 -C boost_1.54.0 --strip-components 1

% cd boost_1.54.0

% setenv CC  "/usr/bin/clang   -mmacosx-version-min=10.10"
% setenv CXX "/usr/bin/clang++ -mmacosx-version-min=10.10"

% ./bootstrap.sh \
--prefix=/Users/XXX/Projects/BX/boost/1.54.0 \
--with-toolset=clang \
--with-icu \
--with-libraries=chrono,date_time,filesystem,locale,program_options,regex,system,test,thread

% ./b2 \
-j $processors_available \
install \
--prefix=/Users/XXX/Projects/BX/boost/1.54.0 \
variant=release \
architecture=x86 \
address-model=64 \
cxxflags=-stdlib=libc++ \
linkflags=-stdlib=libc++ \
link=static,shared \
threading=multi \
-d0 \
-q

**Comment by evoskuil** [comment]
The undefined symbol error above implies that boost 1.55 headers are being referenced while linking a boost 1.54 build.

**Comment by evoskuil** [comment]
Your last post shows a custom build. This isn't recommended because of a boost build bug I had to work around in our installer. See the "hack: ..." entry in your preceding post.

**Comment by skaht** [comment]
Roger the point that the custom build is not recommended...  

The "preferred build technique" doesn't work when boost is compiled with the icu dependency, by having the --with-icu flag set.  I'm clueless as to why boost 1.55 is being used when the preferred build technique was applied. 

`./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test --build-dir=/Users/XXX/Projects/BX/bitcoin-explorer/build --build-icu --with-icu --build-boost`

I don't think any of the environmental variables will interfere with the build, with HOME=/Users/XXX.
setenv BX_CONFIG         $HOME/Projects/BX/bitcoin-explorer/bx-mainnet.cfg
setenv BS_CONFIG         $HOME/Projects/BX/bitcoin-server/bs-testnet.cfg
setenv DYLD_LIBRARY_PATH $HOME/Projects/BX/bitcoin-explorer/test/lib:$HOME/Projects/BX/boost/1.54.0/lib

Unless you have some insight when I call the latest bx install.sh, I'll continue looking at the custom build. Still working on the the custom build to learn more and get boost to successfully use icu. Currently examining:

1) http://www.boost.org/doc/libs/1_54_0/libs/regex/doc/html/boost_regex/install.html
2) http://www.boost.org/doc/libs/1_54_0/libs/config/doc/html/index.html
3) b2 --help
4) bootstrap.sh --help

Recently added the following to the custom bootstrap.sh arguments to improve the custom build results

--with-icu=/Users/XXX/Projects/BX/bitcoin-explorer/test \

This flipped the flags for:

 `"has_icu builds           : yes"`

Trying to understand how to get -licui18n -licuuc -licudata -ldl to work.  Probably related to the infamous hack, "hack: ICU detection modified, will always indicate found."

``"- icu                      : yes``

**Comment by evoskuil** [comment]
I strongly recommend building static only when building boost and/or ICU.

**Comment by skaht** [comment]
Will give that a try...

**Comment by skaht** [comment]
The static compilation failed at the last step.

  CXX      test/commands/test_libbitcoin_explorer_test-wif-to-public.o
  CXX      test/commands/test_libbitcoin_explorer_test-wrap-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-wrap-encode.o
  CXXLD    test/libbitcoin_explorer_test
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: __ZNK10libbitcoin8explorer7command29get_mainnet_cert_file_settingEv, __ZN7network20fetch_height__invoke35fetch_height__invoke__mainnet__okay11test_methodEv , __ZZN5boost9unit_test9ut_detail16auto_tc_exp_failIN7offline14hd_new__invoke53hd_new__invoke__64_bit_seed_mainnet__failure_error_idEE8instanceEvE8inst_ptr , __ZZN5boost9unit_test9ut_detail16auto_tc_exp_failIN7network22fetch_tx_index__invoke70fetch_tx_index__invoke__mainnet_satoshis_words_tx_info__okay_output_idEE8instanceEvE8inst_ptr , __ZZN5boost9unit_test9ut_detail16auto_tc_exp_failIN7network21fetch_stealth__invoke47fetch_stealth__invoke_mainnet_height_0__okay_idEE8instanceEvE8inst_ptr ........

**Comment by evoskuil** [comment]
The above described configuration succeeds in Travis: https://travis-ci.org/libbitcoin/libbitcoin-explorer/jobs/65945163

```
./install.sh --with-icu --build-icu --build-boost --enable-testnet --disable-shared --prefix=$TRAVIS_BUILD_DIR/my-prefix
```

**Comment by skaht** [comment]
Got something to work for static library compilation. Made a minor hack to the install.sh script to bx.  Need to perform a few more regression builds manually.  Will share the modified install.sh script in a digitally signed email for you to diff.

**Comment by skaht** [comment]
Performed a fresh "git clone" today. 

The following mainnet build involving only static linking worked:

`./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test --build-dir=/Users/XXX/Projects/BX/bitcoin-explorer/build --build-icu --with-icu --build-boost --disable-shared`

While the following mainnet build involving dynamic linking failed:

`./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test --build-dir=/Users/XXX/Projects/BX/bitcoin-explorer/build --build-icu --with-icu --build-boost`

**Comment by evoskuil** [comment]
This is as I would expect if you have an older version of ICU installed, which I would also expect.

**Comment by skaht** [comment]
The in-tree build also fails.

**Comment by evoskuil** [comment]
I'm not sure I understand what is meant by in-tree.

**Comment by skaht** [comment]
I believe the following is a in-tree build

`./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-explorer/test  --build-icu --with-icu --build-boost`

In-tree build mixes original source code with object files.  The ability to support out-of-tree builds is an indicator for the maturity of code. Out-of-tree builds provides better support for cross compiling executables for different computing platforms.

**Comment by evoskuil** [comment]
I still don't follow. The Visual studio outputs are differentiated in directories by target, so by this definition they are not "in-tree", but in the Automake builds the use of the install.sh `--build-dir` simply changes the root directory of the source tree, not the relative locations of the object files. Object files are output to the location of the makefile: http://stackoverflow.com/questions/1015700/autotools-library-and-object-file-output-control

**Comment by skaht** [comment]
UNIX out-of-tree builds occur when configure commands are issued outside of the directories containing the source code.  The Makefile, created by the out-of-tree configure, is then in turn is used to create object files that are outside of the original source code tree. This capability facilitates the development and separation of executables for different machine architectures on the same build platform.  See https://gcc.gnu.org/onlinedocs/gccint/Configure-Terms.html.

Its been a while, but I believe IDEs such as Visual Studio and Xcode will natively perform out-of-tree builds.  I have a huge leaning curve for Xcode to overcome. Hence, I'm using the old fashion command line interface and old UNIX Makefile practices to build custom code. 

Never really got into all the nuances with using Autotools (https://www.gnu.org/software/automake/manual/html_node/Autotools-Introduction.html) that creates the platform neutral configure scripts an Makefiles. However, I've figured out an approach for how to romance typical configure scripts associated with many open source packages and to build simplistic single platform Makefiles as needed.

**Comment by skaht** [comment]
You are correct. I conflated the `--build-dir` with out-of-tree builds that I explicitly do at my end for custom builds that I create on my own. 

Libbitcoin's strength is the number of out-of-tree builds it supports out of the box with its native configure scripts.

**Comment by evoskuil** [comment]
OK. I would not expect the location of the intermediate outputs to have any affect on the linking issue discussed earlier. I would also not expect there to be any problem running configure from various directories.

**Comment by skaht** [comment]
Satisfied with the static build approach that includes icu behaviors for the Mac. However, contrast the following manual test vector results to those found at https://github.com/trezor/python-mnemonic/blob/master/vectors.json.

`% echo "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" | bx mnemonic-to-seed -p "00000000000000000000000000000000"`
e86ef4f5d223a358d295d8bdbbefc314bec53ae7d912b2f8d48eeea50dd9c5f317254a30aaa36c6ba34ecf96634b830503a8e41136632d412bc69081587f6343

`echo "legal winner thank year wave sausage worth useful legal winner thank yellow" | bx mnemonic-to-seed -p 7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f`
2985ecde1bab580131bc0b97a150ff3a25d5b18c56436da7579ee1994239cb544676f0400726d5fe41c0683c7362f93ee1b8766631d36dfe7cdb0dcc5ac040ed

Am I using mnemonic-to-seed properly?

**Comment by thecodefactory** [comment]
All of the test vectors have a passphrase.  I believe it's TREZOR (case sensitive).

**Comment by skaht** [comment]
Sorry about wasting time.  Per thecodefactory's comment, the password is TREZOR according to https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki. This issue is closed.
