### ISSUE TITLE
Build fails on Mac OS X

### ISSUE THREAD

**Issue by sobolevn** [libbitcoin/libbitcoin-explorer#274]
I have followed instractions from the README file to install `libbitcoin-explorer`.

The `.install.sh` command fails with this message:

    Cloning into 'libsodium'...
    remote: Counting objects: 12050, done.
    remote: Compressing objects: 100% (18/18), done.
    remote: Total 12050 (delta 0), reused 18 (delta 0), pack-reused 12032
    Receiving objects: 100% (12050/12050), 3.43 MiB | 623.00 KiB/s, done.
    Resolving deltas: 100% (6333/6333), done.
    Checking connectivity... done.
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force -I m4
    autoreconf: configure.ac: tracing
    autoreconf: configure.ac: creating directory build-aux
    autoreconf: configure.ac: not using Libtool
    autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force configure.ac:440: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.
    autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1

I have tried to run `.install.sh` with custom parametrs from your `.travis.yml`. Nothing worked.

I have installed all the `brew` packages:

    MacBook-Nikita:bitcoins sobolev$ brew install autoconf automake libtool pkgconfig wget
    Warning: autoconf-2.69 already installed
    Warning: automake-1.15 already installed
    Warning: libtool-2.4.6 already installed
    Warning: pkg-config-0.28 already installed
    Warning: wget-1.16.3 already installed 

    MacBook-Nikita:bitcoins sobolev$ brew install boost
    Warning: boost-1.58.0 already installed

I am running OS X 10.9.5 with `clang`:

    MacBook-Nikita:bitcoins sobolev$ clang++ --version
    Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
    Target: x86_64-apple-darwin13.4.0
    Thread model: posix

Any ideas what to do next?

**Comment by evoskuil** [comment]
This is a problem:
```
autoreconf: configure.ac: not using Libtool
```
This may help: https://lists.gnu.org/archive/html/bug-autoconf/2010-03/msg00013.html

**Comment by sobolevn** [comment]
Yes, the problem was in the files, which were left from the binary non-brew installation.

I have done the following to resolve the issue:

    brew uninstall autoconf automake libtool pkgconfig wget
    brew doctor 

It showed me all the information about the wrong files. I have manually removed all of them, then started from scratch. Now it works.

**Comment by evoskuil** [comment]
Cool, thanks for the feedback.
