### ISSUE TITLE
Dynamic link error after successful installation

### ISSUE THREAD

**Issue by ShaunHoyes** [libbitcoin/libbitcoin-explorer#275]
I was using the Bitcoin Explorer for simple actions like checking balances and transaction history. Everything was find up until now: whenever I try to access the 'bx' function, I get the following:

dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /usr/local/bin/bx
  Reason: image not found

I tried reinstalling everything based on the user instructions, but nothing changes. Not sure if this is the proper place to seek help on this.

**Comment by ShaunHoyes** [comment]
Could the roll-out of Bitcoin XT at all be affecting libbitcoin Bitcoin Explorer?

**Comment by evoskuil** [comment]
Hi @ShaunHoyes - Bitcoin XT is broken, but it can't break BX linkage (unless maybe you install it on your build machine).

BX hasn't had a direct dependency on GMP since about a year ago (as SX). You might try getting a report from `ldd` to see exactly what it's dynamically linking that's bringing in GMP.

In any case you might try building statically, which will eliminate anything that might be bringing in GMP. When doing this I strongly recommend building boost and using a prefix directory: 

```
$ ./install.sh CXXFLAGS=-Os --disable-shared --build-boost --prefix=/home/me/myprefix
```

**Comment by ShaunHoyes** [comment]
Hi @evoskuil - thanks for the response. In order to build "statically", I would have to use the prefix directory you just provided? I tried that, but I still get the same message. Is there a way to delete everything and just start from scratch by downloading BX again from github?

**Comment by evoskuil** [comment]
Hi @ShaunHoyes - You can use any directory you have access to. It's not a requirement for building, but it does help isolate the build from external linkage. Removing a prior installation is not required. I often build different versions to different prefix directories. You can also specify a `--build-dir` to isolate sources for side-by-side builds, although this doesn't affect linkage issues.

**Comment by evoskuil** [comment]
Hi @ShaunHoyes, any update on this?

**Comment by ShaunHoyes** [comment]
Sorry, but I am having difficulty understanding this. I still get the same message. Could you tell me the exact inputs I should use?

**Comment by ShaunHoyes** [comment]
When I try the following, I get a bunch of "Permission denied" messages:

$ ./install.sh CXXFLAGS=-Os --disable-shared --build-boost --prefix=/home/me/myprefix

**Comment by evoskuil** [comment]
You need to replace "me" with your user account name. `/home/me/myprefix` is an example path.
