### ISSUE TITLE
validation of inputs failed despite that the endorsement is valid. testnet.

### ISSUE THREAD

**Issue by Abdullah114** [libbitcoin/libbitcoin-explorer#282]
Although the endorsement has been validated I receive input failed error for transaction validation on the testnet. Any ideas why? 
Below is the output of my bash. 
Thanks a lot.

creating endorsement script:
>> root@t410:/home/n# bx input-set "[ 304402206680b20d021a225bf0da0a6267e7ea27538cdcfa9de00070dc978a1f9563509902202261736efe6635f08b1401c39fb020f751e194829b1c2ec456cc77f002c7861c01 ] [ 033e64a441a40e58b9b0d031909a99cb94e87c96abe008a024c01e04d9f059913b ]" 0100000001eb31dc84d1f96794b29a87c08e636f3126c214e1e63e2f8eaf724fef415af3e5000000006a47304402206680b20d021a225bf0da0a6267e7ea27538cdcfa9de00070dc978a1f9563509902202261736efe6635f08b1401c39fb020f751e194829b1c2ec456cc77f002c7861c0121033e64a441a40e58b9b0d031909a99cb94e87c96abe008a024c01e04d9f059913bffffffff01404b4c00000000001976a9142a8a065d2cc6537c3bfd8937cae339a45d53edfb88ac00000000

received:
>> 0100000001eb31dc84d1f96794b29a87c08e636f3126c214e1e63e2f8eaf724fef415af3e5000000006a47304402206680b20d021a225bf0da0a6267e7ea27538cdcfa9de00070dc978a1f9563509902202261736efe6635f08b1401c39fb020f751e194829b1c2ec456cc77f002c7861c0121033e64a441a40e58b9b0d031909a99cb94e87c96abe008a024c01e04d9f059913bffffffff01404b4c00000000001976a9142a8a065d2cc6537c3bfd8937cae339a45d53edfb88ac00000000

decoded:
>> root@t410:/home/n# bx tx-decode 0100000001eb31dc84d1f96794b29a87c08e636f3126c214e1e63e2f8eaf724fef415af3e5000000006a47304402206680b20d021a225bf0da0a6267e7ea27538cdcfa9de00070dc978a1f9563509902202261736efe6635f08b1401c39fb020f751e194829b1c2ec456cc77f002c7861c0121033e64a441a40e58b9b0d031909a99cb94e87c96abe008a024c01e04d9f059913bffffffff01404b4c00000000001976a9142a8a065d2cc6537c3bfd8937cae339a45d53edfb88ac00000000
transaction
{
    hash f1d44cfc6b1b9e1dd78705d2d7adb8fdff78652d933c4f713dfb9ff4e1f5b94c
    inputs
    {
        input
        {
            address msYXCFA5jkTcdFZn3miLuNFMQo9dxj8P7E
            previous_output
            {
                hash e5f35a41ef4f72af8e2f3ee6e114c226316f638ec0879ab29467f9d184dc31eb
                index 0
            }
            script "[ 304402206680b20d021a225bf0da0a6267e7ea27538cdcfa9de00070dc978a1f9563509902202261736efe6635f08b1401c39fb020f751e194829b1c2ec456cc77f002c7861c01 ] [ 033e64a441a40e58b9b0d031909a99cb94e87c96abe008a024c01e04d9f059913b ]"
            sequence 4294967295
        }
    }
    lock_time 0
    outputs
    {
        output
        {
            address mjPt2FEcxyoZD5CQtvsfNbVAHuwPvA7K9N
            script "dup hash160 [ 2a8a065d2cc6537c3bfd8937cae339a45d53edfb ] equalverify checksig"
            value 5000000
        }
    }
    version 1
}

validating the endorsement:
>> root@t410:/home/n# bx input-validate 033e64a441a40e58b9b0d031909a99cb94e87c96abe008a024c01e04d9f059913b "dup hash160 [ 2a8a065d2cc6537c3bfd8937cae339a45d53edfb ] equalverify checksig" 304402206680b20d021a225bf0da0a6267e7ea27538cdcfa9de00070dc978a1f9563509902202261736efe6635f08b1401c39fb020f751e194829b1c2ec456cc77f002c7861c01 0100000001eb31dc84d1f96794b29a87c08e636f3126c214e1e63e2f8eaf724fef415af3e5000000006a47304402206680b20d021a225bf0da0a6267e7ea27538cdcfa9de00070dc978a1f9563509902202261736efe6635f08b1401c39fb020f751e194829b1c2ec456cc77f002c7861c0121033e64a441a40e58b9b0d031909a99cb94e87c96abe008a024c01e04d9f059913bffffffff01404b4c00000000001976a9142a8a065d2cc6537c3bfd8937cae339a45d53edfb88ac00000000

received:
>> The endorsement is valid.

trying to validate the transaction:
>> root@t410:/home/n# bx validate-tx 0100000001eb31dc84d1f96794b29a87c08e636f3126c214e1e63e2f8eaf724fef415af3e5000000006a47304402206680b20d021a225bf0da0a6267e7ea27538cdcfa9de00070dc978a1f9563509902202261736efe6635f08b1401c39fb020f751e194829b1c2ec456cc77f002c7861c0121033e64a441a40e58b9b0d031909a99cb94e87c96abe008a024c01e04d9f059913bffffffff01404b4c00000000001976a9142a8a065d2cc6537c3bfd8937cae339a45d53edfb88ac00000000

received:
>> validation of inputs failed

**Comment by evoskuil** [comment]
Did you compile the full stack for testnet?

**Comment by Abdullah114** [comment]
yes I did.

FYI: I am sure I am doing something wrong, because several hours ago I tried doing it with other addresses and inputs, and it used to validate tx. Later I tried various cases and inputs and receiving the same error.

**Comment by evoskuil** [comment]
Are you running against the default (Airbitz) testnet server?

**Comment by Abdullah114** [comment]
I didn't change any settings, it's default, so I suppose its the server you mentioned.

**Comment by Abdullah114** [comment]
I just thought if I could get a hint where it could get wrong. :P

**Comment by evoskuil** [comment]
It looks like you are signing the wrong [prevout script](https://www.biteasy.com/testnet/transactions/e5f35a41ef4f72af8e2f3ee6e114c226316f638ec0879ab29467f9d184dc31eb).
```
DUP HASH160 [83ed63869c1359f5b622668af4e76444c80adb25] EQUALVERIFY CHECKSIG
```

But your `input-verify` shows:
```
dup hash160 [ 2a8a065d2cc6537c3bfd8937cae339a45d53edfb ] equalverify checksig
```

**Comment by Abdullah114** [comment]
Thank you so much evoskuil!
That is exactly what was wrong. I repeated with new inputs and it spent easily.

Can you please give me a hint on how and where should I introduce an address for the change?
I suppose somewhere where I encode transaction:
>> bx tx-encode -i e5f35a41ef4f72af8e2f3ee6e114c226316f638ec0879ab29467f9d184dc31eb:0 -o mjPt2FEcxyoZD5CQtvsfNbVAHuwPvA7K9N:1500000

tx:
>> 0100000001eb31dc84d1f96794b29a87c08e636f3126c214e1e63e2f8eaf724fef415af3e50000000000ffffffff0160e31600000000001976a9142a8a065d2cc6537c3bfd8937cae339a45d53edfb88ac00000000

Can you please give me an example?
Again many thanks for your help.
BX is truly awesome.

**Comment by evoskuil** [comment]
@Abdullah114 Just create a second output and add it to the transaction. The change output script is no different than that for your existing output. Just use a different public key hash.
