### ISSUE TITLE
Handling incoming payments

### ISSUE THREAD

**Issue by eriksank** [libbitcoin/libbitcoin-explorer#287]
I've been looking at the possibility to use the bx commandline tool to process incoming bitcoin payment notifications.

At the moment, I just use bitcoind for that. In bitcoin.conf, it is possible to appoint a script that bitcoind will execute on walletnotify (first argument being the transaction hash) and one on blocknotify (first argument being the blockhash). It is not a perfect solution but it certainly works.

I would certainly appreciate it if I could use something similar with bx:

$ nohup bx p2p-walletnotify mywalletnotifhandler.sh &
$ nohup bx p2p-blocknotify myblocknotifhandler.sh &

Another problem is that I don't see how to retrieve a block by their hash? I need this ability in order to check what transactions to inspect, to see if one of my addresses has received some payment. I could really use something like this:

$ bx getblock [hash]

The problem is of course, who will be storing that data? At the moment, I just have a copy of bitcoind running that stores all the information. It would obviously be useful, if the libbitcoin network could spare its users from each having to do that by themselves.

I think that bx is a very useful addition to my toolbox, but there are quite a few things that it cannot do. At the moment, it leaves out so much required functionality that it is certainly not a replacement for the bitcoin-cli and bitcoind tools.

**Comment by evoskuil** [comment]
Hi @eriksank,

You can fetch transactions by hash using [bx fetch-tx](https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-fetch-tx).

You can fetch block headers by hash using [bx fetch-header](https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-fetch-header). There is no command to fetch a full block, as this is not exposed by `libbitcoin-server`. But if you are pulling blocks to check balances then you should use [bx fetch-balance](https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-fetch-balance) and/or [bx fetch-history](https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-fetch-history). To monitor for payments to an address you can use [bx watch-address](https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-watch-address).

If you don't want to trust a server, then you can host one yourself. This is as strong as you can get in terms of validation, even when using the above commands. There is no reason to pick through blocks, the server does that for you. You can even communicate securely to your hosted server using [CurveZMQ](http://curvezmq.org/page:read-the-docs), see [Using Certificates](https://github.com/libbitcoin/libbitcoin-explorer/wiki/How-to-Use-Certificates).

Full command help with detailed examples and [diagrams](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Wallet-Commands) is [on the wiki](https://github.com/libbitcoin/libbitcoin-explorer/wiki).

I don't follow your question on storing information. A `libbitcoin-server` instance stores and indexes the full chain off of the P2P network. That can be kept locally or remotely.

If there is still something that BX can't do for you please let us know!

**Comment by eriksank** [comment]
@evoskuil Thanks for your reply!
You see, I really like some of the functionality of the bx tool. It is really useful. I just don't believe I can use it for monitoring incoming payments. bx watch-address watches one address. I need to watch potentially hundreds of addresses. Does that mean that I need to start "bx watch-address" hundreds of times? Concerning monitoring incoming payments, I cannot translate an approach based on bitcoind to an approach based on bx. With bitcoind, I have no trouble doing it. With bx, I do not see how to do it.

Concerning picking through the blocks, that is what bitcoind requires. This is obviously not a goal in itself. I am certainly not married to the concept of picking through the blocks. But then again, in that case I will need an alternative that also works. In my impression "bx watch-address" may not cut it. I do not see how to use it as a replacement for bitcoind's walletnotify and blocknotify.

Concerning storing information, I like the idea that libbitcoin-server instances stores the information. It would spare me from doing that too. I don't think there is a trust issue. An attacker would need to know what exactly to forge. Therefore, I don't see security issues in offering a network service that stores this data for others.

I would just need a way to process incoming payments that is equivalent to what I am doing with bitcoind now. It would be helpful if bx could run my script every time a block comes in. I also need the block notifications to count the confirmations of an older payment that came in. I actually like the way bitcoind does the payment notifications. I had just hoped that the bx tool could do something similar.

**Comment by evoskuil** [comment]
BX is not intended to be a stateful wallet. `libbitcoin-server` is designed for that sort of thing. It provides for subscription to transaction and block announcements, but it's not a scripting tool.

WRT security, there are **significant** risks to trusting any Bitcoin server/service (i.e. not validating yourself).

**Comment by eriksank** [comment]
Can libbitcoin-server execute a program on walletnotify or on blocknotify like bitcoind does? Does libbitcoin-server need to store the entire blockchain (I want to avoid this).

Concerning the risk of trusting a bitcoin server/service, at the moment, I don't. I just use bitcoind. I also use electrum to send off payment transactions. There may be a risk in trusting the electrum network for its data, but I am not sure how exactly an attacker could abuse it.

**Comment by evoskuil** [comment]
Yes and no... `libbitcoin-server` has registrations for block and transaction announcements. However it doesn't "execute a program", it's a library.

Bitcoin Server/BS is the `libbitcoin-server` command line application. This is an analog to Bitcoin Explorer/BX, which is the command line tool build on the `libbitcoin-explorer` library. The applications are a thin layer over the libraries. Adding functionality to them is straightforward.

An attacker can abuse it by controlling the network and/or any number of server instances. For example, recent router attacks show that an attacker can simply redirect your traffic to any number of Bitcoin servers to his own server. You would never know. If you think you are receiving payment, you may not be at all. In order to be sure you need to validate on a trusted platform (i.e. one you control).

**Comment by eriksank** [comment]
In fact, it is true. Thinking of it, the corresponding tool for `bitcoind` would be `bs`. There is one major problem with `bs`, however. Its [documentation](https://github.com/libbitcoin/libbitcoin-server/wiki) says nowhere how to use it. Since it is a server, it is probably meant to have a network API? If it exists, it is mentioned nowhere in the wiki. From the documentation, I also do not see how I would be able to register for block/transaction announcements ...

**Comment by evoskuil** [comment]
BS is not as mature as BX at this point. We're focused more on code than documentation presently.

[block announcement subscriptions are here](https://github.com/libbitcoin/libbitcoin-server/blob/master/include/bitcoin/server/server_node.hpp#L66)
```cpp
    virtual void subscribe_blocks(block_notify_callback notify_block);
```
[transaction announcement subscriptions are here](https://github.com/libbitcoin/libbitcoin-server/blob/master/include/bitcoin/server/server_node.hpp#L67)
```cpp
    virtual void subscribe_transactions(transaction_notify_callback notify_tx);
```
You derive from [server_node](https://github.com/libbitcoin/libbitcoin-server/blob/master/include/bitcoin/server/server_node.hpp#L51) which implements your own server.

To reuse the BX command line parsing, config, etc. you can replace [this line](https://github.com/libbitcoin/libbitcoin-server/blob/master/src/dispatch.cpp#L255) with your own derived server.

To handle the callbacks you implement handlers for each of the callbacks:
```cpp
    typedef std::function<void (size_t, const chain::block&)> block_notify_callback;
    typedef std::function<void (const chain::transaction&)> transaction_notify_callback;
```
Then you just handle the notifications.

**Comment by evoskuil** [comment]
It is also possible to subscribe to block and transaction notifications over the client/server API (which means no specialized server, probably better). There are four ZeroMQ based endpoints exposed by `libbitcoin-server`. From the [config](https://github.com/libbitcoin/libbitcoin-server/blob/master/data/bs.cfg#L100) file:

```ini
[server]
# The query service endpoint, defaults to 'tcp://*:9091'.
query_endpoint = tcp://*:9091
# The heartbeat service endpoint, defaults to 'tcp://*:9092'.
heartbeat_endpoint = tcp://*:9092
# The block publishing service endpoint, defaults to 'tcp://*:9093'.
block_publish_endpoint = tcp://*:9093
# The transaction publishing service endpoint, defaults to 'tcp://*:9094'.
transaction_publish_endpoint = tcp://*:9094
```

The query endpoint is used by BX. There is no client stub for the others, but [libbitcoin-client]() is a small library that provides the stubs that BX uses for the query endpoint. A good starting point would be the [method](https://github.com/libbitcoin/libbitcoin-client/blob/master/src/obelisk/obelisk_codec.cpp#L200) that BX uses to implement `bx watch-address`.

**Comment by evoskuil** [comment]
There are people around who can probably be more helpful in the particular area than myself (since they use it in production), here on IRC and the mailing list.

**Comment by eriksank** [comment]
Is there a list of public APIs for `libbitcoin-server`? I could try to use [swig](http://www.swig.org) to generate scripting language bindings for them.

But then again, I have had bad encounters in the past with using swig and C++.

Unless there are complicated variadic macros involved -- openSSL comes to mind -- swig can always handle C header files. Concerning C++, I have never seen a case in which swig was able to parse C++ header files correctly, though. It always required ugly hacks, and even then, it often did not end up working. I sometimes wonder how gcc manages to parse those C++ header files?

Are you actually interested in providing scripting language bindings to `libbitcoin-server`? I avoid writing C++ code like the plague (I am seriously not good at it anyway), and if I really have to go native, I'd rather suffer in C. So, swig or similar bindings would be a solution ...

**Comment by evoskuil** [comment]
We are planning to provide SWIG bindings for all of our libraries at some point. We currently provide them for `libbitcoin-consensus` only. We use `libbitcoin-build` to generate most project artifacts, including the binding metadata. We have one task to complete that will allow us to generate this for all repos. But we are holding off on this until someone comes along and validates the consensus bindings.

**Comment by eriksank** [comment]
Validating the `libbitcoin-consensus` bindings requires heavily-documented examplets -- minimal scenarios --- in C++ that also have good unit test potential. They should preferably "assert" for things while running. From there on, it is a question of translating each examplet to each particular scripting engine for which bindings would be made available.

I can read C++ but not always. I could pick a few items and do their transations for nodejs, php, and with more difficulty, lua. Besides that I could help with finding and recruiting other victims who could also pick a set of examplets to work on. In fact, it would be a good QA exercise for the C++ code too. You'd never know what kind of issues emerge from testing the bindings.

I am quite convinced, however, that the starting point does not yet exist, that is, the documented scenarios in C++. Everybody seems to be hating to work on the documentation. So, nothing new there ;-)

**Comment by evoskuil** [comment]
There is a very small number of test cases in consensus and they should be self-explanatory. The important ones are as follows:

```cpp
BOOST_AUTO_TEST_CASE(consensus__script_verify__null_tx__throws_invalid_argument)
{
    data_chunk prevout_script_data;
    BOOST_REQUIRE(decode_base16(prevout_script_data, CONSENSUS_SCRIPT_VERIFY_PREVOUT_SCRIPT));
    BOOST_REQUIRE_THROW(verify_script(NULL, 1, &prevout_script_data[0], prevout_script_data.size(), 0, 0), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(consensus__script_verify__null_prevout_script__throws_invalid_argument)
{
    data_chunk tx_data;
    BOOST_REQUIRE(decode_base16(tx_data, CONSENSUS_SCRIPT_VERIFY_TX));
    BOOST_REQUIRE_THROW(verify_script(&tx_data[0], tx_data.size(), NULL, 1, 0, 0), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(consensus__script_verify__invalid_tx__tx_invalid)
{
    const verify_result result = test_verify("42", "42");
    BOOST_REQUIRE_EQUAL(result, verify_result_tx_invalid);
}

BOOST_AUTO_TEST_CASE(consensus__script_verify__invalid_input__tx_input_invalid)
{
    const verify_result result = test_verify(CONSENSUS_SCRIPT_VERIFY_TX, CONSENSUS_SCRIPT_VERIFY_PREVOUT_SCRIPT, 1);
    BOOST_REQUIRE_EQUAL(result, verify_result_tx_input_invalid);
}

BOOST_AUTO_TEST_CASE(consensus__script_verify__undersized_tx__tx_invalid)
{
    const verify_result result = test_verify(CONSENSUS_SCRIPT_VERIFY_TX, CONSENSUS_SCRIPT_VERIFY_PREVOUT_SCRIPT, 0, verify_flags_p2sh, -1);
    BOOST_REQUIRE_EQUAL(result, verify_result_tx_invalid);
}

BOOST_AUTO_TEST_CASE(consensus__script_verify__oversized_tx__tx_size_invalid)
{
    const verify_result result = test_verify(CONSENSUS_SCRIPT_VERIFY_TX, CONSENSUS_SCRIPT_VERIFY_PREVOUT_SCRIPT, 0, verify_flags_p2sh, +1);
    BOOST_REQUIRE_EQUAL(result, verify_result_tx_size_invalid);
}

BOOST_AUTO_TEST_CASE(consensus__script_verify__incorrect_pubkey_hash__equalverify)
{
    const verify_result result = test_verify(CONSENSUS_SCRIPT_VERIFY_TX, "76a914c564c740c6900b93afc9f1bdaef0a9d466adf6ef88ac");
    BOOST_REQUIRE_EQUAL(result, verify_result_equalverify);
}

BOOST_AUTO_TEST_CASE(consensus__script_verify__valid__true)
{
    const verify_result result = test_verify(CONSENSUS_SCRIPT_VERIFY_TX, CONSENSUS_SCRIPT_VERIFY_PREVOUT_SCRIPT);
    BOOST_REQUIRE_EQUAL(result, verify_result_eval_true);
}
```

Current SWIG bindings exist for Java and Python.

**Comment by eriksank** [comment]
The test cases do not fully reflect what `libbitcoin-consensus` does.  The important test cases are for what the user would want to use the library for. Imagine the library offers the function `startsWith(string1, string2)` to the users, and that this is what they will be using the library for, then, a test case could be:
```
BOOST_REQUIRE_EQUAL(startsWith('hello','hel'), verify_result_eval_true);
```
From the test cases in your comment, it is not really clear to me what for exactly the users will be using `libbitcoin-consensus`. They do not seem to be testing user-callable functions. What will the user trying to achieve by doing what? is really an unanswered question here ...

**Comment by evoskuil** [comment]
Well it's a Bitcoin SDK, so there is a presumption of some experience. Given the [readme](https://github.com/libbitcoin/libbitcoin-consensus/blob/master/README.md) and the terminology in the test cases, it would hopefully be evident that `libbitcoin-consensus` verifies that transaction inputs conform to consensus rules. There is also the idea that `libconsensus` (from the Satoshi Client) publishes these files for this purpose.

**Comment by eriksank** [comment]
Well, when using `bitcoind`, the consensus validation rules are just assumed, I guess. Even though block/transaction validity is a real, underlying issue, it is not the main focus when processing incoming payments -- which is all that a large group of developers are doing -- since the tool itself is meant to be dealing with that.

I would expect the unit test to start with a list of valid and a list of invalid transactions. For each invalid transaction, there should probably be a reason field: "invalid because...". The library does not seem to be handling block validity, but I suspect that this is because blocks are much easier to validate. My own experience with blocks and transactions is pretty much limited to `bitcoind`. I think `libbitcoin-consensus` is an interesting take on the matter, but I wonder if someone just dealing with incoming payments would ever separate that out of a "full" node? Maybe it is just better part of `libbitcoin`, under the hood, just like in `bitcoind`?

**Comment by evoskuil** [comment]
> Well, when using bitcoind, the consensus validation rules are just assumed, I guess.

Libbitcoin does not require you to understand consensus rules any more than `bitcoind` - unless you are writing a blockchain server. I didn't propose that you need to understand `libbitcoin-consensus` to work with `libbitcoin` as an end-user, or even as a developer. It was presented as an opportunity to validate our SWIG bindings, which are currently generated only for `libbitcoin-consensus` - mainly because it's the simplest library.

> I would expect the unit test to start with a list of valid and a list of invalid transactions. For each invalid transaction, there should probably be a reason field: "invalid because...". 

A single unit test would not list a set of transactions, it would validate one. Running multiple tests in a one unit test obfuscates the condition under test. Each unit test in consensus provides a single TX and a single PREVOUT script and a single result code expectation.

> I think libbitcoin-consensus is an interesting take on the matter, but I wonder if someone just dealing with incoming payments would ever separate that out of a "full" node?

The code in `libbitcoin-consensus` is the **exact* consensus code from `bitcoind`.

**Comment by eriksank** [comment]
Well, yeah, there are the two data sets and then there are the unit tests (source code).

For administrative purposes, each transaction tested should indeed be considered as one unit test case. This should not prevent the unit test programmer from reading the transactions from a file or a set of files and execute the test per transaction.

I think that the documented data sets could be quite interesting material for other bitcoin programmers: "This is valid. This is also (surprisingly) valid. This is invalid. This is also (surprisingly) invalid." It is the kind of interesting documentation that people end up quoting from.

I wonder does the API consist of `verify_script()` or `test_verify()`? It is not clear from the unit tests what function exactly is being tested. Is this also the function mentioned in the swig bindings? Does the swig binding mention other functions?

**Comment by evoskuil** [comment]
> It is not clear from the unit tests what function exactly is being tested

It's really not that much code. The `test_verify()` [method](https://github.com/libbitcoin/libbitcoin-consensus/blob/master/test/consensus__script_verify.cpp#L74-L84) is a test harness for `verify_script()`:

```cpp
static verify_result test_verify(const std::string& transaction,
    const std::string& prevout_script, uint32_t tx_input_index=0,
    const uint32_t flags=verify_flags_p2sh, int32_t tx_size_hack=0)
{
    data_chunk tx_data, prevout_script_data;
    BOOST_REQUIRE(decode_base16(tx_data, transaction));
    BOOST_REQUIRE(decode_base16(prevout_script_data, prevout_script));
    return verify_script(&tx_data[0], tx_data.size() + tx_size_hack, 
        &prevout_script_data[0], prevout_script_data.size(), tx_input_index,
        flags);
}
```
In other words, all of the tests just parameterize this simple harness.

The only **valid** test case in the set uses the following tx and script:
````cpp
#define CONSENSUS_SCRIPT_VERIFY_TX \
    "01000000017d01943c40b7f3d8a00a2d62fa1d560bf739a2368c180615b0a7937c0e883e7c000000006b4830450221008f66d188c664a8088893ea4ddd9689024ea5593877753ecc1e9051ed58c15168022037109f0d06e6068b7447966f751de8474641ad2b15ec37f4a9d159b02af68174012103e208f5403383c77d5832a268c9f71480f6e7bfbdfa44904becacfad66163ea31ffffffff01c8af0000000000001976a91458b7a60f11a904feef35a639b6048de8dd4d9f1c88ac00000000"
#define CONSENSUS_SCRIPT_VERIFY_PREVOUT_SCRIPT \
    "76a914c564c740c6900b93afc9f1bdaef0a9d466adf6ee88ac"
```
There is no point in a suite of test vectors for this library, since it's exact duplicate code from another library that has its own test suite.

A list of data is not sufficient for testing the corner cases, which are what's interesting here, as this is a wrapper. So this test, for example, does exactly what its title and trivial source implies... it attempts to verify a null transaction with a valid prevout script, and expects `std::invalid_argument` to be thrown. I'm not sure that a bunch of explanation is going to make this any easier for a C++ programmer.

```cpp
BOOST_AUTO_TEST_CASE(consensus__script_verify__null_tx__throws_invalid_argument)
{
    data_chunk prevout_script_data;
    BOOST_REQUIRE(decode_base16(prevout_script_data, CONSENSUS_SCRIPT_VERIFY_PREVOUT_SCRIPT));
    BOOST_REQUIRE_THROW(verify_script(NULL, 1, &prevout_script_data[0], prevout_script_data.size(), 0, 0), std::invalid_argument);
}
```

**Comment by eriksank** [comment]
I understand. So, the idea is that python and java users would be using the `verify_script()` function through the swig bindings? I wonder how that would work in java, since standalone functions don't exist there? So, swig must be suggesting something like `VerifyScriptInstanceWrapperFactory.verify_script()` ? In python, it would be less of a problem, if you don't forget to type enough whitespace in front of the function, of course ;-)

**Comment by evoskuil** [comment]
See actual [Python](https://github.com/libbitcoin/libbitcoin-consensus/blob/master/bindings/python/proxy/consensus.py#L232) and [Java](https://github.com/libbitcoin/libbitcoin-consensus/blob/master/bindings/java/proxy/org/libbitcoin/consensus/consensus.java#L11).

**Comment by eriksank** [comment]
What might be missing is some kind of documentation for the function's signature:
```
verify_result verify_script(
SWIGTYPE_p_unsigned_char transaction, //that's probably equivalent with String
long transaction_size,
SWIGTYPE_p_unsigned_char prevout_script, //this too
long prevout_script_size,
long tx_input_index,
long flags) 
```
It looks so imported-from-C to ask the user to fill out the length of strings. I would probably provide a verify_script function that automatically fills out the `transaction_size` and `prevout_script_size` arguments for the user from `transaction.size()` or `transaction.length()` depending on how they named the function this in this particular language.

What is a `prevout` script, actually? Is it the leg in which the address was paid to in a previous transaction? And the `tx_input_index` must then be the location in the `prevout` array, I suppose?

`verify_result.swigToEnum(consensusJNI.verify_script(SWIGTYPE_p_unsigned_char.getCPtr(transaction), transaction_size, SWIGTYPE_p_unsigned_char.getCPtr(prevout_script), prevout_script_size, tx_input_index, flags));
  }`

It is not entirely clear to me what the function will return? Is it just an enum of int that is monstruously being wrapped or so? Zero meaning ok? Or zero meaning not ok? One meaning something else? I guess this will be better clarified in the C++ header file than in what swig now tells us. However, that means that the COBOL programmer using swig bindings would still need to refer to the C++ sources. Not good. Not good. Not good ... ;-)

**Comment by evoskuil** [comment]
* `unsigned char` is  a byte array
* the function returns an enumeration, which is documented in detail in the [public headers](https://github.com/libbitcoin/libbitcoin-consensus/blob/master/include/bitcoin/consensus/export.hpp)

**Comment by evoskuil** [comment]
Closing as a SWIG binding documentation issue that we do not intend to fix in the near future.
