### ISSUE TITLE
Spending bitcoin

### ISSUE THREAD

**Issue by eriksank** [libbitcoin/libbitcoin-explorer#288]
The strategy to implement in order to spend bitcoins [How to spend Bitcoins?](https://github.com/libbitcoin/libbitcoin-explorer/wiki/How-to-Spend-Bitcoin) is technically interesting, but a bit convoluted for the user to use.

At the moment, I just use the electrum commandline tool, in order to simplify the process. It will go through the addresses controlled by a HD private key (BIP32), figure out which addresses to spend from, which vout lines in these addresses to use, and if need be, to generate a change address. This is pretty much what it does:

$ bx hd-create-tx hdprivkey paytoaddress amount

I think it would make sense to add this kind of function to the bx tool too?

**Comment by evoskuil** [comment]
Hi @eriksank,

This might make sense for BX, though it's not intended to be a (state-maintaining) wallet. It works directly off of the P2P network and/or a `libbitcoin-server`. In order to do this it would need to scan the blockchain for the next free address (or pair of addresses). It would not be hard to do, but it might not be snappy. Is that what you are after?

**Comment by eriksank** [comment]
Hi @evoskuil,

I think that your objections are definitely valid.

I just wonder how electrum commandline tool manages to do it very fast? I know that electrum scans the addresses in use (with transactions available for them) in the wallet and then a "gap" of unused indexes. From there, it knows almost immediately what the balances are on these addresses. I suspect that the electrum network stores address history and balances.

If it will be going rather slowly, I suspect it would not be a good idea. This functionality probably pre-supposes that the network servers store the information in such a way that it is speedy to figure out address transactions.

bitcoind allows you to use the "importaddress" method that will also index address transactions in such a way that it does not need to rescan the blockchain for its history or balance.

The need to have rapid access to an address and its transactions is absolutely real. That is probably why bitcoind and electrum implement this specific indexing functionality. I think it would make sense to consider something similar for bx. It is absolutely not a superfluous functionality. One way to solve the problem could be to let the bx tool connect to the electrum network to achieve this?

**Comment by evoskuil** [comment]
Speed is always relative, so we may have different ideas of fast :).

I'm not familiar with the details of the Electrum command, however there are only two options. Either it is scanning the blockchain data or it relying on local wallet information. If you can use any HD key, then it's the former. Electrum doesn't directly use the P2P network, it's server indexes spend information. The scan can seem very fast if the search distance isn't too large.

This could be optimized by providing the server your public key and chain code (which can be derived from what you are giving the command), allowing the server to identify information without multiple round trips. That may be what it does, however that would be catastrophic from a privacy standpoint, unless you are running the Electrum server yourself.

`libbitcoin-server` indexes the blockchain in such a way that *all*  retrieval is fast, not just for the addresses you give it to work on. The query engine is extremely fast, likely far exceeding any other implementation. However, we would never accept a chain code to avoid round trips.

**Comment by evoskuil** [comment]
While i do find this to be a nice usability feature, I would personally not implement it due to the significant privacy issues. Essentially it defeats the purpose of using an HD wallet in the first place. Electrum doesn't concern itself with privacy.
