### ISSUE TITLE
problem with mnemonic-to-seed

### ISSUE THREAD

**Issue by SANDHBill** [libbitcoin/libbitcoin-explorer#304]
Hello,
When I try this line
echo "legal winner thank year wave sausage worth useful legal winner thank yellow" | bx mnemonic-to-seed -p TREZOR

I get this error

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Unicode normalization test failed, a dependency may be missing.

Any idea?

**Comment by evoskuil** [comment]
This error originates from [this line in libbitcoin](https://github.com/libbitcoin/libbitcoin/blob/master/src/unicode/unicode.cpp#L108).

```cpp
// One time verifier of the localization backend manager. This is 
// necessary because boost::normalize will fail silently to perform 
// normalization if the ICU dependency is missing.
static void validate_localization()
{
    const auto ascii_space = "> <";
    const auto ideographic_space = ">　<";
    const auto normal = normal_form(ideographic_space, norm_type::norm_nfkd);
    if (normal != ascii_space)
        throw std::runtime_error(
            "Unicode normalization test failed, a dependency may be missing.");
}
```

It is an indication that `boost` was not linked with ICU during the build. Can you provide your build log?

**Comment by SANDHBill** [comment]
I saw that line in the code also, I guessed it has to do something with boost.
After many times that I failed build it with icu, finally I build it without any errors using this command line.
./install.sh --with-icu --build-icu --build-boost --enable-testnet --disable-shared --prefix=$TRAVIS_BUILD_DIR/my-prefix

Where can I get the log files?

**Comment by evoskuil** [comment]
The build log is emitted to the console.

You will probably be OK once you fix the `--prefix` directory. This needs to be a directory on your machine.

Also, I recommend pulling the `install.sh` from the release (`version2`) branch.

**Comment by SANDHBill** [comment]
I thought it is Boost build problem. what's the problem with --prefix?

**Comment by evoskuil** [comment]
Boost is failing to link ICU because it doesn't find it. If you build ICU and boost in a prefix directory and link statically it will find it.

**Comment by SANDHBill** [comment]
I will rebuild from version2 and a fix directory.

**Comment by evoskuil** [comment]
Thanks, but this is just the portion that includes the output of the test pass. There should be many pages of output.

**Comment by SANDHBill** [comment]
Here is my log
PASS: libbitcoin_explorer_test_runner.sh
============================================================================
Testsuite summary for libbitcoin-explorer 2.2.1
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

real	63m6.126s
user	51m34.995s
sys	8m43.272s


But  I have still the same problem.

**Comment by evoskuil** [comment]
Is this still an open question?

**Comment by skaht** [comment]
Given the lapse of time, and the results below for a newer master/v3.0 build, I suspect this issue is closed.

```% echo "legal winner thank year wave sausage worth useful legal winner thank yellow" | bx mnemonic-to-seed -p TREZOR```

2e8905819b8723fe2c1d161860e5ee1830318dbf49a83bd451cfb8440c28bd6fa457fe1296106559a3c80937a1c1069be3a3a5bd381ee6260e8d9739fce1f607

**Comment by SANDHBill** [comment]
Sorry for being late. I didn't have anytime to test it. I have to rebuild my machine from scratch, later I will let you know. And it isn't important to be honest.

**Comment by SANDHBill** [comment]
Many many thanks for your help.

**Comment by evoskuil** [comment]
OK, please reopen if you discover that it's still an issue.

**Comment by lyhistory** [comment]
@evoskuil two more questions:
1) I think the early version has cmd 'mnemonic-decode' which can convert the words to the original seed, example can be found here (last two commands)https://github.com/bitcoinbook/bitcoinbook/blob/second_edition_print3_rc2/appdx-bx.asciidoc
, do you mean for current version there is no way to convert the long numeric representation to the original seed

2) regarding to the last example in your wiki: https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-mnemonic-to-seed,
is there any major difference between
bx hd-new < seed.txt
and
bx mnemonic-new  < seed.txt | bx mnemonic-to-seed | bx hd-new
(seed.txt is the same, bx seed > seed.txt)
these two cmd will result in different private key, not sure which one is more secure or better
