### ISSUE TITLE
Libbitcoin-explorer installation fails-- Error compiling libbitcoin-client

### ISSUE THREAD

**Issue by felipeporcel** [libbitcoin/libbitcoin-explorer#306]
Hi, I get this error when I try to install libbitcoin-explorer.
I seems to depend of libbitcoint-client, and the compilation of this one fails, when it refers to a definition in payment_address class in libbitcoin library.
In file included from ./include/bitcoin/client/obelisk/obelisk_codec.hpp:25:
./include/bitcoin/client/obelisk/obelisk_router.hpp:52:39: error: unknown type name 'payment_address'; did you mean
      'wallet::payment_address'?
    typedef std::function<void (const payment_address& address, size_t height,
                                      ^~~~~~~~~~~~~~~
                                      wallet::payment_address
In fact there are more similar error when the code in libbitcoin-client points to classes in libbitcoin library.
In file included from ./include/bitcoin/client/obelisk/obelisk_codec.hpp:25:
./include/bitcoin/client/obelisk/obelisk_router.hpp:53:44: error: unknown type name 'transaction_type'
        const hash_digest& blk_hash, const transaction_type&)> update_handler;
Thanks

**Comment by skaht** [comment]
Clueless as to how you are performing the build.  Look at the bottom of the thread at https://github.com/libbitcoin/libbitcoin-client/issues/108#issuecomment-155973441 for details to build bx.

**Comment by felipeporcel** [comment]
Hi,
I think is not the same error, it's not a problen related to pkg-config package not found. in my case all packages are found. In fact I used to have a previos version of bx built before.
I updated libbitcoin, (some files changed i.e as far as I know address.cpp doesn't exist anymore, now is pay_address.cpp ) and since then I get these errors. It seems to me there is some mitsmatch versions between libbitcoin library and libbitcoin-explorer that uses it. Does anyone have built libbitcoin-explorer recently?

**Comment by skaht** [comment]
Very aware your error is not the same, but the solution is very likely to be the same.

Libbitcoin is a very fast moving target on the development side.  Package configurations are constantly in flux.  Been building packages constantly over the last 10 months using package branch heads.  You might have been very lucky with your last successful build and not realized it.  

I highly recommend following the instructions referenced above for compiling a standard bx build using the **install.sh** by first performing a fresh git clone of the bitcoin-explorer package. The pain factor is minimized if the install.sh approach is taken.  It is the most likely the approach the will keep all the packages synced.  

When I perform my own non-standard builds, I always examine the package hash results at https://travis-ci.org/libbitcoin for the different packages. I also pay particular attention the contents of https://github.com/libbitcoin/libbitcoin-explorer/blob/master/install.sh#L598.

**Comment by felipeporcel** [comment]
I've tried to install it with install.sh. ./install.sh --prefix=/Users/felipe/Projects/code/libbitcoin-explorer/
The libbitcoin-client fails to be build. As i said, there seems to be some kind mismatch definittion in libbitcoin classes referenced from libbitcoin-client
Thanks

**Comment by evoskuil** [comment]
Are you building from master or version2 (release)?

**Comment by evoskuil** [comment]
Based on the error message and cross referencing line numbers, it's the case that you are building `libbitcoin/master` and `libbitcoin-client/version2`. It would not be possible to mismatch these branches when building from an install.sh into a clean prefix directory unless possibly if you previously sudo'd an install without a prefix directory.

**Comment by skaht** [comment]
felipeporcel,

When you cd into the libbitcoin-explorer directory and perform a ```git show``` what is the commit configuration?

The following is what I get:

```
%  git show
commit 2ccfe525a63907f3b45fd1a48033e8b08436799d
Merge: da6f3d4 044614f
Author: Eric Voskuil <eric@voskuil.org>
Date:   Wed Nov 11 14:34:06 2015 -0800

    Merge pull request #305 from libbitcoin/network
    
    P2P network redesign.
```

The version displayed should match the prefix displayed to the right of the blue header https://github.com/libbitcoin/libbitcoin-explorer and Travis.  (Note that Travis currently in flux, but I decided to take my chances.)

% ./install.sh --prefix=/Users/XXX/Projects/bitcoin-explorer/test --build-dir=/Users/XXX/Projects/bitcoin-explorer/build --disable-shared --build-icu --build-boost

```
...
  CXX      test/test_libbitcoin_explorer_test-main.o
  CXXLD    test/libbitcoin_explorer_test
clang: warning: argument unused during compilation: '-pthread'
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: libbitcoin_explorer_test_runner.sh
============================================================================
Testsuite summary for libbitcoin-explorer 3.0.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by felipeporcel** [comment]
Ok, thanks to both of you. I had a some old references. I cleaned them and did 
./install.sh --prefix=/Users/felipe/Projects/bitcoin-explorer/test --build-dir=/Users/felipe/Projects/bitcoin-explorer/build --disable-shared --build-icu --build-boost and it worked
Thanks again
