### ISSUE TITLE
BIP 39 mnemonic-to-seed pw option requires ICU build

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-explorer#311]
Using install.sh build mechanism on a Mac last night, built configuration 99cfc47c86eb10f849f2c9b028e4933618b68563.  Tried the BIP 39 [Example #3](https://github.com/libbitcoin/libbitcoin/wiki/Altcoin-Version-Mappings).

```
./install.sh --disable-shared --prefix=/Users/XXX/Projects/BX/version2 --build-dir=/Users/XXX/Projects/BX/version2/build --build-icu --build-boost
```

**Results with password**:
```
echo 'enable load garage hard diagram trim nothing exclude fantasy gold ramp fiber wise ball have hero toddler spy excite glue maze drill else sell' | bx mnemonic-to-seed -p TREZOR
```
```
The passphrase option requires an ICU build. 
```
**Results without password**:
```
echo 'enable load garage hard diagram trim nothing exclude fantasy gold ramp fiber wise ball have hero toddler spy excite glue maze drill else sell' | bx mnemonic-to-seed
```
```
bc1aaed38d43d973ca33907a89fc2f10f525c77bc6398af6cd51632f286ab9a19006fa4ab9a2142904b1c88e36ba75d0b9d337c2e1ccbe0121c5080c75dd8bc3
```

Also, is BIP 38 ```ek command``` functionality support to remain a **master/version3** capability?

**Comment by evoskuil** [comment]
> Also, is BIP 38 ek command functionality support to remain a master/version3 capability?

yes

**Comment by evoskuil** [comment]
> The passphrase option requires an ICU build.

This is correct behavior.

**Comment by SCBuergel** [comment]
Currently the binaries seem on the [Downloads page](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Download-BX) do not seem to be shipping with ICU (I tested the Mac version). That is a bit annoying as mnemonics cannot be used with passwords. I'd suggest changing that unless there are good reasons to not do so.

**Comment by thecodefactory** [comment]
@SCBuergel See https://github.com/libbitcoin/libbitcoin-system/issues/1029 for some relevant details.

**Comment by SCBuergel** [comment]
For an end-to-end workflow in BX the use of a password is of central importance - I do not find it acceptable to only work with mnemonics without passphrase. If that is only possible through a custom build process which requires custom parameters, a range of non-standard dependencies and then takes about 15 minutes to build and test (just did that on Mac), then the utility of BX is severely limited.

I do not see much movement on the issue that you referenced. I'd be happy to chip in to a Gitcoin bounty if we have a well-defined issue that makes sense for a bounty.

**Comment by thecodefactory** [comment]
@SCBuergel The current requirement for the proper use of BIP-39 passphrases includes a dependency that (at the moment) can't be provided for all platforms in binary form.  If you're able to make traction on Windows, pull requests are welcome, as are the third-party boost builds (if that's the better way to go).  In the meantime, everything is available, including an easy to use install script.  Acceptable to you or not, it's what it is (at the moment).

**Comment by evoskuil** [comment]
The precompiled binaries are not intended for production use.
