### ISSUE TITLE
Invalid JSON output for fetch-history (duplicate keys)

### ISSUE THREAD

**Issue by tmsrjs** [libbitcoin/libbitcoin-explorer#315]
When querying for an address' history in JSON format, the output contains a "transfer" key for each transaction affecting the address.
<pre>$ bx fetch-history -f json 1ducYz8pB86cYUqj8jhyqqZCQU6KH6qXQ
{
    "transfers":
    {
        "transfer":
        {
            "received":
            {
                "hash": "72d267b1a4d84c1f182f8fc1652e8c6a15e1a5e1b804bd9a7c6a17b6c456512e",
                "height": "396180",
                "index": "0"
            },
            "value": "20000000000"
        },
        "transfer":
        {
            "received":
            {
                "hash": "6ce05ea54f0d24e94215d8a193d9e29f729b06729e8897e2222b9c6e9b58dcd3",
                "height": "396179",
                "index": "0"
            },
            "value": "20000000000"
        },
        "transfer":
        {
            "received":
            {
                "hash": "a9e9c0164a5b51c309ab9ae9c8b9bffabd3dc85f0de7ec34877af1f5bda16db2",
                "height": "396171",
                "index": "0"
            },
            "spent":
            {
                "hash": "e1be603ef3cccabcb169f1f75db6079d04c1d7b770f2dcbc0971f95707895874",
                "height": "396173",
                "index": "0"
            },
            "value": "20000000000"
        }
    },
    ...
}</pre>
When parsing this output, you get an associative array with only **one** "transfer" key (most likely the last entry).
<pre>
{"transfers"=>
    {"transfer"=>
        {"received"=>
            {"hash"=>"100ec36d9ca8891fb34e00f8999656b4273e4dd1d3084cf0df9656f7ebaabb79", 
             "height"=>"395325", "index"=>"0"},
         "spent"=>
            {"hash"=>"a0a1be73e1ee4d1c6526b641a8139364c9140786cf958f91513a81743fb83a5f",
             "height"=>"395337", "index"=>"0"},
         "value"=>"100000000000"
        }
    }
}
</pre>
I think the desired output would be an array of associative arrays representing each transaction.

What do you guys think?

**Comment by evoskuil** [comment]
The serialization (for xml, json and info) is all done by [boost::property_tree](http://www.boost.org/doc/libs/1_60_0/doc/html/property_tree.html). I believe the issue is that your parser does not have the ability to expose multiple siblings of the same name (though clearly it's able to parse them). Boost property tree does not support JSON array serialization.

**Comment by HamishMacEwan** [comment]
Similar problems arise for `tx-decode -f json`.  `inputs` and `outputs` when evaluated as json result in only the last `input` and `output` being available.

It is a pity that bx is willing to have its utility so impaired by not correctly forming the JSON output.  That it occurs in a package when there are so many that serialise without the error is hardly a sufficient reason to do nothing.  Whatever the issue is, the effect is bx is non-functional when its JSON output is evaluated.

The string parse works, but the JS evaluation doesn't, which renders this output from a misapplied "tree property" function unusable in tools like [jq](https://stedolan.github.io/jq/).

**Comment by evoskuil** [comment]
This is resolved by https://github.com/libbitcoin/libbitcoin-explorer/pull/323

I was mistaken that [boost::property_tree](http://www.boost.org/doc/libs/1_60_0/doc/html/property_tree.html) does not support (JSON-style) array serialization. The documentation states that JSON type information is lost on round trip, and the example implies that array formatting is lost. But upon closer inspection, the example is not a round trip, it shows JSON input and INFO output.

But it is possible to format for array output. The technique is not documented, but I found a good [example](http://stackoverflow.com/a/12821620/1172329) on SO. It also would reduce the quality of the other formats (producing unnamed elements), so I limited the array formatting to JSON encoding. This also preserves backward compatibility for the other encodings.

This change only applies to version3 (master) builds, which are not yet released.

**Comment by evoskuil** [comment]
FWIW I would have fixed boost before accepting another dependency for this. We have worked hard to reduce dependencies (and are continuing to do so), as each introduces significant complexities in the cross-platform environment and increases security risks.

**Comment by HamishMacEwan** [comment]
Hi Eric,

Thank you very much for finding a way.  Particularly one that doesn't increase dependencies and complexity.  I'm pretty sure I'm at my limit with complexity in the area of bx and Bitcoin.

Looking forward to the release of version 3.

**Comment by evoskuil** [comment]
Thanks for the feedback @HamishMacEwan,

We're going to be able to remove **libsodium** as a dependency, and will probably also eliminate **czmqpp** at some point. Also note that **ICU**, **libpng** and **qrencode** are all optional. That will get us down to 4 external core dependencies for bx (**libzmq**, **czmq**, **libsecp256k1** and **boost**). But we are already significantly better that previously with sx. And I don't think it's really feasible to get any leaner than this in Bitcoin.

**Comment by HamishMacEwan** [comment]
I guess (as a naive observer of these projects) you need to balance the benefits of dependence on static or well-maintained dynamic subsystems with many eyeballs keeping all bugs shallow (e.g. qrencode, Boost) and consuming the projects limited resources on reinventing wheels in search of controlled and crafted code.

All part of the architectural and resource challenge you face in this endeavour.

**Comment by evoskuil** [comment]
Yes, and in some cases opting out of certain "features", like HTTP/S for example (we dropped cURL as a dependency).

BX also dropped Python, libcurses, libconfig, and traded massive OpenSSL for tiny libsecp256k1.

**Comment by evoskuil** [comment]
We also repackaged libbitcoinconsensus as an internal and optional library so as to avoid a dependency on bitcoin-core.

**Comment by HamishMacEwan** [comment]
Serious independence, and nice to see interoperable reimplementations of those functions, with the earlier caveats.

**Comment by skaht** [comment]
@evoskuil,
If memory serves me, was there also a MPFR library dependency that you removed?

**Comment by evoskuil** [comment]
The GMP dependency was added and later removed during the process of removing OpenSSL.
