### ISSUE TITLE
ec-to-address is unavailable

### ISSUE THREAD

**Issue by belgacoin** [libbitcoin/libbitcoin-explorer#317]
When trying

bx seed | bx ec-new | bx ec-to-public | bx ec-to-address

I get an error saying that: "ec-to-address is unavailable"

How can I fix this?

**Comment by belgacoin** [comment]
Sorry, ignore this request. It was a typo (bc instead of bx) ;)

**Comment by thecodefactory** [comment]
No worries, glad it's resolved!
