### ISSUE TITLE
Boost 1.55 [version2] 1.56 [master] not in Ubuntu 14.04.

### ISSUE THREAD

**Issue by onepix** [libbitcoin/libbitcoin-explorer#336]
No way to install it via ubuntu 14.04 without
http://packages.ubuntu.com/search?keywords=libboost1.55-all-dev (or more)
because `sudo apt-get install libboost-all-dev` install the 1.54 version

**Comment by evoskuil** [comment]
You always have the option to use another repository or build boost manually or using install.sh (recommended). Boost 1.54 has a bug that makes it insufficient.

**Comment by evoskuil** [comment]
See bug reported 3 years ago in boost 1.54 (resolved in boost 1.55).

**Comment by evoskuil** [comment]
Hi @onepix, were you able to get it built?

**Comment by onepix** [comment]
Hi @evoskuil, I didn't wanted to bother you about it but if I may : 
- From my laptop, I followed the instructions but I didn't make it. I "try hard" via installing manually a boost version from their website "get started", I also try without the install.sh but it's a failure (I skip details)
- After, from my desktop Ubuntu VM (same version as my laptop), I give another try and it worked like charm, perfect. (install.sh)

I was pretty sure that the boost package was the issue into my laptop but after doing exactly the same as my VM I encountered "weird compilation error". I suspect that I have somehow "corrupt" my environment during my "try hard" phase and I give up to use your binary instead because I don't know how "recover the initial state" of my environment.
I just obtain a mac today so I will try another time 😆

**Comment by evoskuil** [comment]
Hi @onepix, thanks for the feedback.

When building I strongly recommend using a `--prefix` directory. This will not only make the build more reliable by isolating dependencies from your environment, but it will also protect your environment from changes (and precludes the need for sudo). Really the install should be as simple as invoking install.sh with a prefix and any dependencies you need built. This is tested regularly on Travis and is usually how I perform my own builds.

Also, if you are using version2, you should set `--disable-shared` when building boost or other non-libbitcoin dependencies. There is a problem with the linker always preferring system libraries. In master/version3 this has been resolved.

**Comment by onepix** [comment]
Well, thanks for this clear answer. 
Indeed I think there is something related to --disable-shared about the error I had, I'll definitively give another try, for fun.
Because I'm on mac os now and It works perfectly ! 👍

**Comment by evoskuil** [comment]
@onepix Can we consider this resolved?

**Comment by onepix** [comment]
Yes, thank you
