### ISSUE TITLE
Not enough documentation for input-sign and input-set.

### ISSUE THREAD

**Issue by ghost** [libbitcoin/libbitcoin-explorer#337]
How do you spend a bitcoin with multiple inputs how does input-sign and input-set work with multiple inputs can some please show a example.

**Comment by evoskuil** [comment]
Hi @donsoleux, see the tutorials and general documentation on the wiki. For example:

https://github.com/libbitcoin/libbitcoin-explorer/wiki/How-to-Spend-Bitcoin

**Comment by donsoleux** [comment]
I did check that but it uses only one input. How would you go about if you would like to spend multiple inputs.

**Comment by thecodefactory** [comment]
You can specify as many inputs and outputs as you'd like.  This will generate bogus info for example:

```
bx tx-encode -i f759759bc998ec96879e4ae8c1639e8a186e0d507401eb32e4479de64d340605:0 -i f759759bc998ec96879e4ae8c1639e8a186e0d507401eb32e4479de64d340605:1 -o 1966U1pjj15tLxPXZ19U48c99EJDkdXeqb:45000 -o 1966U1pjj15tLxPXZ19U48c99EJDkdXeqb:55000
```

**Comment by donsoleux** [comment]
Thanks @thecodefactory  how would I sign the result of tx-encode, with input-sign and input-set.

**Comment by thecodefactory** [comment]
@ghost I'm not sure what you're asking.  input-sign creates the endorsement for an input.  Then input set will create the script from that and assign it to a specified transaction at some index.  The first could be set at 0, the second at 1 (using ```-i 0``` on the first and ```-i 1``` on the second).

The referenced link describes clearly how to use those commands.  The input-sign command changed slightly (to not include the nonce, as noted), so you would instead do:

```
bx input-sign 4ce3eb6bd06c224e3c355352a488720efc5ac9fe527a219ad35178c3cf762350 "dup hash160 [ c564c740c6900b93afc9f1bdaef0a9d466adf6ee ] equalverify checksig" 01000000017d01943c40b7f3d8a00a2d62fa1d560bf739a2368c180615b0a7937c0e883e7c0000000000ffffffff01c8af0000000000001976a91458b7a60f11a904feef35a639b6048de8dd4d9f1c88ac00000000
```

Each command has a help section that describes the command line arguments.  Have you tried that?

```
bx help input-sign
```

**Comment by thecodefactory** [comment]
@ghost Were you able to resolve your issue?

**Comment by thecodefactory** [comment]
@ghost I'm closing this due to no response.  Hopefully you were able to resolve your issue.
