### ISSUE TITLE
testnet mode generate keys

### ISSUE THREAD

**Issue by onepix** [libbitcoin/libbitcoin-explorer#338]
> bx help
Usage: bx COMMAND [--help]
Version: 2.2.0 [testnet]

The mode is testnet but when I generate keys they're not in maintnet format instead of testnet format, is that normal ?

**Comment by onepix** [comment]
sudo ./install.sh --without-tests --enable-testnet
sorry for the post

**Comment by evoskuil** [comment]
In version2 testnet behavior is partially controlled by the build switch and partially by command line options. Depending on the command you probably need to set the "version" byte.

In master/version3 the network is defaulted in the configuration file and can be overridden using command options.

**Comment by evoskuil** [comment]
Also, in version2 one must be careful to build all libbitcoin libraries (libbitcoin, client and explorer) with the `--enable-testnet` switch. The installer does this automatically.

**Comment by evoskuil** [comment]
@onepix Is this resolved?

**Comment by evoskuil** [comment]
Closed for lack of activity.
