### ISSUE TITLE
ec-to-wif no longer has version specification?

### ISSUE THREAD

**Issue by stoicism2323** [libbitcoin/libbitcoin-explorer#339]
In this web page (https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-ec-to-wif) it shows that you can specify the version for ec-to-wif to generate a testnet wif. However, when I run the command (downloaded the latest build for linux from here: https://github.com/libbitcoin/libbitcoin-explorer/wiki/Download-BX) it seems there is no longer a version speicifier:

```
[erich@localhost libbitcoin]$ bx ec-to-wif -h

Usage: bx ec-to-wif [-hu] [--config VALUE] [EC_PRIVATE_KEY]              

Info: Convert an EC private key to a WIF private key. The result         
associates with the compressed public key format by default.             

Options (named):

-c [--config]        The path to the configuration settings file.        
-h [--help]          Get a description and instructions for this command.
-u [--uncompressed]  Associate the result with the uncompressed public   
                     key format.                                         

Arguments (positional):

EC_PRIVATE_KEY       The Base16 EC private key to convert. If not        
                     specified the key is read from STDIN. 

```
How can I easily generate a testnet wif without having to set the version of the bx over, which would require recompiling the program right? Reason I downloaded in the first place was because I can't figure out how to compile this (complains about needing libczmq to compile libczmq++ even though libczmq.a and .so is already present in my /usr/local/lib).

Thanks

**Comment by stoicism2323** [comment]
I forgot to mention. When I run the command, I get the following error when I use the command:

```
... | bx ec-new | bx ec-to-wif -v 239
Error: the argument ('239') for option '--EC_PRIVATE_KEY' is invalid
```

Or when I try to create without pipes:
```

$ bx ec-to-wif --version 239 785bf1d29443fb7cc082c948d880159b626cedf9bf40b5afb8b0e3a2f55421ab
Error: too many positional options have been specified on the command line
```

**Comment by evoskuil** [comment]
Hi @stoicism2323,

It would seem that you are running **version2**, which derives the version from compilation with the `--enable-testnet` switch. The documentation has been updated for the upcoming **version3** (currently master branch), which is not conditionally compiled. The `help` output is correct for version2 and the errors are resulting from the fact that there is no `--version` option.

> complains about needing libczmq to compile libczmq++ even though libczmq.a ...

Notice that these are two distinct libraries. I recommend building with the `install.sh` and using a `--prefix` directory. Explorer master (version3) is in good shape, release quality.
