### ISSUE TITLE
Default libbitcoin-server outage.

### ISSUE THREAD

**Issue by sonicskye** [libbitcoin/libbitcoin-explorer#354]
Hi, I have problem connecting to a stable libbitcoin/obelisk server. Sometimes it connects, but sometimes it disconnects. Any suggestion?

**Comment by evoskuil** [comment]
That's not much to go on. Connect using what software, code? Is the server Obelisk or libbitcoin-server? What versions? Do you control the server and client code? Are there any errors in the client and/or server logs?

**Comment by sonicskye** [comment]
Hi Erik. I connect using BX on Windows. I've tried version 2.1 and 2.2 but all result in timed out. It was working well yesterday, but when I tried executing "fetch-height", the result is timed out. I use the standard configuration.

**Comment by evoskuil** [comment]
Assuming you are using the default configuration this implies the server or your network is down. I have been noticing occasional outages of the default server.

**Comment by evoskuil** [comment]
AirBitz maintains the default servers. If one is out their support might be able to help.

**Comment by sonicskye** [comment]
Yes, there might be another outage. Thank you.
