### ISSUE TITLE
How to run fetch-tx on testnet?

### ISSUE THREAD

**Issue by stoicism2323** [libbitcoin/libbitcoin-explorer#365]
To run a fetch-tx to view transaction 99391604f5db38ca84ed8e888042b134db4b530a4765cd56287ee0246d791a63 on the testnet, I tried this command:

`bx fetch-tx -c /path/to/libbitcoin-explorer/data/bx-testnet.cfg 99391604f5db38ca84ed8e888042b134db4b530a4765cd56287ee0246d791a63`

It comes back with an empty output, last line of which is 'object does not exist'. Trying `bx settings -c bx-testnet.cfg` shows correct settings for the testnet. I'm wondering if there's something I'm missing here. Thanks!

**Comment by evoskuil** [comment]
If you are running `version2` you must compile (all repos) for testnet, see [--enable-testnet](https://github.com/libbitcoin/libbitcoin-explorer/blob/version2/README.md#configuration-options) and [modify config](https://github.com/libbitcoin/libbitcoin-explorer/blob/version2/data/bx.cfg#L6) by setting `general.network = testnet`.

In version3 [master] there is no conditional compile, you just need to modify [configuration settings](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Configuration-Settings). There is a sample [testnet config file](https://github.com/libbitcoin/libbitcoin-explorer/blob/master/data/bx-testnet.cfg) in the build.

**Comment by stoicism2323** [comment]
Thanks for the reply Eric. I am using bx version3, and I am using the bx-testnet.cfg file stored in the data/ dir (specified with the -c option), but it doesn't return any results when I give it a valid testnet transaction. Does something need to be added to the bx-testnet.cfg file or should it work out of the box? Thanks

**Comment by evoskuil** [comment]
Oh, sorry - missed part of your original comment. It should work but there have been a lot of changes in the protocol implementation recently, with tests running against a version3 server. I'll give it a look.

**Comment by evoskuil** [comment]
The default server [tcp://obelisk-testnet.airbitz.co:9091] is well blow the height of the tx you are fetching, Try:
```
$ bx fetch-tx 5d8a1d5d408bd581c6d792ca0c3d3e1122e9f81dfc6dc874025c682760226c3e
```

**Comment by stoicism2323** [comment]
Thanks for the response. Is there an alternative to airbitz.co for testnet obelisk server, one which is not stuck on January 20th? :)

Or at this point do I need to run my own obelisk server in which case this becomes localhost?

Thanks

**Comment by evoskuil** [comment]
I"m not aware of any others, you could ping Airbitz - they are pretty good about it. Also, I think they changed the port of their mainnet server to 80. But otherwise setting up a v2 server would be an option. You can do v3 but it currently will only sync to the last checkpoint, it won't maintain the chain.

**Comment by evandrix** [comment]
> If you are running `version2` you must compile (all repos) for testnet, see [--enable-testnet](https://github.com/libbitcoin/libbitcoin-explorer/blob/version2/README.md#configuration-options) and [modify config](https://github.com/libbitcoin/libbitcoin-explorer/blob/version2/data/bx.cfg#L6) by setting `general.network = testnet`.
> 
> In version3 [master] there is no conditional compile, you just need to modify [configuration settings](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Configuration-Settings). There is a sample [testnet config file](https://github.com/libbitcoin/libbitcoin-explorer/blob/master/data/bx-testnet.cfg) in the build.

404: https://github.com/libbitcoin/libbitcoin-explorer/blob/master/data/bx-testnet.cfg
