### ISSUE TITLE
Problem with libbitcoin-network

### ISSUE THREAD

**Issue by stevijo** [libbitcoin/libbitcoin-explorer#368]
There seems to be a build problem with the explorer, as to a change in libbitcoin network. 
The file [https://github.com/libbitcoin/libbitcoin-explorer/blob/master/src/commands/send-tx-p2p.cpp](url) does not compile.
As i understand, that what the start_handler did now is handled in the result_handler and just the naming must be adjusted and the workaround here `
network.stop(stop_handler);
stopped.get_future();` can just be replaced with `network.stop();`. 
I already created a pull request #367 for that.

**Comment by evoskuil** [comment]
I'm traveling without hardware, so making these changes is a bit hard at the moment.
