### ISSUE TITLE
Install data/bx-testnet.cfg alongside data/bx.cfg?

### ISSUE THREAD

**Issue by RojavaCrypto** [libbitcoin/libbitcoin-explorer#372]
This is more of a question, but it would be good to have the config file so people can easily switch. Maybe a comment saying they can use -c in the top of the file.

**Comment by evoskuil** [comment]
We already install this: https://github.com/libbitcoin/libbitcoin-explorer/blob/master/data/bx-testnet.cfg

**Comment by evoskuil** [comment]
Hm, it's not set in Makefile.am. Need to update libbitcoin-build to include the file.

**Comment by thecodefactory** [comment]
Good catch.  I'll update this momentarily.

**Comment by thecodefactory** [comment]
libbitcoin/libbitcoin-build#64
libbitcoin/libbitcoin-explorer#373
