### ISSUE TITLE
Compilation problem on Kali 

### ISSUE THREAD

**Issue by nolaforensix** [libbitcoin/libbitcoin-explorer#382]
I'm getting the following compilation error while trying to build on Kali:

  ****CXX      src/src_libbitcoin_blockchain_la-organizer.lo
In file included from ./include/bitcoin/blockchain/validate_block_impl.hpp:28:0,
                 from src/organizer.cpp:33:
./include/bitcoin/blockchain/validate_block.hpp:66:27: error: ‘libbitcoin::chain::script_context’ has not been declared
     bool is_active(chain::script_context flag) const;
                           ^
Makefile:942: recipe for target 'src/src_libbitcoin_blockchain_la-organizer.lo' failed
make: *** [src/src_libbitcoin_blockchain_la-organizer.lo] Error 1****

Any thoughts?

Thanks,

--Golden

**Comment by evoskuil** [comment]
Sorry, master is in the midst of a cross-lib merge. Should be complete shortly.

**Comment by evoskuil** [comment]
Actually I think bx should be fine, this was resolved last night.
