### ISSUE TITLE
Build error "No package 'libczmq' found"

### ISSUE THREAD

**Issue by franklili3** [libbitcoin/libbitcoin-explorer#407]
In Mac os x capitan, when I run $ sudo ./configure —enable-leveldb, the error is
 "configure: error: Package requirements (libczmq) were not met:

No package 'libczmq' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libczmq_CFLAGS
and libczmq_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details."
How can I do?

**Comment by evoskuil** [comment]
I don't understand, why are you enabling leveldb, is that a typo?

**Comment by evoskuil** [comment]
@franklili3 I'd love to help but need more info.

**Comment by franklili3** [comment]
Now I run the all commands from the beginning. After I run "sudo ./install.sh CXXFLAGS=-Os --enable-ndebug", and when I run "bx", the error is "-bash: bx: command not found". How can I do?
[config_log.txt](https://github.com/libbitcoin/libbitcoin-explorer/files/594999/config_log.txt)

**Comment by evoskuil** [comment]
Assuming that the binary was compiled and exists on your machine this would be a bash question not a bx question.
