### ISSUE TITLE
commands/*.cpp have no namespace including

### ISSUE THREAD

**Issue by betachen** [libbitcoin/libbitcoin-explorer#411]
libbitcoin-explorer/src/commands/*.cpp

I found that all libbitcoin-explorer/src/commands/*.cpp  have no namespace including as:
```cpp
namespace libbitcoin {
namespace explorer{
//...
}
}
```

all source code using:

```cpp
using namespace bc;
using namespace bc::explorer;
```

in anonymous space.

**Comment by evoskuil** [comment]
Thanks, I've created an issue to improve this. Feel free to issue a PR with this change. It's a lot of files though, so be careful to match the style guide.

**Comment by betachen** [comment]
@evoskuil sure, In this week I'll push changes.
Now I'm working on [metaverse](https://github.com/the-metaverse)  project which forked from libbitcoin , It costs my lots of time.

**Comment by evoskuil** [comment]
Great to hear, thanks!

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-explorer/pull/416
