### ISSUE TITLE
Seed Wiki Example Incorrect

### ISSUE THREAD

**Issue by JoshLind** [libbitcoin/libbitcoin-explorer#413]
Hi,

It appears one of your examples for the seed command in the wiki is incorrect. If you look at page (https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-seed), for the 128 bit seed, shouldn't the command be:

"bx seed -b 128"

instead of

"bx seed"

My understanding is that the default bit length is 192, hence "bx seed" is equivalent to "bx seed -b 192".

Hopefully I haven't miss understood something!

Thanks!

**Comment by evoskuil** [comment]
Thanks for posting. The value length for the default was correctly shown as 192 bits. The explanation was wrong, should have read "192 but seed". I've correct the page.

**Comment by JoshLind** [comment]
Great! Thanks for fixing this :)
