### ISSUE TITLE
Failing input-sign command

### ISSUE THREAD

**Issue by JoshLind** [libbitcoin/libbitcoin-explorer#414]
Hi,

Apologies if I am misunderstanding something, but I'm trying to run through the example at:
https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-input-sign

Everything works up until I make an input-sign request. Giving my command line:

bx input-sign 4ce3eb6bd06c224e3c355352a488720efc5ac9fe527a219ad35178c3cf762350 "dup hash160 [ c564c740c6900b93afc9f1bdaef0a9d466adf6ee ] equalverify checksig" 01000000017d01943c40b7f3d8a00a2d62fa1d560bf739a2368c180615b0a7937c0e883e7c0000000000ffffffff01c8af0000000000001976a91458b7a60f11a904feef35a639b6048de8dd4d9f1c88ac00000000

I am given the error:

Error: the argument ('dup hash160 [ c564c740c6900b93afc9f1bdaef0a9d466adf6ee ] equalverify checksig') for option '--CONTRACT' is invalid

Am I missing something here?

Thanks for your help!

**Comment by evoskuil** [comment]
Remove the spaces from inside of the data brackets. This was a recent change in master/v3.

**Comment by JoshLind** [comment]
Aah okay, thanks! Sure -- makes sense.
