### ISSUE TITLE
confused about index and generating addresses

### ISSUE THREAD

**Issue by eMosbat** [libbitcoin/libbitcoin-explorer#420]
I  have a master private key (hd-new).
I can generates serveral addresses by changing index of private key:

    hd-new | hd-private -i N | hd-public | hd-to-address

so then I have all private keys. but what about when  I generates several addresses from public key?

    hd-new | hd-public -i N | hd-to-address
 
 I have no option to reproduce and find private keys of these addresses?!

my goal is: do not upload and use master private key online and use public key to generate addresses.
but also, I would like to import these addresses in my wallet client so I need private keys of them too!

**Comment by evoskuil** [comment]
Private keys of derived public keys are derived from the master private key using the same derivation path you used to derive the public keys from the master public key. See [IP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki).
