### ISSUE TITLE
[master] update for server validate2

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-explorer#427]
The client-server API has changed so that `validate` is obsolete with `validate2` taking its place.

The new function returns only a result code indicating the specific validation error or success. The previous implementation also returned a set of unconfirmed inputs. Input height can instead be obtained by calling `fetch_transaction_position` as desired. Height is more useful than the Boolean response and this simplifies the interface and implementation. This requires a corresponding change in `libbitcoin-client`.

**Comment by thecodefactory** [comment]
Ok, will update after some testing.
