### ISSUE TITLE
Add subscribe-tx and subscribe-block (pub-sub)

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-explorer#467]

**Comment by thecodefactory** [comment]
👍 on subscribe-block.  Let's discuss this at some point.

Not sure I fully understand the use-case for subscribe tx, but I suppose it could be like a finer grained watch-address that monitors when it hits the mempool (hopefully on broadcast) or a block?

**Comment by evoskuil** [comment]
Yes. What's the question regarding subscribe-block?
