### ISSUE TITLE
Decoding Testnet tx does not show correct addresses

### ISSUE THREAD

**Issue by shigeya** [libbitcoin/libbitcoin-explorer#476]
If I understand correctly, it looks like `tx-decode` does not show correct address with the Testnet transactions.

For example, tx `6a47b0fbbc56e8c8cc35ba32b350650086df6fdeb72700aa676507253d023af6` in the testnet, the raw transaction is:

```
0100000001e4249228e6a527c62ce3c3ed54a5870bc6e7e156e3570f85cb9deb2b37fde1a9000000006b483045022100da6d9c3a37637c78176417f2f72132b4b11fc6d48e2ac96a2870123dcd253518022051a74a98c38f0fcdc7f4d22b8e59cea5e187a4a01e5d18079fd5e117b43f765f012103c5297bdaad52695a7ea230d5025d91a3b44713b7c28667780db61b95b90b67cefeffffff0206951d00000000001976a914e20f0931ce3371d93d8a834505b8032e3db1cafd88ac78e60000000000001976a914685d1250b82443f569fa7260da8028d8666c570f88acd3141100
```

The output with the `bx tx-decode` is like this:

```
transaction
{
    hash 6a47b0fbbc56e8c8cc35ba32b350650086df6fdeb72700aa676507253d023af6
    inputs
    {
        input
        {
            address 1K5c75ANzW5YqVhNcsWZGtGbKFpGJqnRnc
            previous_output
            {
                hash a9e1fd372beb9dcb850f57e356e1e7c60b87a554edc3e32cc627a5e6289224e4
                index 0
            }
            script "[3045022100da6d9c3a37637c78176417f2f72132b4b11fc6d48e2ac96a2870123dcd253518022051a74a98c38f0fcdc7f4d22b8e59cea5e187a4a01e5d18079fd5e117b43f765f01] [03c5297bdaad52695a7ea230d5025d91a3b44713b7c28667780db61b95b90b67ce]"
            sequence 4294967294
        }
    }
    lock_time 1119443
    outputs
    {
        output
        {
            address 1McHj4uu6mP1vKCYxRHGWLVGRGkMS73Hpr
            script "dup hash160 [e20f0931ce3371d93d8a834505b8032e3db1cafd] equalverify checksig"
            value 1938694
        }
        output
        {
            address 1AWpmg8Rwab9MNkwGNhJ4gd5AVPR4hkNme
            script "dup hash160 [685d1250b82443f569fa7260da8028d8666c570f] equalverify checksig"
            value 59000
        }
    }
    version 1
}
```

`1AWpmg8Rwab9MNkwGNhJ4gd5AVPR4hkNme` should be `mq2n4jDQkc2Q8VEYywfftbqQ2Uz7uAsyDj`

I have checked with https://live.blockcypher.com/btc-testnet/decodetx/ and it reveals correctly.

**Comment by evoskuil** [comment]
Hi @shigeya, please see [Testnet Support](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Testnet-Support).

**Comment by shigeya** [comment]
hi @evoskuil. I believe i have configured it correctly via `BX_CONFIG` environment variable. Running `bx settings` show following result:

```
settings
{
    network
    {
        channel_handshake_seconds 30
        connect_retries 0
        connect_timeout_seconds 5
        debug_file debug.log
        error_file error.log
        hosts_file hosts.cache
        identifier 118034699
        seeds testnet-seed.bitcoin.jonasschnelli.ch:18333,seed.tbtc.petertodd.org:18333,testnet-seed.bluematt.me:18333,testnet-seed.bitcoin.schildbach.de:18333,testnet-seed.voskuil.org:18333
    }
    server
    {
        client_private_key 0000000000000000000000000000000000000000
        connect_retries 0
        connect_timeout_seconds 5
        server_public_key 0000000000000000000000000000000000000000
        socks_proxy 0.0.0.0
        url tcp://testnet3.libbitcoin.net:19091
    }
    wallet
    {
        hd_public_version 70617039
        hd_secret_version 70615956
        pay_to_public_key_hash_version 111
        pay_to_script_hash_version 196
        transaction_version 1
        wif_version 239
    }
}
```
Am I missing something?

**Comment by shigeya** [comment]
Note: I created the address `mq2n4jDQkc2Q8VEYywfftbqQ2Uz7uAsyDj` using `bx`, then transfered BTC from http://testnetwallet.com/wallet. That's the above mentioned transaction.

**Comment by evoskuil** [comment]
Ah, I see. No , you are not missing anything. The tx-decode serialization is not honoring the setting and is instead relies on the defaults. It's a bug that will affect address presentation in the tx-decode output (only). Thanks for reporting.

**Comment by evoskuil** [comment]
The address presentation is redundant with the script and is provided for convenience, so not critical but we'll get it fixed straight away.

**Comment by shigeya** [comment]
Thanks!

**Comment by evoskuil** [comment]
This issue exposes an implied dependency between tx decoding and payment address versioning. This in turn implies that txs are dependent upon addressing scheduled. This is an undesirable and unnecessary dependency chain. The [commands that depend on address versioning](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Wallet-Settings#pay_to_public_key_hash_version) are directly related to addressing. Transactions have no relationship to address versioning.

The presentation of a network-relative address for a transaction is a cosmetic convenience, however it is not necessary. We could change the output format so that the address **hash** is presented, leaving the address encoding to subsequent steps by the caller. We could alternatively simply leave out the address, as it can be easily derived from the script. 

Given there is no bx command to parse the address from standard scripts, it would be inconvenient to drop the property altogether, so I'm making the change to present the parsed address hash as `address_hash` and drop the `address` property.

**Comment by evoskuil** [comment]
Resolved in https://github.com/libbitcoin/libbitcoin-explorer/pull/478

**Comment by evoskuil** [comment]
[tx-decode documentation](https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-tx-decode) updated. accordingly
