### ISSUE TITLE
tx-decode shows incorrect input script address

### ISSUE THREAD

**Issue by shigeya** [libbitcoin/libbitcoin-explorer#477]
Hi.

Looks like there is some problem somewhere in tx-decode. Following tx:
```
0100000001833d56a22cd88ef7a17d51d30b169a86aa4138f60867a6e21fc88a7b546b5d64010000006a4730440220688fb2aef767f21127b375d50d0ab8f7a1abaecad08e7c4987f7305c90e5a02502203282909b7863149bf4c92589764df80744afb509b949c06bfbeb28864277d88d0121025334b571c11e22967452f195509260f6a6dd10357fc4ad76b1c0aa5981ac254effffffff030000000000000000246a22414243444546917ce6520f0740cd2c373bd506415777bd23e8680123456789abcdef10270000000000001976a914ce5b06176d2572d4fb985747f197c389b8ac64e888ac30750000000000001976a9143c6602137d7f9a68a96aff2d3cf37bbdeeb95b7d88ac00000000
```

shows

```
transaction
{
    hash 36cd6f786324d11bc61c04eb5364f264b2506f52104551020de5de23170f8f3a
    inputs
    {
        input
        {
            address 1AWpmg8Rwab9MNkwGNhJ4gd5AVPR4hkNme
            previous_output
            {
                hash 645d6b547b8ac81fe2a66708f63841aa869a160bd3517da1f78ed82ca2563d83
                index 1
            }
            script "[30440220688fb2aef767f21127b375d50d0ab8f7a1abaecad08e7c4987f7305c90e5a02502203282909b7863149bf4c92589764df80744afb509b949c06bfbeb28864277d88d01] [025334b571c11e22967452f195509260f6a6dd10357fc4ad76b1c0aa5981ac254e]"
            sequence 4294967295
        }
    }
    lock_time 0
    outputs
    {
        output
        {
            script "return [414243444546917ce6520f0740cd2c373bd506415777bd23e8680123456789abcdef]"
            stealth
            {
                prefix 2252711015
                ephemeral_public_key 02414243444546917ce6520f0740cd2c373bd506415777bd23e8680123456789ab
            }
            value 0
        }
        output
        {
            address 1Kp7ExkXbSMkBfisZYb7q5UfnrZGKW1Uxc
            script "dup hash160 [ce5b06176d2572d4fb985747f197c389b8ac64e8] equalverify checksig"
            value 10000
        }
        output
        {
            address 16WMkA91zv1XSTztY5X44sc5NEKoHhJ6Mo
            script "dup hash160 [3c6602137d7f9a68a96aff2d3cf37bbdeeb95b7d] equalverify checksig"
            value 30000
        }
    }
    version 1
}
```

but the correct `transaction.inputs[0].input.address` is `1Ngu4ZiwmHmG1MF9TcwFcsDAgAhrm9zQcp` not `1AWpmg8Rwab9MNkwGNhJ4gd5AVPR4hkNme`.

Decoding above encoded transaction on https://live.blockcypher.com/btc/decodetx/ show the correct result with key `1Ngu..`

**Comment by shigeya** [comment]
Forgot to mention. `validate-tx` fails on this. I ran same transaction build script on `testnet` and it was successful. Thus, I think there is something wrong.

**Comment by evoskuil** [comment]
Hi @shigeya,

The parsed script from the link you sent is:
```
47
30440220688fb2aef767f21127b375d50d0ab8f7a1abaecad08e7c4987f7305c90e5a02502203282909b7863149bf4c92589764df80744afb509b949c06bfbeb28864277d88d01
21
025334b571c11e22967452f195509260f6a6dd10357fc4ad76b1c0aa5981ac254e
```
That matches exactly the parsed output of `tx-decode` above. So if there is an error it would be in the extraction of the address from the standard p2kh script. This is a process of extracting the second opcode's data and converting its compressed public key to a mainnet payment address:
```
$ bx ec-to-address 025334b571c11e22967452f195509260f6a6dd10357fc4ad76b1c0aa5981ac254e
1AWpmg8Rwab9MNkwGNhJ4gd5AVPR4hkNme
```
The above conversion is correct according to this [random site](http://bitcoinvalued.com/tools.php):

![image](https://cloud.githubusercontent.com/assets/1369335/25306691/5c21ecac-2747-11e7-888a-6ddd5d98d0d6.png)

So as far as I can tell, the issue is with blockcypher's decoding.

**Comment by evoskuil** [comment]
WRT validate-tx, the [prevout tx](https://blockchain.info/tx/645d6b547b8ac81fe2a66708f63841aa869a160bd3517da1f78ed82ca2563d83) script is (according to BCI):
```
OP_DUP OP_HASH160 ede6529b2dc4481dd7ef4ea74af77932c788e99d OP_EQUALVERIFY OP_CHECKSIG
```
So the validation error is incorrect, the public key hashes do not match.

**Comment by evoskuil** [comment]
It appears that the web site you are using is not actually just ddcoding the tx but is also populating the result with blockchain data. The appearance of a "value" for the input makes this apparent. So I assume the payment address is derived from the prevout script and not the posted tx's input script.

**Comment by evoskuil** [comment]
The resolution to the issue is to change the input script, creating the signature using the private key of `1Ngu4ZiwmHmG1MF9TcwFcsDAgAhrm9zQcp` and compose the script using its public key.

**Comment by shigeya** [comment]
@evoskuil Good morning. Thank you very mcuh for detail.

**Comment by KShingala** [comment]
I get the same error op_equal_verify2 and I am operating on testnet. Any help would be appreciated.
