### ISSUE TITLE
Stack False when verifying multi-input TX

### ISSUE THREAD

**Issue by NoamResnick** [libbitcoin/libbitcoin-explorer#482]
Following the documented tutorial https://github.com/libbitcoin/libbitcoin-explorer/wiki/How-to-Spend-Bitcoin, I managed to create a multi-input TX, create the endorsements and set them. I used tx-encode (with multiple -i), input-sign with the corresponding private key and script for each input, and input-set -i index with the corresponding endorsement and public key for each input. However the generated TX is invalid as shown by "bx validate-tx" returning "stack false".

**Comment by evoskuil** [comment]
Hi @NoamResnick, the stack result is also a function of what is contained in the previous output scripts.

**Comment by NoamResnick** [comment]
I don't think the issue has to do with the previous scripts. I found out that using the exact same inputs and outputs, but only one input at a time, the generated TX is valid. Something goes wrong when trying to use multiple inputs. Is there any tutorial on how to use the script test case you linked above in a C program or something of the sort? How to link the library etc. Thank you very much for the help!

**Comment by evoskuil** [comment]
Sorry, there are no tutorials for script debugging. Feel free to add one to the wiki if you get a chance! Instructions for building libbitcoin and its test suite are here: https://github.com/libbitcoin/libbitcoin/blob/master/README.md

**Comment by NoamResnick** [comment]
If I ever do manage to debug it I'll submit something. Regardless, thanks for the help and info, BX has really been useful, much appreciated.

**Comment by evoskuil** [comment]
I'd be happy to evaluate a transaction for you if you want to send one to me.

**Comment by NoamResnick** [comment]
Sure. I've gathered most of what I think could be useful to you.



>    `bx tx-encode -i 375939cd007334a6dd9ee45cd371b253193c23c75b4b788211ceeb28fd3807e3:1 -i 375939cd007334a6dd9ee45cd371b253193c23c75b4b788211ceeb28fd3807e3:2 -o 1mijjBgFJCQmNGLhwMpqXzWiCkLyea3c9:149806 -o 15o8c9dVuUdMrAyaw92cx7fe2HPmM52Ayp:17186`

>    `bx input-set -i 0 "[3045022100abf9aac92d12ec8ef6ceece149b9852608167f7789e21d737ab93bbb5176f789022034a67fa35757d93a8d032ecfd82f80c4956d9f110c0655cebaf9eb43f8500e0701] [02be9139837c8172814eaf40f7d9368f90791fe1200d7de0403657af21b83bd84f]" 0100000002e30738fd28ebce1182784b5bc7233c1953b271d35ce49edda6347300cd3959370100000000ffffffffe30738fd28ebce1182784b5bc7233c1953b271d35ce49edda6347300cd3959370200000000ffffffff022e490200000000001976a9140875247094247cf5c49022b7af2010623f0546ab88ac22430000000000001976a9143499fc8f0bd23ebd3d5f450c351304755adad28888ac00000000`

>    `bx input-set -i 1 "[304502210091074ec04b6512b0c354a7d09c7b96800ece2052692019679fbccd79d4666c0302200e5b164d8be6f1d1b2caccb121dd9b6601aa0f61cc5d52f0d5f1eb72d3944f7801] [02b351c374ac112f76bf2ce9903df0f1e27ad97fa28634071c5ddcaeaf854ee50e]" 0100000002e30738fd28ebce1182784b5bc7233c1953b271d35ce49edda6347300cd395937010000006b483045022100abf9aac92d12ec8ef6ceece149b9852608167f7789e21d737ab93bbb5176f789022034a67fa35757d93a8d032ecfd82f80c4956d9f110c0655cebaf9eb43f8500e07012102be9139837c8172814eaf40f7d9368f90791fe1200d7de0403657af21b83bd84fffffffffe30738fd28ebce1182784b5bc7233c1953b271d35ce49edda6347300cd3959370200000000ffffffff022e490200000000001976a9140875247094247cf5c49022b7af2010623f0546ab88ac22430000000000001976a9143499fc8f0bd23ebd3d5f450c351304755adad28888ac00000000`

resulting in the following TX 
>    `0100000002e30738fd28ebce1182784b5bc7233c1953b271d35ce49edda6347300cd395937010000006b483045022100abf9aac92d12ec8ef6ceece149b9852608167f7789e21d737ab93bbb5176f789022034a67fa35757d93a8d032ecfd82f80c4956d9f110c0655cebaf9eb43f8500e07012102be9139837c8172814eaf40f7d9368f90791fe1200d7de0403657af21b83bd84fffffffffe30738fd28ebce1182784b5bc7233c1953b271d35ce49edda6347300cd395937020000006b48304502210091074ec04b6512b0c354a7d09c7b96800ece2052692019679fbccd79d4666c0302200e5b164d8be6f1d1b2caccb121dd9b6601aa0f61cc5d52f0d5f1eb72d3944f78012102b351c374ac112f76bf2ce9903df0f1e27ad97fa28634071c5ddcaeaf854ee50effffffff022e490200000000001976a9140875247094247cf5c49022b7af2010623f0546ab88ac22430000000000001976a9143499fc8f0bd23ebd3d5f450c351304755adad28888ac00000000`

**Comment by evoskuil** [comment]
Thanks, I'll give it a look.

**Comment by evoskuil** [comment]
@NoamResnick The signatures are both invalid. I can see that the endorsement's public keys are correct and that signatures were created with sighash::all. But I cannot verify the remaining parameterization of `input-sign` for each input. This failure would result if any of the 5 remaining parameters are incorrect. It seems possible that you may be failing to specify the index of the input you are signing, although that should only cause the second input signature to be invalid, as it defaults to zero (the first input).

**Comment by evoskuil** [comment]
@NoamResnick I have concluded that you failed to use the `--index` option of the `input-sign` command. Both signatures are valid for the first input.
