### ISSUE TITLE
How to use pipe?

### ISSUE THREAD

**Issue by Napulsnik** [libbitcoin/libbitcoin-explorer#493]
Hello. I try:

bx base58check-decode < addresses.txt

or

cat addresses.txt | bx base58check-decode

but it's not working
What needs to be changed?
I need convert Bitcoin address to Hash160

**Comment by evoskuil** [comment]
Hello, bx operates over set of parameters per call. If you want to decode a set of addresses you must loop over the set.

**Comment by Napulsnik** [comment]
Hi. Please give an example? I have a list of Bitcoin addresses. I need to convert them to Hash160. How to do it?

**Comment by evoskuil** [comment]
It depends on your script environment. I'd recommend posting that question to the related scripting community.

**Comment by thecodefactory** [comment]
It's not clear what you're trying to do.  Maybe this helps (using bash)?

```
$ cat ADDRS
12xoU6RMdpcCRRmBfR4UuBm6dm3Bt4iJd4
1GKVeYP4ZvEpg8nV6TyjX6c4MPzXpriv8H
149WNun4gsbgDKBdVMrmwjS1harmQ3474A
1FGFhAJaguVK2rcB3VXSHoTUXr6XZT8yAE
194zXoLHkrGkUT3r1Hw5b7B2RNFarEdq4J
12dGTV9XG8AfmneombErgC4TmSEUGfkPny
1A2b7X3VYTx8ANPcH9mZutXgQZyDJs2qxs
16umWiaehg9vXbStAzuoze9czQVZHsSWgZ
1PxxDgJW9s1X9DR9RSe7MyNM6fXrSVXnuS

$ for f in $(cat ADDRS); do echo $f | ./bx base58-decode | ./bx ripemd160; done
0b9a1b3242bb0342da378aa70d9828435fd0b4bf
6dfa4c5455300206327f79b1ae435f79f39afe72
6efcae359434b7c726abb3a758d342ae433cf4c5
07b0d15737e2b1c092bf13baed9eacbf0b19d371
ff71144f1466474046029cc4f17d6bb7df8abc4a
a6eee117f67419276f4f890dbbd288e3e2d74280
653c4cbae085eeb980eda195bbc107f6a977ecdc
7274c52d94803fa26f0a73e3c47309712fb1e10f
174ed6c8155186174da4dc1621569b61cb11f777
```

**Comment by thecodefactory** [comment]
Closing due to no response.  @Napulsnik Re-open if needed and additional information can be provided.
