### ISSUE TITLE
fetch-balance spent value is wrong

### ISSUE THREAD

**Issue by selivandex** [libbitcoin/libbitcoin-explorer#495]
Hey

Just checked bitfinex cold wallet address

```bash
root@vs01:~# bx fetch-balance -f json 3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r
```

And got that response

```json
{
    "balance": {
        "address": "3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r",
        "received": "150518407470795",
        "spent": "0"
    }
}
```

Then i've checked it via blockchain.info and that what i got:

```json
{
  "hash160": "7c6775e20e3e938d2d7e9d79ac310108ba501ddb",
  "address": "3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r",
  "n_tx": 2380,
  "total_received": 80211202834326,
  "total_sent": 68269706281955,
  "final_balance": 11941496552371,
  "txs": [
    # transactions goes here ...
  ]
}
```

And total_received is different...

Also what if i installed bitcoin full node – can i use my local node with libbitcoin-explorer?

**Comment by evoskuil** [comment]
If by "bitcoin full node" you mean Core, etc., no - nodes don't index all addresses. You could install and sync BS and connect BX to it using a simple Confucius change.

BS doesn't index unconfined txs, not sure about your blockchain.info query. You can compare results by looking at the output of fetch-history as oppposed to fetch-balance.

**Comment by selivandex** [comment]
@evoskuil Thank you for your response,

But you can check it by yourself https://blockchain.info/address/3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r

Here this address and its balance 119414.96552371 BTC

But BX tells that this address has 1505184.07470795 BTC received and 0 spend. So total_balance = received-spent=1505184.07470795 BTC

Why it's so different?

**Comment by evoskuil** [comment]
The answer should show in fetch-history. I can't check it because I'm traveling.

**Comment by thecodefactory** [comment]
Don't want this to drop off the radar, but this particular address history will take some time to dig into.  I do see the balance discrepancy noted, but do not know the answer off hand.  @selivandex By any chance, do you know of any other addresses without so many transactions that are also off, as it may help reconcile the differences quicker?

**Comment by evoskuil** [comment]
This could be explained by either of the following issues:
https://github.com/libbitcoin/libbitcoin/issues/814
https://github.com/libbitcoin/libbitcoin-database/issues/150

**Comment by evoskuil** [comment]
This should be resolved by https://github.com/libbitcoin/libbitcoin-database/pull/160

**Comment by evoskuil** [comment]
Closing as resolved. Please reopen if not resolved against updated server. It may take up to a week before community servers are updated.
