### ISSUE TITLE
Add electrum mnemonic support

### ISSUE THREAD

**Issue by thecodefactory** [libbitcoin/libbitcoin-explorer#499]
Implement support for electrum mnemonic and seeds with additional bx commands *electrum-to-seed* and *electrum-new*.

**Comment by skaht** [comment]
It is worth noting that Electrum seeds are fully invertible unlike BIP 39 technology.

**Comment by thecodefactory** [comment]
@skaht @evoskuil  I'm still trying to determine if we need to support electrum 1.x mnemonics (which libbitcoin implemented in the past but deprecated in v2 and removed in v3 I believe), or the newer electrum 2.x mnemonics, which are somewhat similar to BIP39, but include a version prefix.

If the former, we can just revive the previously existing electrum mnemonic code, dust it off and call it a day.  If the latter, I spent some time working on that and have working code in a private libbitcoin branch, but need some feedback on how best to expose it from bx.  Either way, I think we'll be covered, but we need to get to the bottom of what's really needed here.  Perhaps we need to support both versions?  I don't have any clue how much use either version may have in the wild.

**Comment by evoskuil** [comment]
I see no reason to support older electrum mnemonics as IIRC electrum can upgrade them.

**Comment by evoskuil** [comment]
WRT seeding, the implementation should only accept a seed as a parameter and should follow the conventions of existing commands that use seeds.

**Comment by thecodefactory** [comment]
Update on this (as someone asked on the IRC channel):

The draft implementation I have is here:

https://github.com/thecodefactory/libbitcoin/tree/electrum-mnemonic

I need to do a once over, as it's been a while since I looked at this.  I also need to clean up the draft explorer support.  Pull requests coming sometime after that.
