### ISSUE TITLE
wrong block height

### ISSUE THREAD

**Issue by SARSAM** [libbitcoin/libbitcoin-explorer#510]
Querying block height using bx command returns obviously wrong out put : 
`$ ./bx-linux-x64-qrcode fetch-height -c ./bx.cfg`
OUTPUT : `11110`

Also this is my settings output : 
`$ ./bx-linux-x64-qrcode settings -c ./bx.cfg`
`
settings
{
    network
    {
        channel_handshake_seconds 30
        connect_retries 0
        connect_timeout_seconds 5
        debug_file debug.log
        error_file error.log
        hosts_file hosts.cache
        identifier 118034699
        seeds seed.bitnodes.io:8333,seed.bitcoinstats.com:8333,seed.bitcoin.sipa.be:8333,dnsseed.bluematt.me:8333,seed.bitcoin.jonasschnelli.ch:8333,dnsseed.bitcoin.dashjr.org:8333
    }
    server
    {
        client_private_key 0000000000000000000000000000000000000000
        connect_retries 0
        connect_timeout_seconds 5
        server_public_key 0000000000000000000000000000000000000000
        socks_proxy 0.0.0.0
        url tcp://testnet.libbitcoin.net:19091
    }
    wallet
    {
        hd_public_version 70617039
        hd_secret_version 70615956
        pay_to_public_key_hash_version 111
        pay_to_script_hash_version 196
        transaction_version 1
        wif_version 239
    }
}
`

Are the servers somehow behind ? or is there something wrong with my configuration ?

**Comment by evoskuil** [comment]
The default community testnet server should be at whatever height you are seeing. Is it increasing.

**Comment by SARSAM** [comment]
nope It's stuck at `11110`

**Comment by evoskuil** [comment]
@thecodefactory ?

**Comment by evoskuil** [comment]
You can change the URL to [another server](https://github.com/libbitcoin/libbitcoin-server/wiki/Community-Servers) to confirm that this is the server height, as opposed to a problem with the bx build.

**Comment by SARSAM** [comment]
thank you very much. this was what I've been looking for
