### ISSUE TITLE
testnet.libbitcoin.net:19091 connection timed out

### ISSUE THREAD

**Issue by marriva** [libbitcoin/libbitcoin-explorer#512]
$ bx fetch-height tcp://testnet.libbitcoin.net:19091
connection timed out

wtf?

$ bx fetch-height tcp://mainnet.libbitcoin.net:9091
494965

Testnet server has gone? :(

**Comment by evoskuil** [comment]
Host [testnet3.libbitcoin.net](https://github.com/libbitcoin/libbitcoin-server/wiki/Community-Servers#testnet3) is operational, however the non-secure port has been disabled for reasons not known to me. So this wasn't connecting:
```
$ bx fetch-height tcp://testnet3.libbitcoin.net:19091
```
However this was:
```
$ bx fetch-height tcp://testnet3.libbitcoin.net:19081 "ZW4K2g{E>*a@n>NqZ<VeI^2ANqw.7Ub<?>UgSiNq"
```
At the same time there was a power failure that brought down both testnet1 and testnet2. This left us with no community testnet server for about a day. The [testnet1.libbitcoin.net](https://github.com/libbitcoin/libbitcoin-server/wiki/Community-Servers#testnet1) server has recently been resynced, and I've just moved DNS for testnet.libbitcoin.net (default for bx) to that server to resolve this issue. So this now works (you may need to flush dns):
```
$ bx fetch-height tcp://testnet.libbitcoin.net:19091
```
Note that:
1. These servers are maintained by volunteers (not me).
2. The bx server configuration is [configurable](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Server-Settings), there is no automatic failover, but there are generally multiple [community servers](https://github.com/libbitcoin/libbitcoin-server/wiki/Community-Servers) to choose from.
3. You are free to run your own server, and to publish it as a community server.
4. If server status is important to you I would recommend that you monitor the libbitcoin slack and/or freenode IRC channel. Maintainers have posted status on these specific issues over the past couple of days.
5. You are generally likely to get better support from open source volunteers if you don't start your issue with *what the fuck*.

**Comment by evoskuil** [comment]
Resolved.
