### ISSUE TITLE
Error in retrieving balance?

### ISSUE THREAD

**Issue by charlesrwest** [libbitcoin/libbitcoin-explorer#548]
Hello!

I am just getting started with libbitcoin-explorer and ran into an issue (which I hope is a simple mistake on my part!).

When I run:
bx fetch-balance 1ECQ2vYffShxJFwQnbamxAF54NUBp1ADUb

I get:
balance
{
    address 1ECQ2vYffShxJFwQnbamxAF54NUBp1ADUb
    received 18446744073709551615
    spent 18446744073709551615
}

Despite blockchain.info showing 0.00410831 BTC with over 36 confirmations and bx fetch-height showing the same blockchain height as that site:
https://blockchain.info/address/1ECQ2vYffShxJFwQnbamxAF54NUBp1ADUb

If I may ask, do you know why I am getting an incorrect balance?  Is there something I need to configure?

**Comment by evoskuil** [comment]
Are there segwit payments?

**Comment by charlesrwest** [comment]
Thank you.  Checking out the v3.5.0 tag and recompiling solved the issue.
