### ISSUE TITLE
Need help  for installing Libbitcoin explorer !

### ISSUE THREAD

**Issue by mddia** [libbitcoin/libbitcoin-explorer#554]
After installing explorer, When I run any BX command I am get his error :

`bx: error while loading shared libraries: libbitcoin-explorer.so.0: cannot open shared object file: No such file or directory
`

**Comment by evoskuil** [comment]
You probably have an incompatible boost build installed. Try rebuilding with --prefix, --build-boost and no sudo.

**Comment by mddia** [comment]
It was really a problem related to boost. Removing & reinstalling  it resolved the problem.
Thank you @evoskuil
