### ISSUE TITLE
Initiation of time locked transaction

### ISSUE THREAD

**Issue by NikleshPhabiani** [libbitcoin/libbitcoin-explorer#555]
Hi,

I initiated a time locked transaction to be considered for incorporation into the blockchain after block number 517820 got crossed. This was done when block number 517795 had got mined. I was trying to transfer from one multisig wallet to another. I had even changed the sequence number because if only locktime is put in keeping the sequence number as the default value (0xFFFFFFFF), the locktime won't be effective. So my TRANSACTION HASH: INDEX: SEQUENCE NUMBER was 20c4266b807284702207046bfe7b2c37916d219d8423cdcf5574afa8066b2c5f:0:7. Also, I have put the output amount as 380871 satoshis out of 396687 satoshis leaving 15816 satoshis as the fees for the miner. But, the transaction has not yet become a part of the block. Is there something that I am not doing or doing incorrectly? Kindly guide me on the same.

On doing '**validate-tx**' and '**send-tx**' while initiating the transaction, I received an output message stating '**transaction is currently non-final for next block**', which looks like a legitimate one.

After waiting for a couple of hours after block 517820 had reached, I again tried the aforementioned commands and then received an output message stating '**op_equal_verify2**'.

On doing **bx tx-decode**, the output is:
```js
transaction
{
    hash 7987e90f01ea168ac5cfed10f967016e645b66fdeb5ff917ae352f0e0eefd20f
    inputs
    {
        input
        {
            address_hash 676e8e5386882438a476db0aa79d36d92b7b1df7
            previous_output
            {
                hash 20c4266b807284702207046bfe7b2c37916d219d8423cdcf5574afa8066b2c5f
                index 0
            }
            script "zero [304402201c80510964ee74ec261be7b28a016ad25b042cb6248bfa36307579db9acf1339022007ea1c8fbf585bb2c58189440489a5a748a8a730be2d65a8f9ac5f9e88d0456501] [3045022100df6176458a64fb708a01a1f92d79cefa79fe93c10a97e3a93dd7d0baed1f0aa90220291d529d9c5db36947302d265370626886800a1813ed5d233f32f1a476c92e5d01] [522103b967d2f85c1b6de9523607935493ae5625ad9d4f31716a4dc21a3c714382d9872102c7ba86688d6cc4b2cb48a11326c7c275b8e51c70db97c50f0af03e78fad35ed721026c78f77f24aac043bd805587aa4f87c317b64ece1aab3b6dae270f6410f6c39253ae]"
            sequence 7
        }
    }
    lock_time 517820
    outputs
    {
        output
        {
            address_hash 1e47961220a46f0d9db18aac2963ff0767ccdda4
            script "dup hash160 [1e47961220a46f0d9db18aac2963ff0767ccdda4] equalverify checksig"
            value 380871
        }
    }
    version 1
} 
```

**Comment by evoskuil** [comment]
The previous output is the (only) output of this tx:
```sh
$bx fetch-tx 20c4266b807284702207046bfe7b2c37916d219d8423cdcf5574afa8066b2c5f
transaction
{
    hash 20c4266b807284702207046bfe7b2c37916d219d8423cdcf5574afa8066b2c5f
    inputs
    {
        input
        {
            address_hash 90c17018ff5661b96db251f45e8b622f4b8e57ea
            previous_output
            {
                hash 94544cc4b2c38762f0caee5451aaccb6fe16715a52a0783d347560d4aa13524a
                index 1
            }
            script "[3045022100bae97d75d2750487631cc32f083ab1383ad2fb627b1a2d5e7677519cbc26fba50220280a50ff64abeae666f053a697581ae7b12e16b2386ba4a2bfe57eb3f47864b101] [03b967d2f85c1b6de9523607935493ae5625ad9d4f31716a4dc21a3c714382d987]"
            sequence 4294967295
        }
    }
    lock_time 0
    outputs
    {
        output
        {
            address_hash 90c17018ff5661b96db251f45e8b622f4b8e57ea
            script "dup hash160 [90c17018ff5661b96db251f45e8b622f4b8e57ea] equalverify checksig"
            value 396687
        }
    }
    version 1
}
```
So you are attempting to spend a P2PKH output script with a bare multisig input script. A failure of the `equalverify` operation is expected.

**Comment by evoskuil** [comment]
Closing as resolve, please reopen if you suspect a problem. For general questions on transaction construction you might try the #libbitcoin IRC or slack.
