### ISSUE TITLE
Issue with spending from Multi-Signature wallet?

### ISSUE THREAD

**Issue by charlesrwest** [libbitcoin/libbitcoin-explorer#556]
Hopefully the last question for a while:

I've constructed a multi-sig wallet with the following command and funded it:
bx script-to-address "2 [03b967d2f85c1b6de9523607935493ae5625ad9d4f31716a4dc21a3c714382d987] [02c7ba86688d6cc4b2cb48a11326c7c275b8e51c70db97c50f0af03e78fad35ed7] 2 checkmultisig" > twoOfTwoWallet.bitcoin_address

I am then trying to move the money out of the wallet using the two keys with the following commands:
3. Encode the transaction:
bx tx-encode -i b27b22e132dae74689e7d21ced759dde8837ffa62797c250881821aa84a41bd8:0 -o 1ECQ2vYffShxJFwQnbamxAF54NUBp1ADUb:77623 -o 13m72eqE5erf4MLYt7u14EUQCCdTWdo6k9:162318 > noDispute.transaction

4. Make first key's endorsement
bx input-sign privateKeyShouldNotBePostedToGitHub1 "2 [03b967d2f85c1b6de9523607935493ae5625ad9d4f31716a4dc21a3c714382d987] [02c7ba86688d6cc4b2cb48a11326c7c275b8e51c70db97c50f0af03e78fad35ed7] 2 checkmultisig" < noDispute.transaction > noDisputeWallet1Endorsement.endorsement

5. Make second key's endorsement
bx input-sign privateKeyShouldNotBePostedToGitHub2 "2 [03b967d2f85c1b6de9523607935493ae5625ad9d4f31716a4dc21a3c714382d987] [02c7ba86688d6cc4b2cb48a11326c7c275b8e51c70db97c50f0af03e78fad35ed7] 2 checkmultisig" < noDispute.transaction > noDisputeWallet2Endorsement.endorsement

6. Encode the endorsement script to be included in the transaction
bx script-encode "2 [03b967d2f85c1b6de9523607935493ae5625ad9d4f31716a4dc21a3c714382d987] [02c7ba86688d6cc4b2cb48a11326c7c275b8e51c70db97c50f0af03e78fad35ed7] 2 checkmultisig" > noDisputeUnlockingScript.encoded_script

7. Add the endorsement script to the transaction
bx input-set "zero  [wallet1Endorsement] [wallet2Endorsement] [encodedUnlockingScript]" < noDispute.transaction > noDispute.signed_transaction

which in practice looks like:

bx input-set "zero  [3045022100b24ac3d3c5d8e7bf0884cd126afffef0a00128257410fbbb41323f715a96fbb902202e62124199f30667b5c9d35c80ffeb06ebbbe418bc69583d4b62b530aeb0b29081] [3044022078836df89b8265491ae21117394ec4c1ac2297a8ae147e50879cbb8b8fad10af02200ed925b0df17c127848b8f2b5289eb1508bfd81b7f3a77574cf9be0e43d0c55e81] [522103b967d2f85c1b6de9523607935493ae5625ad9d4f31716a4dc21a3c714382d9872102c7ba86688d6cc4b2cb48a11326c7c275b8e51c70db97c50f0af03e78fad35ed752ae]" < noDispute.transaction > noDispute.signed_transaction

However, when I try to validate the transaction with:
bx validate-tx < noDispute.signed_transaction

I get:
stack false

If I may ask, do you have any idea where I might be going wrong?

**Comment by evoskuil** [comment]
It would be easier if you just showed the tx that is failing to validate.

**Comment by charlesrwest** [comment]
My apologies.  I think I made a typo, despite checking it several times.  Thank you for your help.
