### ISSUE TITLE
possible bug in input-sign, where signature returned is 71, not 72 bytes? 

### ISSUE THREAD

**Issue by annjieching** [libbitcoin/libbitcoin-explorer#557]
Correct example -- returns 72 byte signature (notice 0x45, implying full sequence of signature is 69 bytes): 
```
bx input-sign 16e56830f5a6e967af92a2a49bef934681e32bbf3b0b6e5e99310edc44d7a890 "if 2 [02e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b] [0281cd7c6b17e5a62786b2f1f4fa0f71126c39540129e7692dabde56d601c1fc3d] 2 checkmultisig else [010040] checksequenceverify drop [02e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b] checksig endif" 0200000001bc766c606fabeea703095fabcf951acef723caa0ec3a0f786dfeaa5f4f5816a50000000000ffffffff0180010b27010000001976a914576aca4e70b6b75cc7a9fc05d7e0da13cc21ba7588ac00000000

3045022100cfea35a4c02ef489d7f68b1850db40f9bbc7e8c69775e0240f518ae6767b2904022003a62cb473d14a83a4b327c3f9b9d23c7969e6990d4da5ba4e6a9d9bde33be3c01

```

Incorrect example -- returns 71 byte signature instead of 72 bytes, notice 0x44: 
```
bx input-sign 13ed665bc90d7c958930e61abc232d981e2da8349bbfa778a441f408968b2b38 "if 2 [02e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b] [0281cd7c6b17e5a62786b2f1f4fa0f71126c39540129e7692dabde56d601c1fc3d] 2 checkmultisig else [010040] checksequenceverify drop [02e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b] checksig endif" 0200000001bc766c606fabeea703095fabcf951acef723caa0ec3a0f786dfeaa5f4f5816a50000000000ffffffff0180010b27010000001976a914576aca4e70b6b75cc7a9fc05d7e0da13cc21ba7588ac00000000

304402205278c38d515218fbbfa0bfcfeb6207503f7ff851b20fa083538a54fc75539eb5022030ce4205f041392ce54b9aa389092affd93baafc185eea71d31d0457dbeb44ab01
```

grateful if someone could check and replicate this

**Comment by evoskuil** [comment]
Given that 0x44 is one less than 0x45, and 71 is one less than 72, I don't see the problem.

**Comment by annjieching** [comment]
Thank you :) 

Do you mind helping me a little further? 
So I used the two signatures above to construct an unlocking script for my P2SH transaction. Using script-decode works perfectly: 
```
bx script-decode "00483045022100cfea35a4c02ef489d7f68b1850db40f9bbc7e8c69775e0240f518ae6767b2904022003a62cb473d14a83a4b327c3f9b9d23c7969e6990d4da5ba4e6a9d9bde33be3c0147304402205278c38d515218fbbfa0bfcfeb6207503f7ff851b20fa083538a54fc75539eb5022030ce4205f041392ce54b9aa389092affd93baafc185eea71d31d0457dbeb44ab015163522102e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b210281cd7c6b17e5a62786b2f1f4fa0f71126c39540129e7692dabde56d601c1fc3d52ae6703010040b2752102e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736bac68"

zero [3045022100cfea35a4c02ef489d7f68b1850db40f9bbc7e8c69775e0240f518ae6767b2904022003a62cb473d14a83a4b327c3f9b9d23c7969e6990d4da5ba4e6a9d9bde33be3c01] [304402205278c38d515218fbbfa0bfcfeb6207503f7ff851b20fa083538a54fc75539eb5022030ce4205f041392ce54b9aa389092affd93baafc185eea71d31d0457dbeb44ab01] 1 if 2 [02e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b] [0281cd7c6b17e5a62786b2f1f4fa0f71126c39540129e7692dabde56d601c1fc3d] 2 checkmultisig else [010040] checksequenceverify drop [02e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b] checksig endif
```
 
But I'm having a problem with tx-decode for the following (parsed), says my argument for --TRANSACTION is invalid (parsed after the raw hex). 
Would you please help me understand what's wrong here?: 

```
0200000001bc766c606fabeea703095fabcf951acef723caa0ec3a0f786dfeaa5f4f5816a500000000060100483045022100cfea35a4c02ef489d7f68b1850db40f9bbc7e8c69775e0240f518ae6767b2904022003a62cb473d14a83a4b327c3f9b9d23c7969e6990d4da5ba4e6a9d9bde33be3c0147304402205278c38d515218fbbfa0bfcfeb6207503f7ff851b20fa083538a54fc75539eb5022030ce4205f041392ce54b9aa389092affd93baafc185eea71d31d0457dbeb44ab015163522102e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b210281cd7c6b17e5a62786b2f1f4fa0f71126c39540129e7692dabde56d601c1fc3d52ae6703010040b2752102e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736bac68ffffffff0180010b27010000001976a914576aca4e70b6b75cc7a9fc05d7e0da13cc21ba7588ac00000000

02000000
01
bc766c606fabeea703095fabcf951acef723caa0ec3a0f786dfeaa5f4f5816a5
00000000
0601 (**LE hex for 262 bytes, changing to 0106 decodes the tx, but it's all wrong. I suspect there's something here..?**) 
00
48
3045022100cfea35a4c02ef489d7f68b1850db40f9bbc7e8c69775e0240f518ae6767b2904022003a62cb473d14a83a4b327c3f9b9d23c7969e6990d4da5ba4e6a9d9bde33be3c01
47
304402205278c38d515218fbbfa0bfcfeb6207503f7ff851b20fa083538a54fc75539eb5022030ce4205f041392ce54b9aa389092affd93baafc185eea71d31d0457dbeb44ab01
51
63522102e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b210281cd7c6b17e5a62786b2f1f4fa0f71126c39540129e7692dabde56d601c1fc3d52ae6703010040b2752102e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736bac68
ffffffff (changing this to 7fffffff doesn't work either) 
01 (changing this to 02 doesn't help either) 
80010b2701000000
1976a914576aca4e70b6b75cc7a9fc05d7e0da13cc21ba7588ac
00000000
```

**Comment by evoskuil** [comment]
How did you construct the binary transaction?

**Comment by evoskuil** [comment]
Closing this as the title issue is resolved. If you suspect a problem with a command please report. Otherwise you might try the #libbitcoin IRC for general help.

**Comment by annjieching** [comment]
I used bitcoin-cli: 
```
bitcoin-cli -regtest createrawtransaction '''[{"txid":"a516584f5faafe6d780f3aeca0ca23f7ce1a95cfab5f0903a7eeab6f606c76bc", "vout":0}]''' '''{"'moVB1fGQx7EpH3WB3KjzZ1LZPbNHakk5rE'":49.5}'''
```

and then I manually parsed the output, adding by hand where I wanted my scripts to go because there is no automated way (I plan to write one): 
```
0200000001bc766c606fabeea703095fabcf951acef723caa0ec3a0f786dfeaa5f4f5816a500000000
<insert 0601>
00 ==> <insert unlocking + redeem script, replacing '00' with my script that also has '00', accounting for the bug> 
ffffffff0180010b27010000001976a914576aca4e70b6b75cc7a9fc05d7e0da13cc21ba7588ac00000000
```

Is this the right approach? 
Thank you! 

ps. just saw you closed the issue. I'll post it on the IRC if you don't get a chance to look at this. thanks :)

**Comment by evoskuil** [comment]
> there is no automated way (I plan to write one)

The automated way is `bx tx-encode`.

**Comment by annjieching** [comment]
hmm... I meant signing the transaction with two separate private keys and then appending them in such a way for the conditional script to work.

**Comment by evoskuil** [comment]
See [bx input-sign](https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-input-sign) and [bx input-set](https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-input-set).

**Comment by annjieching** [comment]
Thank you @evoskuil! That leads me to another question. With input-set, how can you push the entire redeem script and not its individual components? is that possible? 

e.g.  
bx input-set "<signature part> <redeem script>" <txhex>
where <redeem script> is "if ..... checksig endif"

The end result would include for example, 0x4c__ before the contents of the script, to indicate pushing the number of bytes of the redeem script onto the stack. 
 
I tried putting [] around the entire redeem script to indicate it is a token but got  ''' '--ENDORSEMENT_SCRIPT' is invalid'''

'''bx input-set "zero [3045022100cfea35a4c02ef489d7f68b1850db40f9bbc7e8c69775e0240f518ae6767b2904022003a62cb473d14a83a4b327c3f9b9d23c7969e6990d4da5ba4e6a9d9bde33be3c01] zero **WRONG SHOULD HAVE A PUSH FOR REDEEM SCRIPT HERE!!!? ** if 2 [02e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b] [0281cd7c6b17e5a62786b2f1f4fa0f71126c39540129e7692dabde56d601c1fc3d] 2 checkmultisig else [010040] checksequenceverify drop [02e2887490bd940ef9122575269db1e4d91eeacc2fd85f61b06e443ddd6414736b] checksig endif" 0200000001bc766c606fabeea703095fabcf951acef723caa0ec3a0f786dfeaa5f4f5816a50000000000ffffffff0180010b27010000001976a914576aca4e70b6b75cc7a9fc05d7e0da13cc21ba7588ac00000000
'''
