### ISSUE TITLE
Build instructions incomplete for Ubuntu 16.04/17.10

### ISSUE THREAD

**Issue by haarts** [libbitcoin/libbitcoin-explorer#559]
The `install.sh` can't find the ZMQ library even thought it is installed (`apt install libzmq5`).
 Turns out the `libzmq.pc` is missing. This file is provided by the `libzmq3-dev` package. Yes, that is right, 3. Not 5. Both DO provide ZMQ version 4.2.1.

**Comment by evoskuil** [comment]
Yes, the dev package is required.

**Comment by evoskuil** [comment]
PR to update readme?

**Comment by haarts** [comment]
Will do. At latest next Monday!

**Comment by evoskuil** [comment]
@pmienk

**Comment by haarts** [comment]
Resolved in 43f1d08701b028ea1d425118fd46597e4be06c24

**Comment by evoskuil** [comment]
Thanks for reporting!
