### ISSUE TITLE
Using input-set to push entire redeem script in P2SH-- possible? 

### ISSUE THREAD

**Issue by annjieching** [libbitcoin/libbitcoin-explorer#562]
With input-set, how can you push the entire redeem script and not its individual components? is that possible?

e.g.
bx input-set " " 
where is "if ..... checksig endif"

The end result would include for example, 0x4c__ before the contents of the script, to indicate pushing the number of bytes of the redeem script onto the stack.

I tried putting [] around the entire redeem script to indicate it is a token but got ''' '--ENDORSEMENT_SCRIPT' is invalid'''

```
bx input-set "zero [sig1] zero **WRONG SHOULD 
HAVE A PUSH FOR REDEEM SCRIPT HERE!!!? ** if 2 
[pubkey1] [pubkey2] 2 checkmultisig else [010040] 
checksequenceverify drop [pubkey1] checksig endif" 
0200000001bc766c606fabeea703095fabcf951acef723caa0ec3a0f786dfeaa5f4f5816a50000000000ffffffff0180010b27010000001976a914576aca4e70b6b75cc7a9fc05d7e0da13cc21ba7588ac00000000
```

**Comment by evoskuil** [comment]
A P2SH embedded script is data. It must be encoded using “bx script-encode” and then passed to “bx input-set” as a data token (wrapped in []) in the script parameter.

**Comment by annjieching** [comment]
Got it. Thank you!
