### ISSUE TITLE
op_equal_verify2 on validate-tx and send-tx

### ISSUE THREAD

**Issue by KShingala** [libbitcoin/libbitcoin-explorer#601]
Hello,

I run into a situation where I get op_equal_verify2 message on my transactions. I am operating on the testnet and attempting an op_return transaction. This problem persists even if I create a new address and key. Attached is a screen shot of the decode transaction and the error on send-tx.
![send_op_equal_verify2](https://user-images.githubusercontent.com/18003825/46548452-6995a380-c8cf-11e8-83cd-dff1714d9f98.png)
tx.

**Comment by thecodefactory** [comment]
@KShingala Which version are you using, and what is the input that you are using (it's not clear from the picture)?

**Comment by KShingala** [comment]
I am using version 3.2.0. I downloaded the binary on a Ubuntu system. The signed transaction bytes are
`010000000164f8f8bfe39093b833a6b41811854954bc07670e88c8c2c17cdc9838dd2d3e900000000048473044022059080a14cb4a2b2d50d3b41649c354484382f412a5e19aeab6e760ca42a57a2902205509aebd855c908b9a4eb70f3e988518b235f978d3648dbee08e0bed9bed949d01ffffffff0210980200000000001976a91496ee2ccb31d6e5cfc635942c0fcbd52df31824bf88ac18000000000000000b6a09596573202d2033342100000000 `

**Comment by KShingala** [comment]
I am stalled on this. I get this message with a simple single input single out messages as well.

**Comment by KShingala** [comment]
I received help on this. It was rightly pointed out that my input script was missing the public address. So, this issue is invalid.
