### ISSUE TITLE
bx ec-to-public 0000111122223333444455556666777788889999aaaabbbbccccddddeeeeffff failed

### ISSUE THREAD

**Issue by woshidama323** [libbitcoin/libbitcoin-explorer#603]
src/secp256k1.c:300: test condition failed: secp256k1_ecmult_gen_context_is_built(&ctx->ecmult_gen_ctx)

**Comment by thecodefactory** [comment]
Can you provide some more information?  I get the following result from both version3 and master builds.

```
$ bx ec-to-public 0000111122223333444455556666777788889999aaaabbbbccccddddeeeeffff
020d47568a5e517067a2836c3823fbc58169a7662bfae934a4d41da3e23c98d816
```

**Comment by thecodefactory** [comment]
Closed due to inactivity.  @woshidama323 Re-open if you have any information about this.
