### ISSUE TITLE
حل مشکل ساخت ادرس ها

### ISSUE THREAD

**Issue by matinbeigi99** [libbitcoin/libbitcoin-explorer#624]
این سورس یک باگ داره ، دوستانی که به مشکل خوردند ، با ایدی زیر در تماس باشند.
Telegram : @MatinBeigi

**Comment by evoskuil** [comment]
Thanks, English preferred. Google translate:

Title: 
Solve the problem of building addresses

Content:
This source has a bug, friends who have trouble contact with the following iDis.

We need more information than this.

**Comment by matinbeigi99** [comment]
Difficult to build bitcoin address

This script has problems.
Contact idTelegram below to troubleshoot.
@matinbeigi

**Comment by thecodefactory** [comment]
@matinbeigi99 More details required. No information has been provided.

**Comment by m4tinbeigi** [comment]
> این سورس یک باگ داره ، دوستانی که به مشکل خوردند ، با ایدی زیر در تماس باشند. Telegram : @matinbeigi

ID Telegram: @M4tinBeigi

**Comment by evoskuil** [comment]
Translation: 
"This source has a bug, friends who have problems, contact the following ID."
This is spam.
