### ISSUE TITLE
bx: command not found

### ISSUE THREAD

**Issue by WesNz** [libbitcoin/libbitcoin-explorer#625]
Any idea whats going on?

Install didnt throw any errors so assuming it installed fine.
OS : ubuntu 16.04.
manually install...not the auto install.

 CXXLD    test/libbitcoin-explorer-test
make[1]: Leaving directory '/home/purple/Desktop/build-libbitcoin-explorer/libbitcoin-explorer'
make  check-TESTS
make[1]: Entering directory '/home/purple/Desktop/build-libbitcoin-explorer/libbitcoin-explorer'
make[2]: Entering directory '/home/purple/Desktop/build-libbitcoin-explorer/libbitcoin-explorer'
PASS: libbitcoin-explorer-test_runner.sh
============================================================================
Testsuite summary for libbitcoin-explorer 3.4.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[2]: Leaving directory '/home/purple/Desktop/build-libbitcoin-explorer/libbitcoin-explorer'
make[1]: Leaving directory '/home/purple/Desktop/build-libbitcoin-explorer/libbitcoin-explorer'
Running 506 test cases...
Platform: linux
Compiler: GNU C++ version 5.4.0 20160609
STL     : GNU libstdc++ version 20160609
Boost   : 1.62.0

real    31m26.284s
user    125m39.624s
sys     11m53.860s

purple@ubuntu:/home/me/myprefix$ echo "skin join dog sponsor camera puppy ritual diagram arrow poverty boy elbow" | bx mnemonic-to-seed | bx hd-new | bx hd-private -d -i 0 | bx hd-private -i 0 | bx hd-private -i 0 | bx hd-to-ec | sed 's/$/01/' | bx base58check-encode -v 128
bx: command not found
bx: command not found
bx: command not found
bx: command not found
bx: command not found
bx: command not found
bx: command not found

**Comment by evoskuil** [comment]
./bx

**Comment by WesNz** [comment]
./bx
-bash: ./bx: No such file or directory
     
Am i supposed to be in a certain directory?

**Comment by evoskuil** [comment]
Yes, sorry, you also need to be in the context of the directory into which bx is built. It’s a subdirectory of the prefix dir.

**Comment by WesNz** [comment]
ah thanks!    works now

  @ubuntu:/home/me/myprefix/bin$

**Comment by Jack0Fu** [comment]
solved my problem. thanks for your sharing.

**Comment by MountainMan87119** [comment]
Way outta my comfort zone, took a week, but got the client stack built.  One at a time.
[CrankyBadger@bryanthemercifullista1729 bin]# ./bx seed | ./bx ec-new | ./bx ec-to-public | ./bx ec-to-address
1NTCRLhDVH1BH51vPucTCCSFbv1KvGch6D
THX!!!
