### ISSUE TITLE
Feature Request: `bx input-sign` should take the private key on stdin, not the tx

### ISSUE THREAD

**Issue by abliss** [libbitcoin/libbitcoin-explorer#629]
Hi, thanks for this awesome tool! I have but one quibble.

According to https://github.com/libbitcoin/libbitcoin-explorer/wiki/How-to-Spend-Bitcoin and its own help text, `bx input-sign` requires the private key on the command-line, but can optionally take the tx on stdin.

However, the private key is much more sensitive than the raw transaction. Putting it as a command-line argument risks exposing it to the process table, to your shell history, etc. It would be better if it could come on stdin and the tx was required to be positional.

**Comment by evoskuil** [comment]
Thanks for the input. We assume that if the computer is compromised you are at the same risk. It’s not about security, it’s about user interface, specifically composability.

**Comment by skaht** [comment]
What is to stop an input-sign from being performed on TX on offline on an air gapped computer?

**Comment by skaht** [comment]
What is to stop an input-sign from being performed on a TX on an offline air gapped computer?

**Comment by evoskuil** [comment]
Note also that there are many commands that manipulate secrets. The values cannot be hidden securely via stdin/stdout. BX exists primarily as an educational tool and demonstration of library features and their integration. The libraries themselves are available for custom user interface development, including the explorer library. The command line UX is a very thin layer over explorer.

**Comment by abliss** [comment]
Thanks for the quick reply. Just a few clarifications:

1. I understand and really appreciate the composability of `bx`. This
change would not decrease composability at all; when a command needs 2 or
more parameters (like `input-sign`) and you only have one stdin, you have
to choose which argument is privileged for composability, while the rest go
in args (Or, with more work, you could let the user choose by e.g.
specifying `-` as a special argument to mean stdin). I'm trying to make the
case that `ec_private_key` should be chosen as the default stdin arg over
the `tx`.

2. It's not necessary for the computer to be 'compromised' for this to be a
relevant risk. Many consumer-grade multi-user linux systems come with
default settings that expose you here. E.g. allowing any user to run `ps
axf` and see the arguments to every running process. Or persisting
command-line arguments to disk in the form of a `~/.bash_history` which a
novice user may not know needs to be scrubbed. See e.g.
https://www.netmeister.org/blog/passing-passwords.html for more on this.
(Not everyone has access to, or the ability to manage, an air-gapped secure
single-user system. So should we throw up our hands and say those people
should not even try to use `bx`? Or should we adopt a "defense in depth"
posture and try to choose reasonable defaults that are, wherever practical,
more secure than the alternatives?)

3. I also understand and appreciate that `bx` is mostly for educational
value. And it is well-suited to educate users, not just about bitcoin, but
about open-source command-line utilities as well. For `bx` is, in almost
every, way a paragon of good design, good documentation, good code, and
good project management. So here is your chance to make it even more
perfect, through showing by example to users that sensitive arguments
should be taken on stdin instead of in the args list. :)

>
>

**Comment by thecodefactory** [comment]
> So here is your chance to make it even more
perfect, through showing by example to users that sensitive arguments
should be taken on stdin instead of in the args list. :)

@abliss Thanks!  Perhaps you mean, this is *your* chance (PRs welcome) :)

**Comment by evoskuil** [comment]
Regarding composibility I’m referring to ease of composibility and the patterns we try to apply consistently. We do our best to limit command line arguments to smaller values such that typing is reduced and scripts are more readable. The objective then is to pipe larger composed objects, especially transactions. To the extent that a variable can be used to store the tx, minimizing these issues, the same can be done with secrets to eliminate the security concern you have raised.

We also have to look at consistency of both security assumptions and parameterization conventions. We have a lot of commands, and not only do we endeavor to pipe larger inputs, but we also have secrets (and privacy aspects) exposed as command line arguments on many of them. Changing this one command would reduce this consistency in these two ways.

Finally, we the bar for breaking compatibility is high, so the reason must be compelling. The issue raised, in light of above considerations, does not in my opinion reach that bar.
