### ISSUE TITLE
Master: OSX homebrew automake 1.16.1_1 dependency

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-explorer#630]
FYSA - The following install.sh command line build failed within the secp256k1.  Upgrading **automake** from **1.16.1** to **1.16.1_1** updated the automake's /Users/Scott/usr2/local/bin/aclocal file.

% ./install.sh --disable-shared --build-icu --build-zlib --build-png --build-qrencode --build-boost --build-zmq --build-dir=/Users/Scott/Projects/LibBitcoin/libbitcoin-explorer/build4 --prefix=/Users/Scott/Projects/LibBitcoin/libbitcoin-explorer/build4/core

```
********************** Download libbitcoin/secp256k1/version5 **********************

Cloning into 'secp256k1'...
remote: Enumerating objects: 183, done.
remote: Counting objects: 100% (183/183), done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 183 (delta 52), reused 105 (delta 43), pack-reused 0
Receiving objects: 100% (183/183), 205.30 KiB | 203.00 KiB/s, done.
Resolving deltas: 100% (52/52), done.
Can't locate Automake/Config.pm in @INC (you may need to install the Automake::Config module) (@INC contains: /Users/Scott/usr2/local/Cellar/automake/1.16.1/share/automake-1.16 /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/Scott/usr2/local/bin/aclocal line 36.
BEGIN failed--compilation aborted at /Users/Scott/usr2/local/bin/aclocal line 36.
autoreconf: aclocal failed with exit status: 2
```

**Comment by skaht** [comment]
Concerning **automake**, documentation at https://github.com/libbitcoin/libbitcoin-system/blob/version2/README.md#using-homebrew should be revised, version 1.16.1_1 was needed.

**Comment by evoskuil** [comment]
Looks like you were building with the origin repo version of secp256k1, which isn't supported. The reason is that the interface changes but the version is never updated, so proper detection is impossible. We maintain a fork with known-good snapshots on version branches for each breaking change that we have tested agaist.
