### ISSUE TITLE
Release latest builds as binary?

### ISSUE THREAD

**Issue by SCBuergel** [libbitcoin/libbitcoin-explorer#659]
I see that the latest binary releases are fairly outdated (version 3.2). I suggest that you release the latest version as binary.

**Comment by thecodefactory** [comment]
@SCBuergel Can we assign this one to you? :wink:

**Comment by SCBuergel** [comment]
1) Yes, happy to help!
2) Not sure if you want a rando from the internet pushing binaries around for you though ;)
3) If you direct me somewhere, I could take a stab at it.

**Comment by evoskuil** [comment]
You sign them you own them. 😁

Builds are single executable binary, statically-linked. Ubuntu, macOS and Windows. Windows built with VS solution files, others with install.sh. Non-debug with symbols stripped (macOS and Ubuntu). Signed by hashing binary and signing hash with PGP. See: https://github.com/libbitcoin/libbitcoin-explorer/wiki/Download-BX and https://github.com/libbitcoin/libbitcoin-server/wiki/Download-BS

**Comment by thecodefactory** [comment]
@SCBuergel Great news!  Several requests for Windows binaries have been made over time, both for latest pre-release v4, but more so for production version3.  Any progress made there will surely help the community. Thanks for taking a look at this!

**Comment by evoskuil** [comment]
This is a matter of our process, just hasn't happened in a while. I'll be doing this once I have the builds all cleaned up and tagged for new boost, secp256k1, libzmq, and ICU dependencies and current compilers.
