### ISSUE TITLE
wiki: bx-wif-to-public.md code block Example 3

### ISSUE THREAD

**Issue by RandyMcMillan** [libbitcoin/libbitcoin-explorer#663]
https://github.com/RandyMcMillan/libbitcoin-explorer-wiki/blob/master/bx-wif-to-public.md#example-3

![Screen Shot 2020-01-30 at 6 06 28 AM](https://user-images.githubusercontent.com/152159/73444702-21ea2500-4327-11ea-8b8f-84d685472878.png)

commit on master branch: 9087fd661d8a2d422d1d59d58c2821ccdaa43f27
https://github.com/RandyMcMillan/libbitcoin-explorer-wiki.git

**Comment by thecodefactory** [comment]
@RandyMcMillan Is this a question?

```
$ bx ec-to-wif 8ed1d17dabce1fccbbe5e9bf008b318334e5bcc78eb9e7c1ea850b7eb0ddb9c8
L21LJEeJwK35wby1BeTjwWssrhrgQE2MZrpTm2zbMC677czAHHu3

$ bx ec-to-wif 8ed1d17dabce1fccbbe5e9bf008b318334e5bcc78eb9e7c1ea850b7eb0ddb9c8 | bx wif-to-public
0247140d2811498679fe9a0467a75ac7aa581476c102d27377bc0232635af8ad36
```

**Comment by RandyMcMillan** [comment]
Github corrects the issue when it is displayed on github.com - but to be more consistent - an empty line before a code block will display correctly in the majority of markdown editors...

```sh

```


 (it is one of the quirks of markdown)

if you download the wiki and view the markdown on your local machine - the issue may be more obvious.



![Screen Shot 2020-03-08 at 6 10 20 AM](https://user-images.githubusercontent.com/152159/76160834-df74ee80-6103-11ea-8096-b80f8ed9a399.png)

I think there are more of these throughout the wikis.

Q. Is there a better way to submit PRs for the wiki?

**Comment by evoskuil** [comment]
I don’t see a problem in any context. What’s the issue?

**Comment by RandyMcMillan** [comment]
If the user downloads the wiki and views it in a markdown client - it will likely NOT display correctly.

**Comment by thecodefactory** [comment]
@RandyMcMillan Ah, ok.  I'm not at all familiar with offline markdown clients.  If I can find one that works with the site, I'll give a go.  Any recommendations for GNU/Linux by chance?

**Comment by RandyMcMillan** [comment]
Maybe just vim with a markdown plugin.

PS - I know this is probably nit-pick stuff...but I think that local viewing of the wiki should be considered. That is how I found the issue in the first place. 

I would be happy to do some of the work - but as we can see - there isn't a public repo for the wiki itself - unless it is hosted else where? 

Peace,

RM

**Comment by evoskuil** [comment]
What exactly is meant by “not display correctly”... image?

**Comment by thecodefactory** [comment]
> Maybe just vim with a markdown plugin.

Very cool, but unfortunately not a supported use-case (at least. known to me)

> PS - I know this is probably nit-pick stuff...but I think that local viewing of the wiki should be considered. That is how I found the issue in the first place.

Not a problem, understood.

> I would be happy to do some of the work - but as we can see - there isn't a public repo for the wiki itself - unless it is hosted else where?

The wiki itself is public, but I think github team permissions need to be granted for editing it (not sure).  That said, it's not clear this is a direction worth spending time on.  The screenshot looks like a readable text rendering of the content.  I would think there's a compromise of the online rendering for the offline rendering, and if that's the case, it's likely not worth the trade-off.  If that's definitely not the case (I'm no markdown expert ;-), it would be good to know.

The original issue created was extremely ambiguous and I didn't realize it was a rendering issue until very recently.

**Comment by evoskuil** [comment]
I do not see any rendering issue or markdown issue, so I’m just confused.

**Comment by thecodefactory** [comment]
If I understand it correctly, it has something to do with being able to see the markdown quote tags, rather than how github renders that as a newline afterward.  So sequential uses show no newlines in text (kind of like how it's edited/written), rather than a block/newline/block.  Not sure myself though.  

It looks like opening the raw file in emacs/vim to me, so it's more or less expected, but I don't know 'markdown modes'.
