### ISSUE TITLE
error : reference to seed is ambiguous

### ISSUE THREAD

**Issue by MountainMan87119** [libbitcoin/libbitcoin-explorer#664]
//#include <bitcoin/bitcoin.hpp> 

#include <bitcoin/system.hpp>
#include <boost/system/config.hpp>

#include <boost/random/detail/seed.hpp>
#include <bitcoin/explorer/commands/seed.hpp>

#include <bitcoin/client.hpp>
#include <bitcoin/explorer.hpp>
#include <bitcoin/network.hpp>
#include <bitcoin/protocol.hpp>
#include <boost/filesystem.hpp>
#include <bitcoin/system/define.hpp>
#include < string >
#include < iostream >

using namespace bc;
using namespace libbitcoin;
using namespace explorer;
using namespace commands;
using namespace system;
using namespace wallet;
using namespace electrum;
using namespace std;

int main()
{

        // cout << "seed, LOL.  Since you so desperately insist!" << endl;
        cout << seed << endl;
}

[LibBitUzr@bryanlaptop LibBitcoinBX4]# g++ -std=c++11 -o MW1L_Exercise_1ne MW1L_Cpp_Exercise_1ne.cpp -I/home/LibBitcoinBX4/include -DWITH_ICU -DWITH_PNG -DWITH_QRENCODE -I/home/LibBitcoinBX4/include -I/home/LibBitcoinBX4/etc/libbitcoin/ -L/home/LibBitcoinBX4/include -lbitcoin-system -L/home/LibBitcoinBX4/lib -lboost_chrono -lboost_date_time -lboost_filesystem -lboost_iostreams -lboost_locale -lboost_log -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread -lrt -ldl

Compiler Output Follows::

MW1L_Cpp_Exercise_1ne.cpp: In function ‘int main()’:
MW1L_Cpp_Exercise_1ne.cpp:57:10: error: reference to ‘seed’ is ambiguous
  cout << seed(16) << endl;
          ^
In file included from /home/LibBitcoinBX4/include/bitcoin/system.hpp:214:0,
                 from MW1L_Cpp_Exercise_1ne.cpp:28:
/home/LibBitcoinBX4/include/bitcoin/system/wallet/electrum.hpp:60:12: note: candidates are: enum class libbitcoin::system::wallet::electrum::seed
 enum class seed : uint8_t
            ^
In file included from MW1L_Cpp_Exercise_1ne.cpp:33:0:
/home/LibBitcoinBX4/include/bitcoin/explorer/commands/seed.hpp:64:15: note:                 class libbitcoin::explorer::commands::seed
 class BCX_API seed
               ^
[LibBitUzr@bryanlaptop LibBitcoinBX4]#

The bx commands are available and work
> from the commandline, ie.;
[LibBitUzr@bryanlaptop bin]# ./bx seed
3214f9fd4d01d7122fa1d581f8866b78312ce3112e1ed5a1
[LibBitUzr@bryanlaptop bin]#

> from within a BASH script

[[[[
#!/bin/bash
: <<'END_COMMENT'
FileNAME  ::  "Just_BX_Me_Vs1.sh"
END_COMMENT

cd /home/LibBitcoinBX4/bin
./bx seed
]]]]

[LibBitUzr@bryanlaptop LibBitcoinBX4]# ./Just_BX_Me_Vs1.sh
cb52a97ebb23da21a4979a5ee52355eafe57e67d54522fc3
[LibBitUzr@bryanlaptop LibBitcoinBX4]#

I suspect that, with libbitcoin-explorer 4.0.0, this is no longer
a valid include...

//#include <bitcoin/bitcoin.hpp>
and as one can see at the top of this question, I have commented it out.
However, the #include (s) I have placed, are just guess~work.  Is there a
"magic bullet" #include which I have been unable to locate?

I had some errors as well, regarding a PATH issue.
reproducing it here just to illustrate the lengths I am willing to go to to try to get
things sorted!

ERRORS:
In file included from /home/LibBitcoinBX4/include/bitcoin/system.hpp:50:0,
                 from MW1L_Cpp_Exercise_1ne.cpp:29:
/home/LibBitcoinBX4/include/bitcoin/explorer/command.hpp: In function ‘boost::filesystem::path libbitcoin::explorer::config_default_path()’:
/home/LibBitcoinBX4/include/bitcoin/system/config/directory.hpp:46:29: error: ‘SYSCONFDIR’ was not declared in this scope
         CONFIG_DEFAULT_PATH(SYSCONFDIR, relative)
                             ^
/home/LibBitcoinBX4/include/bitcoin/system/config/directory.hpp:34:46: note: in definition of macro ‘CONFIG_DEFAULT_PATH’
         const boost::filesystem::path folder(directory); \
                                              ^
/home/LibBitcoinBX4/include/bitcoin/explorer/command.hpp:59:1: note: in expansion of macro ‘BC_DECLARE_CONFIG_DEFAULT_PATH’
 BC_DECLARE_CONFIG_DEFAULT_PATH("/home/LibBitcoinBX4/etc/libbitcoin" / BX_PROGRAM_NAME ".cfg")

Eventually dug deep enough to make changes to a couple of files, generated code,
here was one such.
directory.hpp

(((((((
#include <string>
#include <boost/filesystem.hpp>
#include <bitcoin/system/define.hpp>

namespace libbitcoin {
namespace system {
namespace config {

// Declare config_default_path() via BC_DECLARE_CONFIG_DEFAULT_PATH(relative).
#define CONFIG_DEFAULT_PATH(directory, subdirectory) \
    static boost::filesystem::path config_default_path() \
    { \
        const boost::filesystem::path folder("/home/LibBitcoinBX4/etc/libbitcoin"); \
        return folder / subdirectory; \
    }
// PsalmSunday February 2020.  Editing the line *** const boost::filesystem::path folder(directory); ***
// to:
// const boost::filesystem::path folder("/home/LibBitcoinBX4/etc/libbitcoin");
)))))))

Worked through a lot of things to get the compile but as of now the focus is just on
learning enough to get at least the simplest of bx commands up and running.  Should
give me a boost  (bad pun) to get more and more then.

Any tips would be so much appreciated.
I have the 19,000 +/- lines of output from installation, but doubt it is needed.

**Comment by thecodefactory** [comment]
@MountainMan87119 The C++ you provided should not compile, as it's referencing a variable that doesn't exist.  I'm assuming you meant something like "new_seed", which is a utility function in libbitcoin-explorer, but not generally a good one to rely on, since it's just generating a pseudo-random number.  All that aside, I think something like this could get you going:

Edit seed.cpp:

```
#include <bitcoin/system.hpp>

using namespace bc;
using namespace bc::system;

// Borrowed from:                                                                                                                           
// https://github.com/libbitcoin/libbitcoin-explorer/blob/master/src/utility.cpp#L69                                                        
data_chunk new_seed(size_t bit_length)
{   
    size_t fill_seed_size = bit_length / byte_bits;
    data_chunk seed(fill_seed_size);
    pseudo_random_fill(seed);
    return seed;
}

int main(int argc, char **argv)
{   
    const auto bit_length = 256;
    const auto seed = new_seed(bit_length);

    std::cout << encode_base16(seed) << std::endl;
    return 0;
}
```

To compile:

```
# If needed, export PKG_CONFIG_PATH
$ export PKG_CONFIG_PATH=$libbitcoin_install_dir/lib/pkgconfig
...
$ g++ seed.cpp -o seed $(pkg-config --cflags --libs libbitcoin-system)
$ ./seed
976e7489c8b316d009dd9e7d752a9d5bd3b0ddcb5a59851e19d174be87991b5f
```

**Comment by MountainMan87119** [comment]
Hello,

Just a reply to ack your assistance.

Will begin working with the suggestions pronto

Thank ever so much!

~B.

**Comment by thecodefactory** [comment]
No problem, good luck!
