### ISSUE TITLE
P2WPKH and P2WSH addresses with bx?

### ISSUE THREAD

**Issue by fazlearefin** [libbitcoin/libbitcoin-explorer#665]
Is it possible to generate **P2WPKH** and **P2WSH** addresses with `bx`?

**Comment by evoskuil** [comment]
No, though I believe there is an outstanding feature request for this.

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-explorer/issues/520#issuecomment-593030807

**Comment by evoskuil** [comment]
Closed as answered/duplicate.

**Comment by thecodefactory** [comment]
Yes, see https://github.com/libbitcoin/libbitcoin-explorer/pull/627
