### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by Barno** [libbitcoin/libbitcoin-explorer#666]
Hello,
After use homebrew and install.sh, I get this error When I attempt to use it.

```
$ bx
dyld: Symbol not found: __ZN10libbitcoin3cinE
  Referenced from: /usr/local/bin/bx
  Expected in: /usr/local/opt/libbitcoin/lib/libbitcoin.0.dylib
 in /usr/local/bin/bx
[1]    39741 abort      bx
```

**Comment by evoskuil** [comment]
Hello. What are you installing using homebrew? Is the libbitcoin lib in the referenced directory?

**Comment by Barno** [comment]
Yes `I'm using homebrew` and then `./install.sh --prefix=/Users/barno/libbitcoin_cli --build-boost --build-zmq --disable-shared`. I'm using Catalina (10.15.4)

**Comment by evoskuil** [comment]
Is Libbitcoin in the referenced directory?

/usr/local/opt/libbitcoin/lib/

**Comment by Barno** [comment]
in /usr/local/opt/libbitcoin/lib/ I can see
```
-r--r--r--  1 barno  staff   2.4M Feb 19 09:49 libbitcoin.0.dylib
-r--r--r--  1 barno  staff    13M Aug 29  2019 libbitcoin.a
lrwxr-xr-x  1 barno  staff    18B Aug 29  2019 libbitcoin.dylib -> libbitcoin.0.dylib
drwxr-xr-x  3 barno  staff    96B Feb 19 09:49 pkgconfig
```

$ which bx
`/usr/local/bin/bx`

thanks

**Comment by evoskuil** [comment]
You built bx using the install.sh and used the `--prefix` setting. This would not place either bx or libbitcoin into the directories you are showing me. They would be in the prefix directory.

**Comment by thecodefactory** [comment]
@Barno Any update here?

**Comment by Barno** [comment]
I did several tests, uninstall, install (with homebrew) , and now it's works :) thanks
