### ISSUE TITLE
"connection timed out" for all client commands

### ISSUE THREAD

**Issue by xloem** [libbitcoin/libbitcoin-explorer#669]
I'm new to `bx` and haven't been able to get it to work.

OS: Ubuntu 20.04
bx: 3.6.0
libzmq: v4.3.2

I can form a TCP connection to servers using netcat but none of the bx commands like `fetch-height` are working.  Is there a chat channel somewhere for this project?

**Comment by thecodefactory** [comment]
Freenode IRC: #libbitcoin
Slack: https://join.slack.com/t/libbitcoin/shared_invite/enQtNDgxMjQxODg0NTM1LTFhYzNhYjYxYTg1OTc0NGQ0OWQxY2ZiYWI5ODc1ZmFjZjEyNGZkNWQwM2JiMzk0YjhkMDc0MjkxOTgwMzQ0ZDM

**Comment by thecodefactory** [comment]
Retry and then close this issue please

**Comment by xloem** [comment]
Thanks.  Guess had an issue.  I'm curious if there is a way to detect the issue on my end.

**Comment by thecodefactory** [comment]
> Thanks. Guess the server had an issue? I'm curious if there is a way to detect the issue on my end.

I think you just did ;-)

**Comment by thecodefactory** [comment]
> Thanks. Guess the server had an issue? I'm curious if there is a way to detect the issue on my end.

Really, the best way is to run your own server locally and test against it.  Community/public servers are a convenience, but not required.

**Comment by xloem** [comment]
Okay, since I could netcat to the server ports fine it wasn't clear that it wasn't a misconfiguration or library linking issue.  Thanks.
