### ISSUE TITLE
change from default for mainnet to testnet

### ISSUE THREAD

**Issue by tobben1998** [libbitcoin/libbitcoin-explorer#671]
Can anyone help with changing default settings from mainnet to testnet, so I do not always have to use -c testnet.cfg on every thing I do?

**Comment by thecodefactory** [comment]
Edit `libbitcoin-explorer/data/bx.cfg` and update all of the settings that show the proper defaults for testnet [(see bx.cfg for reference)](https://github.com/libbitcoin/libbitcoin-explorer/blob/master/data/bx.cfg) and save that file to `/some/path/bx.cfg`.  After that, `export BX_CONFIG=/some/path/bx.cfg` (or set the env var appropriately for your shell) and then use bx as normal.
