### ISSUE TITLE
hi, my raw signed tx was created with unnecessarily high s values...

### ISSUE THREAD

**Issue by DHB94** [libbitcoin/libbitcoin-explorer#672]
i was wondering if somebody could help me fix my tx please ?
sudo wine bx-windows-x64-icu.exe tx-encode -i 97facbd7e07c4f3140d9ea167c2e54d85bc5f6fd04d9774d80b1284b706920ff:1 -o 1EhPYu17SHdbpcgy8TRgphnEjtznFiz3Wk:6937008220000

sudo wine bx-windows-x64-icu.exe input-set "[3045022100c9f051042467433b2199526db1ba327154d2bcd7c90c40070ba06869c551219402204eeb906f053812f248e2d0f36e0cf3ace99bcc21a6a25921e39011ad5f298db601] [02545d2c25b98ec8827f2d9bee22b7a9fb98091b2008bc45b3b806d44624dc038c]" 0100000001ff2069704b28b1804d77d904fdf6c55bd8542e7c16ead940314f7ce0d7cbfa970100000000ffffffff010316e9254f0600001976a914963d18ef70ab28a0dbd15944721eb5673341db7a88ac00000000 
resulted in this tx 0100000001ff2069704b28b1804d77d904fdf6c55bd8542e7c16ead940314f7ce0d7cbfa97010000006b483045022100c9f051042467433b2199526db1ba327154d2bcd7c90c40070ba06869c551219402204eeb906f053812f248e2d0f36e0cf3ace99bcc21a6a25921e39011ad5f298db6012102545d2c25b98ec8827f2d9bee22b7a9fb98091b2008bc45b3b806d44624dc038cffffffff010316e9254f0600001976a914963d18ef70ab28a0dbd15944721eb5673341db7a88ac00000000
![image1](https://user-images.githubusercontent.com/35415891/95687757-9b832400-0bd3-11eb-977d-f74c1d53b7df.jpeg)
![image0](https://user-images.githubusercontent.com/35415891/95687759-9cb45100-0bd3-11eb-9ee6-067c3e438800.jpeg)

**Comment by thecodefactory** [comment]
This post is very confusing.  Why run a windows binary through wine, instead of running natively?  Also, did you build the binaries, or are they the older outdated ones?  There are no publicly available modern binaries available for bx, so building it yourself is advised.

**Comment by DHB94** [comment]
Hi, I built the binaries for 3.6.0 after you said it would be better but the tx I created either will say stack false when validating tx or when broadcasting via bitaps or other services as well as bitcoin core,
 it will say mandatory-script-verify-flag-failed (Non-canonical signature: S value is unnecessarily high) (code 16) and that is my issue that I was hoping someone could help me correct :)

**Comment by DHB94** [comment]
> This post is very confusing. Why run a windows binary through wine, instead of running natively? Also, did you build the binaries, or are they the older outdated ones? There are no publicly available modern binaries available for bx, so building it yourself is advised.

I changed that behavior to avoid confusion.
So basically I’m having issues with my transactions being accepted.
 The following error is displayed in the picture.
![054C0973-08F4-4C85-9AFE-131D2A969D84](https://user-images.githubusercontent.com/35415891/95863682-7c4ed880-0d32-11eb-93c5-d1a11c919d15.png)

**Comment by evoskuil** [comment]
This appears to be a usage question. Please take up with the community on slack or IRC.
