### ISSUE TITLE
Detect fees

### ISSUE THREAD

**Issue by xloem** [libbitcoin/libbitcoin-explorer#673]
Is there some way other than trial and error to discern the minimum fees the connected node will accept?

**Comment by evoskuil** [comment]
You could contact the node owner. Otherwise you could wait to receive a `feefilter` message, though that’s not a guarantee.

**Comment by xloem** [comment]
This sounds like a missing interface function; would you agree?

**Comment by evoskuil** [comment]
No

**Comment by xloem** [comment]
Well, I'm trying to figure out where to plan possible PRS.  Would that be as a matter of policy or effort?

**Comment by evoskuil** [comment]
Neither, it’s a matter of protocol.

**Comment by xloem** [comment]
I'm thinking it could be nice to add to the libbitcoin client/server protocol so as to retrieve the configured fees at https://github.com/libbitcoin/libbitcoin-server/blob/a64da765481528a95f9364adac7ac3b35111f89d/data/bs.cfg#L233

**Comment by evoskuil** [comment]
The c/s interface doesn’t currently expose an administrative interface, though it’s envisioned. But this wouldn’t help with the general question of “the connected node” because nodes utilize the p2p network interface, not the Libbitcoin c/s interface.

**Comment by xloem** [comment]
Sorry for using the wrong word: I meant the libbitcoin-server that libbitcoin-explorer connects to when you run `bx send-tx`.  Wouldn't it make sense to show the configuration or at least minimum fees in the output of some `bx fetch` or `bx settings` command?  It sounds like that might go near administrative controls.

**Comment by evoskuil** [comment]
Asking the server for its configuration is what I would call administrative. But knowing the one server’s config doesn’t actually help much.

**Comment by xloem** [comment]
It helps to know a server will hold a transaction on the network; and the configuraton of a server indicates the configurations of other similar servers.  I'll slot this idea near administrative features for libbitcoin-server, but I infer it's not your favorite feature request.

**Comment by evoskuil** [comment]
Actually it tells you nothing about the configuration of other servers. I would expose all config through a public and/or private set of interfaces.

**Comment by xloem** [comment]
Well provably no, but statistically people do similar things.  Okay, sounds like config exposure sounds reasonable.

**Comment by evoskuil** [comment]
Yes, default fees are set as DOS protection. Ideally one (especially a miner) wants all valid transactions but with fees set too low the store can be overflowed at zero or low cost.
