### ISSUE TITLE
Build Problem - 'sys/types.h' file not found

### ISSUE THREAD

**Issue by chris-pollard** [libbitcoin/libbitcoin-explorer#692]
Boost Build boostrap.log: fatal error: 'sys/types.h' file not found
#include <sys/types.h>

using .zsh and MacOSX11.3.sdk

Environment variable set in .zshrc as CFLAGS="-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.7" based on answer to similar problem from a build github repo [comment](https://github.com/codebutler/firesheep/issues/169#issuecomment-6985466) for Firesheep.

Not sure what I'm doing wrong here. /usr/include/sys/types.h exists in MacOSX11.3.sdk directory.

**Comment by evoskuil** [comment]
Build command line?

**Comment by chris-pollard** [comment]
$ ./install.sh --prefix=/home/me/myprefix --build-boost --build-zmq --disable-shared

**Comment by evoskuil** [comment]
Maybe look at our macOS Travis builds, which don’t show this problem.

**Comment by chris-pollard** [comment]
Apologies for my ignorance, but where are your macOS Travis builds I can't seem to find them.

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-explorer/blob/master/README.md

Green button, first two builds.
