### ISSUE TITLE
hd-new returning a public key in one of the examples in the wiki

### ISSUE THREAD

**Issue by grondilu** [libbitcoin/libbitcoin-explorer#694]
In example 5 :

```
$ bx hd-new -v 70615956 baadf00dbaadf00dbaadf00dbaadf00d
tpubD6NzVbkrYhZ4XbUpwb3JpXFpXXa8CrP8cTkqzrnsnPV6Z1v3C15HRcUquADA8CMEawvRMMGoKnwg8fza8pPdFUcJH6uxZJJKkDYJJAGT53e
```

Shouldn't it return a private key (tprv...) instead?

**Comment by evoskuil** [comment]
The tea case is here. Looks like a cut/paste error in the wiki.

**Comment by evoskuil** [comment]
Resolved, was just a paste error into the wiki - thanks!
https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-hd-new
