### ISSUE TITLE
Building bx tool Windows under VS2019 community fails

### ISSUE THREAD

**Issue by dynamo-foundation** [libbitcoin/libbitcoin-explorer#695]
All the other libs build fine, including explorer.  When I go to build bx, I get this:

LNK1104	cannot open file 'libboost_filesystem-vc142-mt-s-x32-1_72.lib'

All the dependencies were resolved using VS Nuget package manager.  Tried "static debug" and "static release" configurations.

Forked from master branch.

**Comment by evoskuil** [comment]
vc142 is VS2019, which is not yet supported. If you open the solution in VS2019 you must not allow it to upgrade the solution.

**Comment by dynamo-foundation** [comment]
Ok cool, thanks!  Is this a priority to fix?  Do you want me to make a PR for it?  I'm guessing this just involves swapping some boost libs.

**Comment by evoskuil** [comment]
It’s a lot more than that, it’s coming eventually.

**Comment by evoskuil** [comment]
Closing as not yet supported.
