### ISSUE TITLE
'bx hd-private' not matching BIP85 Child Key in Mnemonic Code Converter

### ISSUE THREAD

**Issue by kenorb** [libbitcoin/libbitcoin-explorer#698]
I'm playing with [Mnemonic Code Converter](https://iancoleman.io/bip39/) site by following step by step conversion, however I can't get pass _BIP85 Child Key_.

So, for the given 3 words: `client mixed great`, I've generated successfully _BIP32 Root Key_ (which matches the site):

```
$ echo client mixed great | bx mnemonic-to-seed | bx hd-new 
xprv9s21ZrQH143K3UX3BhXusdpBUSLW3KVBCV6DGAuAKoXumU9chwDWjT9gcxjyFs8YdBxysyvZx2yC6snUBhb46wwXeq5xNqRjx5WkD8bbxYf
```

Then I've clicked _Show BIP85_ (in order to generate _BIP85 Child Key_) and set _BIP85 Application_ to _Xpriv_, and _BIP85 Index_ to 0, and it generated a different key than:

```
$ echo client mixed great | bx mnemonic-to-seed | bx hd-new | bx hd-private -i 0
xprv9v6WUZT3D9NryJcPMGBxrauhE42egVktC9mwLKFuZUjinZencdiZ21d43oye8rX83cEjfAKptfaoceUYctptAhc2UUM398Akf9n6qXzd8RQ
```

I've tried a hardened key, doesn't help either:

```
$ echo client mixed great | bx mnemonic-to-seed | bx hd-new | bx hd-private -i 0 -d
xprv9v6WUZTBYouqAnZyHm1P76SvmRrmpvteFo2PhncirF6BNj2kr6qzTRJzJ41a5wwWKf35AjwtxDJEJ2U72H9g4LGj38Ytg2SzEfTQDVhEWB3
```

What I am missing?

**Comment by evoskuil** [comment]
You can review the `hd-private` [test cases](https://github.com/libbitcoin/libbitcoin-explorer/blob/master/test/commands/hd-public.cpp), which demonstrate conformance with standard vectors. Maybe compare these to the site results.
