### ISSUE TITLE
bx fetch-balance -> wrong results of [receive & spent]

### ISSUE THREAD

**Issue by selffik** [libbitcoin/libbitcoin-explorer#700]
Input: #bx fetch-balance 1JSpE7i3xncuirvQvRqjRFQ8g1gUynePDB
Output: 
balance
{
    address 1JSpE7i3xncuirvQvRqjRFQ8g1gUynePDB
    received 18446744073709551615
    spent 18446744073709551615
}

**Comment by evoskuil** [comment]
I suggest to use `fetch-history` to identify the incongruity. This can be affected by the height of the node/server, which can be determined by `fetch-height`.
