### ISSUE TITLE
newbee issue with installation - tips welcome 

### ISSUE THREAD

**Issue by Mikester0981** [libbitcoin/libbitcoin-explorer#702]
Linux Mikker 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ ./install.sh --prefix=/home/Mikker/myprefix --build-boost --build-zmq --disable-shared

I'm doing everything according to the instructions, just I think I'm messing up something related to the correct "prefix". 
I cannot find guidance in the documentation or wiki so I'm reaching out here.

Should I use my name "Mikker" instead of "me" and choose a "myprefix" myself or should I make precisely these folders in advance?
When running it like this:
$ ./install.sh --prefix=/home/Mikker/myprefix --build-boost --build-zmq --disable-shared
everything seems to install fine (~25min) but command 
$ bx 
does return
bx: command not found 

Any help or tips are welcome!
Thanks a lot!

**Comment by thecodefactory** [comment]
Since it was installed to `/home/Mikker/myprefix`, try something like:

```
$ /home/Mikker/myprefix/bin/bx
```

Or you could maybe do:

```
$ export PATH=/home/Mikker/myprefix/bin
$ bx
```

**Comment by Mikester0981** [comment]
Dear thecodefactory,
Excellent, that worked right away. Thanks a thousand times.

**Comment by thecodefactory** [comment]
Great, glad to hear!
