### ISSUE TITLE
Can't build bx on ubuntu server following instructions.

### ISSUE THREAD

**Issue by MichielBruijn** [libbitcoin/libbitcoin-explorer#705]
I followed [these](https://github.com/libbitcoin/libbitcoin-explorer#debianubuntu) instructions and received a lot of errors. 

I'm noob but installed and used bx in the past on older systems

[These](https://pastebin.com/XG4r5tV4) are the errors.
I also tried to install boost package libboost1.74-all-dev and skip the --build-boost

My system is Ubuntu server 21.10 (GNU/Linux 5.13.0-40-generic x86_64)

**Comment by evoskuil** [comment]
Hello, we recommend against a sudo build into a shared directory. This can lead to problems with boost linkage. However that may not be the problem here, as the boost compile itself is failing. What is the version of the c++ compiler in use?

**Comment by evoskuil** [comment]
Closing for lack of response.
