### ISSUE TITLE
'fetch-block' is not a bx command

### ISSUE THREAD

**Issue by ardabro** [libbitcoin/libbitcoin-explorer#708]
I'm very new to this software. I successfully installed libbitcoin-explorer. I see that some inline commands work but "fetch-block" seems not to exist. "help" command does not mention it either. How to understand this fact?

**Comment by evoskuil** [comment]
Hi. Please post the output of the help command here.

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-fetch-block

**Comment by ardabro** [comment]
./bx fetch-block --help 
'fetch-block' is not a bx command. Enter 'bx help' for a list of commands.

 ./bx

Usage: bx COMMAND [--help]

Version: 3.7.0

Info: The bx commands are:

address-decode
address-embed
address-encode
base16-decode
base16-encode
base58-decode
base58-encode
base58check-decode
base58check-encode
base64-decode
base64-encode
bitcoin160
bitcoin256
btc-to-satoshi
cert-new
cert-public
ec-add
ec-add-secrets
ec-multiply
ec-multiply-secrets
ec-new
ec-to-address
ec-to-ek
ec-to-public
ec-to-wif
ek-address
ek-new
ek-public
ek-public-to-address
ek-public-to-ec
ek-to-address
ek-to-ec
electrum-new
electrum-to-seed
fetch-balance
fetch-header
fetch-height
fetch-history
fetch-public-key
fetch-stealth
fetch-tx
fetch-tx-index
fetch-utxo
hd-new
hd-private
hd-public
hd-to-ec
hd-to-public
help
input-set
input-sign
input-validate
message-sign
message-validate
mnemonic-new
mnemonic-to-seed
qrcode
ripemd160
satoshi-to-btc
script-decode
script-encode
script-to-address
seed
send-tx
send-tx-node
send-tx-p2p
settings
sha160
sha256
sha512
stealth-decode
stealth-encode
stealth-public
stealth-secret
stealth-shared
token-new
tx-decode
tx-encode
tx-sign
uri-decode
uri-encode
validate-tx
watch-address
watch-stealth
watch-tx
wif-to-ec
wif-to-public
wrap-decode
wrap-encode

Bitcoin Explorer home page:

https://github.com/libbitcoin/libbitcoin-explorer

**Comment by evoskuil** [comment]
Thanks, the helps a lot. I’ll take a look.

**Comment by thecodefactory** [comment]
fetch-block was added to master, not the v3 series
