### ISSUE TITLE
Fail to do install.sh on reproducible Docker build

### ISSUE THREAD

**Issue by josvazg** [libbitcoin/libbitcoin-explorer#712]
This is the Dockerfile:

~~~Dockerfile
FROM debian:stable-slim

RUN apt update -y && apt install -y curl git autoconf automake libtool make \
                                    g++ pkg-config libboost-all-dev \
                                    libzmq3-dev libnorm-dev

RUN curl -LO https://raw.githubusercontent.com/libbitcoin/libbitcoin-explorer/version3/install.sh && \
    chmod +x install.sh && ./install.sh

CMD bash
~~~

This is the error:

~~~shell
*** Warning: Linking the shared library src/libbitcoin-protocol.la against the
*** static library libprotokit.a is not portable!
g++: error: libprotokit.a: No such file or directory
make: *** [Makefile:872: src/libbitcoin-protocol.la] Error 1
~~~

Note that `libprotokit.a` is provided by `libnorm-dev`.
~~~shell
root@289452cd0f7b:/# dpkg -L libnorm-dev |grep libprotokit.a
/usr/lib/x86_64-linux-gnu/libprotokit.a
~~~

What am I missing?

**Comment by evoskuil** [comment]
Sorry, no idea.

**Comment by pmienk** [comment]
Might want to try `--disable-shared` given that it's finding `libprotokit.a` and will favor the static library. Though your error appears to be telling you that the location of `libprotokit.a` isn't being provided.

I don't recognize `libprotokit.a` or `libnorm-dev` as required by either `libbitcoin-protocol` or `libbitcoin-explorer`.  More detail as to what you were trying to accomplish and where it failed would be useful.

**Comment by mehdi-sadighian** [comment]
juts edit the Makefile and remove libprotokit.a  from linker
