### ISSUE TITLE
Connecting the Bitcoin node to the libbitcoin explorer

### ISSUE THREAD

**Issue by Hossein-Teimouri** [libbitcoin/libbitcoin-explorer#725]
I have a full bitcoin node running locally on my server and now I want to connect the libbitcoin explorer library to it and interact with it but I don't know what to do please guide me

**Comment by pmienk** [comment]
Please see the [wiki](https://github.com/libbitcoin/libbitcoin-explorer/wiki). Without further information I don't anticipate anyone will be able to help you further.
