### ISSUE TITLE
Wiki Improvement (Strengthen warnings about `bx seed`)

### ISSUE THREAD

**Issue by Ademan** [libbitcoin/libbitcoin-explorer#727]
It doesn't look like I can issue PRs against the wiki directly, but I wanted to offer https://github.com/Ademan/libbitcoin-wiki/commit/eef7ca21a071a18675a6f833bd73b647c30efe1c as a quick improvement to strengthen the warnings about `bx seed` due to recent events.

There are a ton of references to `bx seed` throughout the wiki, and I think arguably all of them should carry warnings similar to what I added, but at the very least, the example on the homepage of the wiki should guide people towards an explanation of `bx seed`'s limitations.

**Comment by evoskuil** [comment]
Thanks, much appreciated.

**Comment by evoskuil** [comment]
@kulpreet this seems fine, please “merge” if you concur.

**Comment by pool2win** [comment]
Happy to merge. @Ademan can you make a pull request please?

**Comment by kulpreet** [comment]
Commit merged. Thanks @Ademan 

Closing the issue.

![image](https://github.com/libbitcoin/libbitcoin-explorer/assets/13216/f39733d4-6e2a-4163-bf20-509563a1e446)
