### ISSUE TITLE
Single executable file

### ISSUE THREAD

**Issue by barbarabhagsw** [libbitcoin/libbitcoin-explorer#738]
Hi, i can`t download the Single Executable File for Linux, can you please send it to me? Thank you so much.

**Comment by moznc** [comment]
I've just finished building v3.8.0: [bx_3.8.0.zip](https://github.com/libbitcoin/libbitcoin-explorer/files/12507609/bx_3.8.0.zip)

$ ./bx base16-encode < bx | ./bx sha256
eba4cfae45ef2ff23fbf96f7264ccdb80e6cb715cf3018793f94fbaeaace04f4

You should either wait for the maintainers, build it yourself, or use mine but don't trust me / use it for anything important.

**Comment by barbarabhagsw** [comment]
Hi. Thank you so much, but do you have the bx-linux-x64-qrcode (https://github.com/libbitcoin/libbitcoin-explorer/releases/download/v3.2.0/bx-linux-x64-qrcode)? I need this one too, thank you

**Comment by barbarabhagsw** [comment]
Hi. Thank you so much, but do you have the bx-linux-x64-qrcode Version 3.2.0 (https://github.com/libbitcoin/libbitcoin-explorer/wiki/Download-BX)? I need this one too, thank you

**Comment by moznc** [comment]
Are you trying to test milsad?
Anyway I don't have version 3.2.0. And bx-linux-x64-qrcode is bx, they just renamed it to that, not sure why.

**Comment by barbarabhagsw** [comment]
No, I need it because my friend made to me a program and I can’t use it because the link was removed

**Comment by pmienk** [comment]
You will need to build the appropriate version yourself. The binary has been removed and there is no plan to rebuild or restore the version you are seeking.
