### ISSUE TITLE
404 error on portable executable for Linux, OSX or Windows

### ISSUE THREAD

**Issue by adrastee** [libbitcoin/libbitcoin-explorer#743]
Hi,

https://github.com/libbitcoin/libbitcoin-explorer/releases/download/v3.2.0/bx-windows-x64-icu.exe
leads to 404 error.
Same for Linux and MacOS.

What's the link please?

"t can be built as a single portable executable for Linux, OSX or Windows and is available for [download as a signed single executable](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Download-BX) for each."

**Comment by pmienk** [comment]
Binaries have been removed and are not available at this time.

**Comment by adrastee** [comment]
Why not?

The only binary I could find is version 2.2.0 from https://github.com/libbitcoin/libbitcoin-explorer/releases/download/v2.2.0/bx-linux-x64-mainnet
