### ISSUE TITLE
Since Boost 1.82, C++14 is minimum requirement for Boost.Math

### ISSUE THREAD

**Issue by ptrdsh** [libbitcoin/libbitcoin-explorer#751]
When building on Mac with M1 using install-cmake.sh, i get this error in multiple occasions. 

```
/opt/homebrew/include/boost/multiprecision/detail/standalone_config.hpp:36:7: warning: "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)" [-W#warnings]
 #    warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)"
      ^
```

**Comment by evoskuil** [comment]
Thanks for posting. Libbitcoin v4 uses c++20, so this won’t be an issue. Libbitcoin v3 uses c++11 and older versions of boost, so this will also not be an issue.

**Comment by evoskuil** [comment]
The maximum Boost for libbitcoin version3 is 1.76 due to lack of Boost backward compatibility, though the build tools do not allow for this restriction.
